### ISSUE TITLE
Question: OCR processing

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#100]
I have a question about the OCR processing function. I started a OCR process and the "not OCR processed" changed into "processing". Then I waited and nothing happened. Then I reloaded the todo component in the hopes of now seeing the processed file but the file is back to "not OCR processed".
1. Do I stop the processing by refreshing the todo component? 
2. Or is my request still in the queue of OCR files and I am just not seeing this?
3. When I try to process the same file again (because I think it didn't work/stopped processing), do I add a file to the OCR queue and therefore make the queue even longer?

Edit: My first two question were just answered because I see the file is now processed. Is there a possibility to keep the "processing" information even if I reload the todo component? Because otherwise it is pretty confusing.

**Comment by anlausch** [comment]
Yes, when you trigger the ocr processing for a file that's still in the ocr queue, the file gets added to the queue again.

**Comment by lgalke** [comment]
Agreed. For now i set a front-end-specific status `'OCR_PROCESSING'` but the back-end until now never gets to know about this. Therefore after reloading the status is reset to either UNPROCESSED or PROCESSED and a second trigger would cause the file to be append another time to the queue.

**Comment by anlausch** [comment]
I introduced a new status OCR_PROCESSING, which is set to the scan triggered for ocr processing before it is sent to the ocr component. After the processing finishes, the status is set to OCR_PROCESSED, as before.

**Comment by lgalke** [comment]
It is reflected in the front-end already. Thus we can close this issue.
