### ISSUE TITLE
pdf as background image

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#102]
The textual PDFs gets converted to images in the OCR-Component. However the filetype of the images is still `pdf`. This causes problems since we assume the image to be displayable inside a `<img src=''>` tag.
We might be able to adjust this to `<iframe>` in case the link name ends with `.pdf`, but that requires special browser dependencies (Acrobat, Foxit,...). We will try to adjust it and hope that the bounding boxes via `<svg>` still work. However, please let me know in case the output format of the textual pdf to image conversion is just a matter of setting some value to `png`. That would save a lot of work.

**Comment by anlausch** [comment]
There should be .png's returned. I created a working example using the frontend and I can see that it gets rendered. The only problem seems to me regarding that, that the bounding boxes do not fit always the referenced text.

Also, there is now an issue with the status. Let's talk about that today.

**Comment by lgalke** [comment]
Good to know, then we can exclude this possibility.

**Comment by anlausch** [comment]
I introduced a new status OCR_PROCESSING, which is set to the scan triggered for ocr processing before it is sent to the ocr component. After the processing finishes, the status is set to OCR_PROCESSED, as before.

**Comment by lgalke** [comment]
They are actually pngs, not a problem anymore.
