### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#103]
Currently, I can't logging. The message `Invalid credentials.` appears:

![invalid-credentials](https://user-images.githubusercontent.com/5199995/32133340-238315fa-bbd6-11e7-9150-eb2c337c918f.jpg)

**Comment by LauraErhard** [comment]
I don't have this issue. Maybe it was temporary?

**Comment by lgalke** [comment]
Could it be possible that your IP was not white-listed at that point? The IP restriction is also still active.

**Comment by zuphilip** [comment]
Yeah, I tried it at home. After connecting to VPN it works now. But the message is wrong, if it is related to IP restriction.

Moreover, how will this work in the workshop? The people there will have an IP from eduroam or some guest WLAN?

**Comment by lgalke** [comment]
Yea, we should be aware of this. These IPs from eduroam are not white-listed? Maybe it would be the time now to create some fixed `locdb/workshop` credentials, disable the possibility of `Sign Up` and then to disable the IP restriction?

**Comment by anlausch** [comment]
I see several options here, but that's definitely something that needs to be decided:
1) Maybe people have eduroam. Then there is no problem. But I think we should not assume that.
2) We only demo via our own devices. Then we should have access and we can control who does what with the system. Then we need to take care that we have enough devices available.
3) We ask the admin to open up the IP restriction for that particular day. 
Maybe there are even more possibilities. What do you think?

**Comment by kleinann** [comment]
I'd prefer 3.

**Comment by anlausch** [comment]
Ok, let's go for 3 together with the measures proposed by @lgalke.

**Comment by zuphilip** [comment]
The admin is Stefan, right? Should I talk to him?

**Comment by lgalke** [comment]
That would be great. Yes.

**Comment by zuphilip** [comment]
@stweil removed the IP restriction for now.

**Comment by lgalke** [comment]
Good, I will close the issue for now. More informative error messages are a general topic we need to address later.
