### ISSUE TITLE
Electronic journals preferred solution

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#104]
1. Electronic journals workflow starts with article metadata. Possible sources: 
Online Contents (OLC - interfaces: https://uri.gbv.de/database/olc) --> retrieved by ppn
Crossref --> retrieved by DOI
Frontend: Input of OLC ppn or DOI should be possible before or even without file upload.
Reason: For the (many) journals which have references on Crossref, it won't be necessary to upload a file. As that is a very efficient way of processing articles, it would be good to be able to demonstrate it at the workshop.
Result: Show article metadata in frontend

2. Show original article in seperate window
If input was OLC-ppn: extract DOI from article metadata, open link in seperate window.
If input was DOI: open link in seperate window.

3. Check if references are available on Crossref
If references are available: Skip file upload, show references, make them editable, link them to resources, save them, 
If references are not available: File upload (name of file is irrelevant), push file to OCR-component, proceed as usual.

See also examples here:
https://hackmd.io/CwYwzAZgDGCsIFoBMBGAbGBoqwQIzRRQQHYoo9ZQBDYKADhSA===?view

**Comment by anlausch** [comment]
Thanks for adding this more detailed description of what should happen. We will comment on this as soon as it is ready or more questions arise.

**Comment by anlausch** [comment]
@kleinann : What type is this file which you expect in step 3? An electronic pdf? Or is it the html source code? Thanks

**Comment by kleinann** [comment]
For now, an electronic pdf. Later (after the Workshop) maybe also html.

**Comment by anlausch** [comment]
The backend part should be fully implemented. Let me know how it goes @lgalke.

**Comment by lgalke** [comment]
Should work. All child issues are addressed. Do I manually need to call `/checkCrossRefReferences` or is it automatically triggered when `/saveElectronicJournal` is requested? @anlausch .

@kleinann @LauraErhard : can someone provide an example DOI?

**Comment by zuphilip** [comment]
Example: OLC PPN `1994632569` or DOI `10.1007/s11135-016-0361-y` (it is the same journal article by Springer and references are already in CrossRef)

**Comment by kleinann** [comment]
Oh, I forgot: The article isn't opened in a separate window.

**Comment by kleinann** [comment]
I now tried 2 existing ppns ( 1994632429 and 1994632410), they don't upload.

**Comment by anlausch** [comment]
Currently, only Crossref with the DOI is queried. I understood from the description of the workflow that only one source needs to be queried. I assume this to wrong now. Support for OLC will then follow.

The references should be loaded correctly by the backend @lgalke . I just tried it via Swagger and the DOI `10.1007/s11135-016-0361-y` (same as kleinann) .

The pages are not parsed correctly. Thanks for pointing that out. This will be also addressed.

- [ ] query olc
- [ ] extract pages correctly

**Comment by lgalke** [comment]
@anlausch I am getting just { "_id": "No scan available." } as `ToDoScans` item of a journals `parts`

**Comment by anlausch** [comment]
@lgalke you requested explicitly a dummy scan because you did not want to change your parser. Which id should I assign if there is no scan?

**Comment by anlausch** [comment]
@zuphilip I have problems accessing the database of OLC. Do you know which measures I have to take now? 

http://sru.gbv.de/olc?query=pica.ppn+%3D+%221994632569%22

Returns:

<zs:searchRetrieveResponse xmlns:zs="http://docs.oasis-open.org/ns/search-ws/sruResponse">
<zs:echoedSearchRetrieveRequest>
<zs:version>2.0</zs:version>
<zs:query>pica.ppn = "1994632569"</zs:query>
<zs:recordXMLEscaping>xml</zs:recordXMLEscaping>
</zs:echoedSearchRetrieveRequest>
<zs:diagnostics xmlns:diag="http://docs.oasis-open.org/ns/search-ws/diagnostic">
<diag:diagnostic>
<diag:uri>info:srw/diagnostic/1/236</diag:uri>
<diag:message>Access to specified database denied</diag:message>
</diag:diagnostic>
</zs:diagnostics>
</zs:searchRetrieveResponse>

**Comment by zuphilip** [comment]
For OLC database the request has to come from an IP from university, i.e. VPN or backend server. I can then open the database entry https://gso.gbv.de/DB=2.152/PPNSET?PPN=1994632569 . I see also access denied on the SRU URL you provided, but the following works for me http://sru.gbv.de/olcssg-soz?query=pica.ppn+%3D+%221994632569%22&maximumRecords=10 . Maybe we can start with OLCSSG-SOZ, also it would be preferable to look in all OLC-DB http://uri.gbv.de/database/olcssg , but maybe we can discuss that with the GBV further after the workshop.

**Comment by anlausch** [comment]
Thank you very much for helping here. I will start with querying olcssg-soz.

**Comment by lgalke** [comment]
@anlausch The idea was to have the dummy scan carry the `_id` i need to pass to `/getToDoBibliographicEntries/${_id}` to retrieve the corresponding entries. However, since in this case the front-end actually needs to call `/bibliographicResources/${_id}` instead, and proceed with the `parts` of the results, the dummy scan is not needed anymore.

Still there is a technical difficulty: how to determine at runtime whether the current item is actually a `ToDoScan` (as before) or a `ToDoParts` (inside `children` of `ToDo` or a *real* `BibliographicResource`).

**Comment by anlausch** [comment]
I will remove the scan. For now, we could go with this: When there is no scan, then it is a TODO Part, otherwise a TODO scan. Later on, we can think about adding a todo type maybe? What do you think @lgalke ?

**Comment by anlausch** [comment]
The OLC query should work now. The service to call is again `/saveElectronicJournal` but we now have an additional parameter, `ppn` . Both are optional but one has to be set in order to retrieve results. If the ppn is given, we search in OLC-SSG-SOZ and try to retrieve data. When a DOI for the article can be retrieved by OLC-SSG-SOZ we try to call Crossref in order to retrieve references. If only the doi parameter is set we go directly to Crossref. https://github.com/locdb/loc-db/commit/9df1d914070b148f38e5486fff28e9de5823fb18

**Comment by lgalke** [comment]
Great, thanks to @anlausch I can now use prevalence of the `parts` property as an indicator. Good short-term solution. Now the electronic resources workflow should work.

**Comment by lgalke** [comment]
The capability of dealing with electronic journals was added. Remaining small bugs are discussed in other isses.
