### ISSUE TITLE
Adjusting thresholds for suggestions

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#108]
Here is an example for adjusting the thresholds for suggestions. I looked at the 4th chapter of the 1st entry and scrolled to the end to `S` in the list of references. The entry `Salmi V and Kivivuori J` is recognized AFAIKS perfectly from the OCR. The suggestions look like this:

![suggestions](https://user-images.githubusercontent.com/5199995/32167230-9ebe24d8-bd68-11e7-81ab-ddd1c71f014d.jpg)

The internal suggestions are all crap and not one of them should been shown. The first external suggestion (GoogleScholar) is a perfect match and is correct. The second suggestion (ISSN) matches pefectly the subtitle and is correct as well. Why is the main title not shown/found for the second one? The third match has `The role` and `social capital` in common and could maybe still okay to suggest. Everything else should possibly not be shown at all.

From where does the suggestions with ISSN come from?

This title should be easy to [find exactly in CrossRef](https://search.crossref.org/?q=The+association+between+social+capital+and+juvenile+crime%3A+The+role+of+individual+and+structural+factors.). Why do we have here another match from CrossRef URL?

**Comment by anlausch** [comment]
Regarding the internal suggestions: The service GET /getInternalSuggestionsByQueryString has now another optional query parameter `threshold` which can be set to an elastic search relevance score value, above which suggestions shall be retrieved. https://github.com/locdb/loc-db/commit/0608f186d0f1ce2eb8fc97e0c1ba0d126ac4879d

Example:
GET /internalSuggestionsByQueryString?query="Test 123"&threshold="1.5"

The suggestion threshold is therefore now fully controllable by the front end. @lgalke 
We could even expose the threshold to the user for experiments and testing. 

I also added a default value, which is currently `0.5` but will be changed later on when I have done some more testing. Like this, the frontend can decide to either use the service as before (no changes needed) or to update accordingly.

Elastic relevance score: https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-intro.html

**Comment by anlausch** [comment]
Regarding the uncomplete crossref title: You actually found a bug - thanks for pointing that out. The title property was erroneously overwritten by the subtitle. Should be resolved with https://github.com/locdb/loc-db/commit/a0d3afa684048ea0c3bba173266ba27611c17c88 .

**Comment by anlausch** [comment]
The issue with the missing source indicators (ISSN instead of CROSSREF etc.) is addressed in  https://github.com/locdb/locdb-frend/issues/114.

**Comment by anlausch** [comment]
Regarding the external suggestions relevance issue, a similar solution as for the internal suggestions was implemented. The service GET /getExternalSuggestionsByQueryString has now the additional optional parameter threshold, which corresponds to the string similarity (Dice Coefficient) between the query string, the title and the subtitle (all only if available) threshold.The default is currently set to 0.45 and may be changed easily according to your needs. Again, there are no changes in the front end necessary @lgalke, because the parameter is optional, but exposing the threshold could be beneficial. https://github.com/locdb/loc-db/commit/d1bd98348e6d034b4720fffce5a98177e85d9213

**Comment by lgalke** [comment]
threshold is exposed. Still it is not optimal to rerun (especially external) queries. At some point it would be preferable to just pass the confidence scores to the front-end.

**Comment by zuphilip** [comment]
Okay, thank you! External suggestions match quite well now already, but internal suggestions look still strange most of the time. We just need some values for the workshop will look reasonable, when humans look at the suggestions :-)
