### ISSUE TITLE
Restart Server

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#111]
@lgalke Can we restart the server now? There are some I/O errors...

**Comment by lgalke** [comment]
Yes

**Comment by zuphilip** [comment]
Okay, we will do this now...

**Comment by zuphilip** [comment]
Machine is restarted and it looks that everything works as before, right?

**Comment by zuphilip** [comment]
Uhm.. I have some problems to log in again. Can you log in w/o problems?

**Comment by zuphilip** [comment]
Okay, I can now login again but there are some 503 errors for loading the todo management. Is the backend running as it should?

**Comment by zuphilip** [comment]
Okay, my fault. Now it seems to work as before...
