### ISSUE TITLE
Search for suggestions: Ignore small typos?

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#113]
Example: "Behavioral study of obedence" (instead of "obedience") --> no valid suggestion
![grafik](https://user-images.githubusercontent.com/33151732/32176643-8e3e5cca-bd88-11e7-9971-54d25814e6eb.png)

But: Data for the article is available from Crossref
![milgram-behavioral-crossref](https://user-images.githubusercontent.com/33151732/32178703-b47dd2da-bd8d-11e7-9201-5666ad4474fd.jpg)

**Comment by kleinann** [comment]
Maybe the problem is not the typo - I just corrected it, but the right result still didn't appear. Is there someting wrong with the Crossref query itself?

**Comment by lgalke** [comment]
Is the correct result appearing somewhere at a lower position, when you press `Show all`?

**Comment by LauraErhard** [comment]
I searched with the same query and the correct result appears, but not from Crossref.
![screenshot-2017-10-30 loc-db frontend 2](https://user-images.githubusercontent.com/32642653/32180004-166431f8-bd91-11e7-92df-85e08e8d2a77.png)

**Comment by kleinann** [comment]
Ok - maybe I just didn't wait long enough and the external suggestions hadn't been refreshed yet after the new search.
Then there's the typo issue still - but that would probably be an enhancement.

**Comment by LauraErhard** [comment]
I just checked your screenshot and I noticed that you were not logged in (sign in option available on top right). Maybe the suggestions didn't refresh because of that?

**Comment by lgalke** [comment]
2a66d3286306962b4c4fc871c65b8d6f17b4db6b since now you have full control over the string that is used for querying the databases (up to now, only the title was editable in the search field, but there was more used for the actual query). Please give it a try again 💯 maybe the results are now more predictable.

**Comment by anlausch** [comment]
Improvement on this was also provided together with https://github.com/locdb/locdb-frend/issues/108 .

**Comment by anlausch** [comment]
I will close the issue now. Feel free to open it again.
