### ISSUE TITLE
External Suggestions: show source / filter by source

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#114]
At the moment, the external suggestions are marked as "url_crossref" and "issn". It would be more interesting to see the real source of the data, and possibly be able to filter the suggestions by data source.

If there is a monograph in the reference list, the chance is very high that it can be found in a union catalogue (SWB etc.) - and this would also be the data with the highest quality. We'd always want to make the link to this record if it's available, so it should be possible to see which suggestion comes from a union catalogue.
Even better: Make it possible to choose a preferred source for suggestions in the frontend and then rank the suggestions accordingly.

**Comment by anlausch** [comment]
For the workshop, we could start with showing the sources. There should be already an enum in the suggestion provided by the backend indicating where the suggestion comes from. Filtering can already be done in the frontend too. For enhancing the performance later on, we can also provide an http request parameter indicating which source should be queried.

**Comment by lgalke** [comment]
Development depends on #123

**Comment by lgalke** [comment]
Provenance is now displayed 9e7d365. Filtering will not most likely *not* be possible until the workshop.

**Comment by lgalke** [comment]
For filtering and so on we will wait for concrete provenance implementation in our data model. This way we avoid double-work. Currenty the provenance comes from a heuristic based on the identifiers.

**Comment by anlausch** [comment]
The provenance of a suggestion is now explicitely available in a specific property `source`.

**Comment by lgalke** [comment]
- [ ] display the new `source` property
- [ ] implement filtering (still considered long-term)

**Comment by lgalke** [comment]
We decided to start with filtering on the following attributes:

- [ ] Source
- [ ] Resource Type
- [ ] Standalone vs Contained (has `partOf`)

**Comment by lgalke** [comment]
@chah3d has made some progress here. However, we need to keep in mind that the precalculated suggestions only return 10 initially. So, the feature will only really shine, when a manual search is triggered with more suggestions. Just to keep in mind.

**Comment by lgalke** [comment]
Filtering suggestions is now deployed. Thanks to @chah3d

**Comment by LauraErhard** [comment]
I just now checked this new feature out. And I have a question. What does the "contained" filter? It seems that the `contained `filter only shows external suggestions and `standalone `only shows internal suggestions. Am I right with this assumption? And if so, why is it called "contained" and "standalone"?
![filter](https://user-images.githubusercontent.com/32642653/44994020-ff6ea380-af9c-11e8-9b8b-2b618cad3337.png)

Or is it something completely different?

**Comment by LauraErhard** [comment]
@lgalke I think you don't get a notification if the issue is closed. Please check out my feedback to the suggestion filter.
