### ISSUE TITLE
Internal/external suggestions

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#115]
1. If I want to `commit link` an external suggestion and a box on the left, I always have to do it twice. First I have to click `commit link`, then this external suggestion becomes an internal suggestion. After that I have to click `commit link` again (now with the internal suggestion and the box) to lock the left side to the right side (the box on the left side gets a green frame). Is there an easier way to do it?
2. Is there a possibility to show that the search for the external suggestions is still in progress? = issue #116 
3. The changes I make to the internal suggestions are not saved. When I `submit` my changes in the edit function, I see the changes on the right side. But if I go back to the todo page and then go back to the file, I see that all my changes are gone. What is going on there?

**Comment by lgalke** [comment]
1. Actually one click on `commit` is enough to link the reference to the resource.
```js

Push BR {identifiers: Array(2), title: "VII. Zum Stand der neueren Forschung", subtitle: "", contributors: Array(1), status: "VALID"}

locdb.service.ts:53 Response Response {_body: "{"__v":0,"title":"VII. Zum Stand der neueren Forsc…URL_CROSSREF","_id":"59f7bda531e9903d3cd6277e"}]}", status: 200, ok: true, statusText: "OK", headers: Headers, …}

suggestion.component.ts:192 Submitted Entry pointing to former external BR {__v: 0, title: "VII. Zum Stand der neueren Forschung", subtitle: "", status: "VALID", _id: "59f7bda531e9903d3cd6277c", …}
```
2. #116 is resolved.
3. Is covered by #120
