### ISSUE TITLE
Suggestions not working

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#123]
Internal as well as external suggestions are not responding due to CORS headers (502). Did you change anything? It only affects the local development environment and not the deployed one, but still it slows down the cycles. @anlausch 

```js
Failed to load https://locdb.bib.uni-mannheim.de/locdb-dev/getExternalSuggestionsByQueryString?query=Just%20sustainabilitles:%20Development%20in%20an%20unequal%20world.%20J%20Agyeman%20Agyeman,%20J.,%20Robert,%20D.%20B.,%20%26%20Evans,%20B.%20(Eds.).%20(2003).%20Just%20sustainabilitles:%20Development%20in%20an%20unequal%20world.%20London:%20Earthscan.:
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 503.
```

**Comment by anlausch** [comment]
Both requests return the header as discussed.

Internal:
![image](https://user-images.githubusercontent.com/20592651/32264425-ebbd1290-bede-11e7-91b4-fdf05cc60536.png)
External:
![image](https://user-images.githubusercontent.com/20592651/32264464-11bacbae-bedf-11e7-9536-d16947a4ba76.png)

**Comment by lgalke** [comment]
nvm, I needed to explicitly URL-encode the query parameter... 4aa7d33
