### ISSUE TITLE
Deleting Single Scans

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#124]
We need a REST endpoint to delete single scans. We cannot rely on deleting the resource as a whole since it might lead to inconsistent states.

**Comment by anlausch** [comment]
It does not cause inconsistency, but it might not be desired to delete a whole bibliographic resource. Later on, this service will follow.

**Comment by anlausch** [comment]
A new service was implemented DELETE /scans/<id>.  Please test whether it fits the needs.

**Comment by lgalke** [comment]
Front-end button is connected and working. 👍 @anlausch
