### ISSUE TITLE
Adapt todo details to work with list of entries if todo not given

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#125]
Adapt todo details to work with list of entries if todo not given.
necessary for #104

**Comment by lgalke** [comment]
The `children` of a resource do not have `parts`, thus I cannot its `BibliographicEntry` list.

**Comment by lgalke** [comment]
@anlausch

**Comment by anlausch** [comment]
The children of a resource are bibliographic resources themselves, e.g., an article of a journal. The identifiers of children therefore refer to bibliographic resources, which can be queried via GET /bibliographicResource/<id> .. this returns the full resource including the entries if available.

**Comment by anlausch** [comment]
For your convenience and for reducing traffic, I added the parts now to the external todos. @lgalke

**Comment by lgalke** [comment]
Thanks @anlausch .
