### ISSUE TITLE
External Suggestions sensitive to blank spaces

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#126]
# Steps to reproduce

1. Select an arbitrary entry
2. Delete the `Query` field and enter `Development`
3. After some time, assert that at least 2 suggestions appear.
4. Now instead enter `Development ` (note the blank space)
5. After some time, the loading indicator disappears, but **no** suggestions appear.

You can also verify, that the list was indeed empty by checking the console.

# Possible problem

The front-end calls `encodeURI(queryString)` before passing it to `GET /externalSuggestionsByQueryString?=`. This effectively replaces blank spaces and other invalid symbols with `%20` something. It might need to get decoded by the back-end afterwards.

**Comment by anlausch** [comment]
Thanks for pointing that out. I will check how to deal with this problem.

**Comment by anlausch** [comment]
Solved with https://github.com/locdb/loc-db/commit/8540dc26cc89838a2c25761c5c288b7e15e3c7d8
