### ISSUE TITLE
Creating empty new BR is not possible

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#128]
# Problem

Push BR Object 
```js
{ title: undefined, publicationYear: undefined, contributors: Array[0], embodiedAs: Array[0], parts: Array[0], partOf: undefined, number: undefined }
```

```html
400 - Bad Request The br already exists (entry with exactly the same fields is in the database, use put endpoint).
```

# Steps

1. select an entry where no other data than the Raw Text is given (e.g. coming from CrossRef)
2. Press the plus button

# Potential fixes

How do we deal with this case.

- [ ] Should I keep the data locally until it is submitted?
- [x] As a quick-fix alternative, I could copy all the raw text into the title field...

**Comment by anlausch** [comment]
I think the best would be to wait until the user submits?

**Comment by lgalke** [comment]
Indeed, it is just not that clean to add the resource temporarily to the internalSuggestions list.. we might want to display it differently. We could

- [ ] add it to external List since its treatment would be the same: 1. push 2. commit link
- [ ] make a novel view independent of either suggestions

**Comment by lgalke** [comment]
For the workshop, it will be fine to have it in the external list, since the treatment is the same.
I will add a Provenance: "New" to distinguish it from the others.

**Comment by lgalke** [comment]
Okay, I made a new view for it, pushing it into the external resources is not helpful, since they can be overwritten as soon as the real external suggestions appear. Yet the treatment is now the same as for externals which means "Only push the resource when the commit is invoked"
