### ISSUE TITLE
No external suggestions from SWB?

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#129]
In the bibliography of "Rethinking business schools" (ppn 44461205X), the third entry is "Academically Adrift etc." There is a record for this in SWB (ppn 33608000X), but this isn't found neither by the automatic query which probably has to many parameters nor by a shortened search for "Academically Adrift: Limited Learning on College Campuses" or just "Academically Adrift".
Strangely, "Academically Adrift: Limited Learning on College Campuses" found a match on Crossref, but "Academically Adrift" didn't.

**Comment by lgalke** [comment]
There might be a bug with the encoding, when the query string gets passed to the backend, related to: #126

**Comment by anlausch** [comment]
#126 is resolved. I checked and SWB suggestions are retrieved. Feel free to reopen the issue when the problem persists.
