### ISSUE TITLE
Search for external suggestions takes too long

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#130]
The search for external suggestions takes so long that it's not realistic to go through a whole list of references.

Example:
"Academically Adrift: Limited Learning on College Campuses, R Arum Arum, R. and Roksa, J. (2010), Academically Adrift: Limited Learning on College Campuses, University of Chicago Press, Chicago, IIL, USA."
This is what is automatically extracted from the pdf file - it seems too much to me anyway; title and author should typically be enough to find a resource.
I counted 35 seconds before the search stopped with no results.
"Academically Adrift: Limited Learning on College Campuses"
58 seconds, 1 (correct) result from Crossref
"Academically Adrift"
52 seconds, no results.

**Comment by anlausch** [comment]
If you retrieve no results at all, make sure to adjust the threshold. If the problem persists, then it's maybe a time out in the frontend? @lgalke  
Regarding the overall time: The bottleneck is questing the external sources. Currently, SWB  and GoogleScholar are making problems. Google Scholar might be blocking us, but SWB is taking also very long from time to time, also when accessing via the browser (I just half an hour ago noticed it when making tests). This is something that I probably cannot resolve completely until the workshop. One could think of providing different services for each source, then the front end could retrieve the results depending on how long it takes for each source and show already the results that are there. Then the threshold adjusting would have to be done completely in the front end. 
Of course, the best would be to make it faster anyway and in total.. one step could be already caching former results,  but then we probably also need to cache lots of crap. This approach I would not prefer. On the other hand, one could think of more advanced scraping techniques. But this needs to be investigated further and needs some time. Any experiences with that anyone?

**Comment by zuphilip** [comment]
Personally, I think it might be good idea to calculate some of these queries beforehand, but maybe only save very good matches, which can be shown instantaneously. But this is IMO something to discuss after the workshop. 

For now: Can we deactivate GoogleScholar? It is quite easy to get blocked by them... Maybe this helps a little and CrossRef search should be also quite powerful.

**Comment by lgalke** [comment]
+1 for deactivating google scholar 🔌 esp. if it is unreliable (in terms of blocking us)

>If you retrieve no results at all, make sure to adjust the threshold. If the problem persists, then it's maybe a time out in the frontend? @lgalke

I extensively tried it and it never ran into timeout. There is always something returned, either some suggestions or an empty list.

Regarding the time issue: pre-populate LOC-DB internal data with SWB as a starting point? Probably not doable anymore now. Thus, pre-populate internal resources for the cherry-picked examples. Afterwards manually remove the `references` field of the entry on the left-hand-side for demonstration purposes.

**Comment by anlausch** [comment]
Ok, for the workshop, I will deactivate Google Scholar and afterwards work on a long-term solution. 

"Thus, pre-populate internal resources for the cherry-picked examples. Afterwards manually remove the references field of the entry on the left-hand-side for demonstration purposes." If I understand this correctly, this solution would not require additional implementation. I think we can do this.

**Comment by lgalke** [comment]
- [ ] deactivate GoogleScholar

**Comment by anlausch** [comment]
Update: Google Scholar is deactivated and I have the impression that this measure already helps. @zuphilip was pinged regarding the optimization of the SRU query.

**Comment by lgalke** [comment]
Closed for now, without GoogleScholar the performance did improve already.
