### ISSUE TITLE
Avoid empty boxes + delete undefined from query string

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#133]
I entered an electronic journal article by DOI where also the references are available at CrossRef. But for a lot of entries no title is extracted by CrossRef and therefore this boxes seem to be empty. I suggest to take simply the whole text string, if there is no information about the title. Moreover, the query should not contain the word `undefined`:

![locdb-no-title](https://user-images.githubusercontent.com/5199995/32291596-d0bd577a-bf3d-11e7-9c51-0d05254791b8.jpg)

**Comment by lgalke** [comment]
Yea, the `undefined` value is indeed a bug.

**Comment by lgalke** [comment]
For the empty boxes, I already introduced a hotfix that if ocrdata.title is not available, the raw string is used. Will deploy in a minute, including also the other fix.

**Comment by lgalke** [comment]
Regarding the other part of the issue, I presume Anne does not get structured data from CrossRef but unstructured. Plus, the potential conversion of unstructured text to structured data is performed by DFKI. And finally, for now DFKI never gets to see CrossRef results for electronic journals 🔢 

It would be a good idea to have exactly this process `unstructured` :arrow_right: `structured` as a stand-alone service, but it is not at all realistic to have it incorporated before the workshop.

Hopefully, its enough for now if there are no empty-boxes and undefined values 🥇

**Comment by zuphilip** [comment]
That sounds exactly what I was looking for! Thank you 🙇 !

Let me know when it is deployed.

**Comment by lgalke** [comment]
It is now deployed :)

**Comment by zuphilip** [comment]
Nice! It works. Thank you!
