### ISSUE TITLE
Collect examples for workshop

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#136]
For `Rethinking business schools MONOGRAPH`, everything works like a charm. There is not even the need to wait for external suggestions. The extraction was so good that you just have to press `+` and `commit`, for each entry.

- `Rethinking business schools MONOGRAPH`

**Comment by anlausch** [comment]
+1 good idea

**Comment by lgalke** [comment]
Scans should have at least: 300 dpi. Better 600
