### ISSUE TITLE
Container item vanishes after title of article is entered

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#145]
![2017-11-02_07-47-12](https://user-images.githubusercontent.com/5199995/32313255-3e980ac4-bfa2-11e7-9378-d234e0fc0750.gif)

**Comment by lgalke** [comment]
Good find, I will make sure that all not modifieable values are retained.

**Comment by lgalke** [comment]
the `partOf` property was causing this problem, it is now copied without modification from the unchanged resource. 43e5afc should fix it.

**Comment by lgalke** [comment]
My manual tests succeeded, if there are any objections please reopen.

**Comment by lgalke** [comment]
Add `container-title` field (maybe until workshop) as a *free* string field.
