### ISSUE TITLE
textual PDf field

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#148]
Add another input to file input. 

- [x] Process as Image *default*
- [x] Process as Text

**Comment by anlausch** [comment]
The services /saveScan and /saveScanForElectronicJournal have now an additional boolean parameter "textualPdf". According to this and the documentation of the OCR component, the configuration for the request is set. Now, we can be 100% sure, that we always pass the optimal configuration to the ocr processing.

**Comment by lgalke** [comment]
108e30da7d57feec93a2ab2961ee7ecab7ea7512
