### ISSUE TITLE
External: Make DOI in metadata of citing work clickable

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#150]
Sometimes it would be helpful to see the original article while working with the external references. Could you make the DOI in the metadata of the citing article clickable?
![grafik](https://user-images.githubusercontent.com/33151732/32372861-f012ea72-c096-11e7-8b2e-14c87158ebbe.png)
Only if it's not too complicated...

**Comment by lgalke** [comment]
Should be possible

**Comment by lgalke** [comment]
76f5294
