### ISSUE TITLE
Crossref references only with DOI

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#151]
Crossref sometimes gives reference lists which only contain very basic data. Example:
![grafik](https://user-images.githubusercontent.com/33151732/32373503-d8fe3fc8-c099-11e7-9e10-cb6d16e80dcd.png)

This results in a partly empty reference list in LOC-DB:
![grafik](https://user-images.githubusercontent.com/33151732/32373533-f7b737b2-c099-11e7-947c-64871691b735.png)

Could you show the DOI from the Crossref reference list in the LOC-DB list of entries, if there is any?

**Comment by zuphilip** [comment]
Moreover, take the DOI into the query for such cases.

**Comment by lgalke** [comment]
Identifiers are currently not at all considered in the **Bib. Entry ** data structure.

**Comment by kleinann** [comment]
Ok, that explains it. We should think about that after the workshop, then. Of course it would make sense to use the DOI for the suggestions search and also keep in in our data.

**Comment by anlausch** [comment]
@lgalke 

> Identifiers are currently not at all considered in the Bib. Entry data structure.

 Do you mean in the front end?
Because the back end has it, exactly like for every other db type. The Doi is extracted when available and can be retrieved.

[

```
"parts": [
          {
            "bibliographicEntryText": "Anscombe G.E.M.: On the frustration of the majority by fulfillment of the majority's will. Analysis 36,161–168 (1976)",
            "status": "VALID",
            "_id": "59f89542cddeb54b39191275",
            "references": "59fb18beeb79496a14bfb44a",
            "ocrData": {
              "date": "1976",
              "authors": []
            },
            "identifiers": [
              {
                "literalValue": "10.1093/analys/36.4.161",
                "scheme": "DOI",
                "_id": "59f89542cddeb54b39191276"
              }
            ]
          },
```

**Comment by lgalke** [comment]
Good to know 👍 only checked the front-end model, I can then adapt.

**Comment by lgalke** [comment]
d0a3ac2 identifiers are now displayed for entries
