### ISSUE TITLE
Deactivate logging for workshop

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#152]
It is very frequently that somehow one gets logged out. This is painful. 😠  Can we deactivate the logging for the workshop?

**Comment by lgalke** [comment]
Default Session timeout should be 20minutes. Is it even Note frequent for you?

**Comment by zuphilip** [comment]
My experience is that sometimes I work in the system and then it just not work anymore, before I see that I somehow got logged out. My colleagues also mentioned that in some steps (e.g. go through list of references) it is more easy to get logged out.

I see that we also had several issues here before and therefore suggest, that maybe the simplest would be to temporarily deactivate it completely. This will reduce the possible errors by at least one cause...

**Comment by anlausch** [comment]
We can do that. But the problem is that the server is then not secured.

**Comment by anlausch** [comment]
I noticed that most of the time when the back end fails (that is one of the possible causes of getting logged out) accessing index of elastic search is the proplem. I made this part now more secure. Maybe that already helps (please continue testing).
