### ISSUE TITLE
Frontend shows wrong external suggestions results for a while, when multiple requests are sent 

### ISSUE THREAD

**Issue by anlausch** [locdb/locdb-frend#153]
Now, that the external suggestions are faster (deactivating google scholar apparently helped), You can really see in the frontend how the results are retrieved when triggering multiple requests one after the other, because the front end displays the results of the old requests one after the other when they arrive.

Steps to reproduce: Select a resource with references extracted (EXTERNAL or OCR_PROCESSED) --> click quickly on the first, second, third, fourth reference --> check on the right-hand side of the screen what's happening with the external suggestions.

**Comment by lgalke** [comment]
Great, the external requests are popping in really fast, now.

**Comment by lgalke** [comment]
ce830c9 both internal and external suggestions async responses are now validated and will only update the view if the entry is the same as when the request was started.
