### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by anlausch** [locdb/locdb-frend#162]
In the workshop a participant noticed that there were some encoding problems with the german "Umlaute". We need to check on this.

**Comment by lgalke** [comment]
As long as the data is in our control, everything works as expected.

``` js
Sending resource updates to backend! Object { ..., title: "Ärzte", type: "" ,… }
```

``` js
Yay. submitted Object { ..., title: "Ärzte", type: "", … }
```

Therefore, I presume that the error might be caused by CrossRef or SWB conversion?

**Comment by rtahseen** [comment]
You can try by setting encoding of the html pages to "UTF-8" or "ISO 8859-2". Hopefully, it will automatically encode all the data displayed on that page to the specified encoding and hopefully it will be displayed correctly.

**Comment by lgalke** [comment]
It is already.

``` html
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8">
      <!-- other html headers -->
    </head>
    <body>
      <app-root>Loading...</app-root>
    </body>
    </html>
```

Also in principle, Umlaute can indeed be displayed.

**Comment by anlausch** [comment]
I will check what we get back in such cases from Crossref and SWB.

**Comment by anlausch** [comment]
Update on this: 
With Crossref and DOI, everything works fine. I cannot see any problems. And the references are always coming from Crossref if loaded externally. Therefore, I am not sure where the problems come from. 
Can someone provide reproducible examples of this issue? Whenever you encounter encoding issues after uploading or saving a resource, just let me know what you did. Thanks.
@LauraErhard @lgalke @SylviaZander @kleinann @zuphilip

**Comment by lgalke** [comment]
Closed for now. Might be reopened in case we find another malfunctioning example.
