### ISSUE TITLE
Reduce clicks in order to improve usability

### ISSUE THREAD

**Issue by anlausch** [locdb/locdb-frend#164]
People in the workshop mentioned that we should reduce unnecessary clicks, e.g. auto-trigger ocr procressing of uploaded scans.

**Comment by lgalke** [comment]
So I started with auto-triggering the OCR processing of uploaded scans. To implement it in the front-end, however, the back-end needs to return the `ToDoScans` object which was created. Most importantly, I need its `_id` to continue with triggering the OCR processing. Currently it seems like the full bibliographic resource is returned, to which it got attached. In this latter case I can not decide which of the `scans` is the one that was newly created.

**Comment by anlausch** [comment]
+1 I will probably implement it together with the other changes of the ToDo List.

**Comment by anlausch** [comment]
I have been thinking about this and I am wondering what's the best way to implement this. Would the frontend really be ok with only returning the Scan instead of the whole BR? Let's talk about this later this day.

**Comment by lgalke** [comment]
@anlausch Why not return both? 
```json
{"resource": <resource-object>, "entry": <entry-object>}
```

Auto-triggering OCR Processing and the Crossref Check #178 in the front-end requires the concrete `_id` of the just-added scan.

**Comment by anlausch** [comment]
In the newest version of the backend, the scan is returned in the answer array together with the resources that were created/modified/matched. It is always the last array element.
https://github.com/locdb/loc-db/commit/3c0ee8e1ed45ee4b43153cf1a39a2678f7863b71
This version will be deployed today afternoon.

**Comment by lgalke** [comment]
How exactly is the format of the answer array? Or you mean the `parts` array inside the resource. Swagger seems to be not yet updated. @anlausch

**Comment by lgalke** [comment]
Autotriggering is now enabled. However, for nested resources I receive `[container, resource, null]`.

**Comment by anlausch** [comment]
should be ok now
