### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by anlausch** [locdb/locdb-frend#165]
A participant had the idea to use keyboard shortcuts in order to make the workflow faster.

**Comment by lgalke** [comment]
ca75fa4 you can now use `j` to move one entry downward and `k` to move one entry upward, both in the entry-list and the scan view.

**Comment by lgalke** [comment]
As of d9245c0, the cheat-sheet (by pressing `?`) is also correctly displayed.

**Comment by lgalke** [comment]
The hotkey init in the scan view was a little misplaced, fixed by 8633d55

**Comment by LauraErhard** [comment]
I tested the shortcuts and they work fine. Just one quick question, does the `j` and `k` have a deeper meaning? I am right handed (mouse in the right hand for clicking) and it is awkward for me to move my left hand to the `j` and `k` keys. I think it would be more intuitive to put the shortcuts on `f` and `d` or something like that? But please discuss this, maybe I'm the only one with this issue

**Comment by LauraErhard** [comment]
It would also be nice to have a shortcut for jumping to the top and to the end of the page. Our ToDo Management is rather long at the moment and it is really frustrating to scroll up and down. At the moment I use the `refresh` button to go to the top, but I have no way to jump to the end of the page (new OCR processed files are at the end of the todo list).

**Comment by lgalke** [comment]
>I tested the shortcuts and they work fine. Just one quick question, does the j and k have a deeper >meaning? I am right handed (mouse in the right hand for clicking) and it is awkward for me to move >my left hand to the j and k keys. I think it would be more intuitive to put the shortcuts on f and d or >something like that? But please discuss this, maybe I'm the only one with this issue

In unix systems, `j` and `k` are quite established hotkeys for moving the cursor down and up, respectively.
In particular, the chosen keys are inspired by *the* text editor [vim](http://www.vim.org/), in which the cursor is moved by `hjkl`. I could of course add another set at any time.

**Comment by lgalke** [comment]
> It would also be nice to have a shortcut for jumping to the top and to the end of the page. Our ToDo Management is rather long at the moment and it is really frustrating to scroll up and down. At the moment I use the refresh button to go to the top, but I have no way to jump to the end of the page (new OCR processed files are at the end of the todo list).

I totally agree that when the ToDo items grow, the manual scrolling to find the correct one is unconfortable. There is need for improvement or even an alternative. Adding hotkeys to the `todo-list` view is a little tricky because there is currently no notion of a *selection*.

**Comment by lgalke** [comment]
Will close for now because this issue is not the main focus right now. Can be reconsidered, when we are at a UI polishing phase.
