### ISSUE TITLE
OCR can't handle large files?

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#170]
I just uploaded a few large pdf files (8,5 MB to 17,7 MB, 10-19 pages per file) and after clicking the OCR processing button they disappeared as usual but after a while they reappeared in the OCR unprocessed part. I uploaded a file with 10 pages and less MB and this worked fine. Has the OCR a problem with large files? Is there a limit of pages or MB that the OCR can handle? Or is there a different problem?

PPN:
357156412 
347675387 
265957915
352226064

**Comment by lgalke** [comment]
Good point, we need to make sure that there is no timeout at some point. Since uploading succeeded, the storage on the back-end should work. Yet there might be a problem considering the trigger between back-end and OCR component. Does the console log any errors (after triggering and then waiting a reasonable time)?

**Comment by anlausch** [comment]
Could you send us an example file that does not work?

**Comment by LauraErhard** [comment]
I just send you two files.

**Comment by LauraErhard** [comment]
@lgalke I got this error after like 3 minutes of waiting:
`SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Stack-Trace:
../../../http/@angular/http.es5.js/Body.prototype.json@https://locdb.bib.uni-mannheim.de/extrapolate-dev/vendor.bundle.js:102367:20
../../../../../src/app/locdb.service.ts/LocdbService.prototype.handleError@https://locdb.bib.uni-mannheim.de/extrapolate-dev/main.bundle.js:1100:24
../../../../rxjs/operator/catch.js/CatchSubscriber.prototype.error@https://locdb.bib.uni-mannheim.de/extrapolate-dev/vendor.bundle.js:36019:26
../../../../rxjs/Subscriber.js/Subscriber.prototype._error@https://locdb.bib.uni-mannheim.de/extrapolate-dev/vendor.bundle.js:29056:9
../../../../rxjs/Subscriber.js/Subscriber.prototype.error@https://locdb.bib.uni-mannheim.de/extrapolate-dev/vendor.bundle.js:29030:13
onLoad@https://locdb.bib.uni-mannheim.de/extrapolate-dev/vendor.bundle.js:102801:17
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@https://locdb.bib.uni-mannheim.de/extrapolate-dev/polyfills.bundle.js:2964:17
onInvokeTask@https://locdb.bib.uni-mannheim.de/extrapolate-dev/vendor.bundle.js:84395:24
../../../../zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@https://locdb.bib.uni-mannheim.de/extrapolate-dev/polyfills.bundle.js:2963:17
../../../../zone.js/dist/zone.js/</</Zone.prototype.runTask@https://locdb.bib.uni-mannheim.de/extrapolate-dev/polyfills.bundle.js:2731:28
../../../../zone.js/dist/zone.js/</</ZoneTask.invokeTask@https://locdb.bib.uni-mannheim.de/extrapolate-dev/polyfills.bundle.js:3038:24
invokeTask@https://locdb.bib.uni-mannheim.de/extrapolate-dev/polyfills.bundle.js:4079:9
globalZoneAwareCallback@https://locdb.bib.uni-mannheim.de/extrapolate-dev/polyfills.bundle.js:4105:17`

**Comment by anlausch** [comment]
Thanks for sending the files. I checked it again directly with the UI of the OCR component itself and I get the following error after 9 minutes:

![image](https://user-images.githubusercontent.com/20592651/32668089-e93931ba-c63c-11e7-9b42-539fe98e8297.png)
![image](https://user-images.githubusercontent.com/20592651/32668156-198be27c-c63d-11e7-861b-5f7249e98e28.png)

**Comment by zuphilip** [comment]
CC @rtahseen

**Comment by rtahseen** [comment]
I tried with the files which @LauraErhard sent through email and found out that the files are huge. Right now the OCR component is converting each page to an image and stacking up all pages on each other to create one large image. In the given case, the file had 12 pages (in other words 12 files) and the image generated had dimensions of 2479x42088 which contains over one hundred million pixels data. Thus occupying a lot of resource. In result, the server's security feature considers it a decompression bomb and disrupts its execution.
I would suggest to use multiple files with fewer number of pages. If possible just one page per file.

**Comment by zuphilip** [comment]
It is not efficient for the user to split the files into pages. Especially renaming different files is time-consuming. I think we have around 20 pages on average for a reference list of a monograph and therefore we even may have larger files then this example.

**Comment by lgalke** [comment]
Now the OCR component performs splitting. Is the issue thereby resolved?

**Comment by LauraErhard** [comment]
Last time I checked, the OCR couldn't handle any files. See also #344.
I just tried uploading a new pdf, but the service seems to be not available right now:

Send Scans failed: Object { identifier: {…}, firstpage: null, lastpage: null, file: File, _resourceType: "MONOGRAPH", uploading: false, textualPdf: false, embodimentType: "PRINT", err: {…} }
 
Object { headers: {…}, status: 503, statusText: "Service Unavailable", url: "https://locdb.bib.uni-mannheim.de/locdb-dev/saveResource", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://locdb.bib.uni-mannheim.de/locdb-dev/saveResource: 503 Service Unavailable", error: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n<hr>\n<address>Apache/2.4.25 (Debian) Server at locdb.bib.uni-mannheim.de Port 443</address>\n</body></html>\n" }

**Comment by lgalke** [comment]
Unfortunately, basically nothing is working at the moment because the back-end is down #346 . Hope Anne will be back next week, since I cannot re-start the backend. :cry:

**Comment by lgalke** [comment]
Any updates on this? Does it work now properly?

**Comment by LauraErhard** [comment]
I checked earlier with a 4 MB file (ppn 486614735) and it was bounced back to the waiting part (I think it took nearly an hour to switch to "waiting").

**Comment by rtahseen** [comment]
Since last update of Automatic Reference Extractor, all requests are asynchronously processed. This issue is no more there. You can close the issue after testing it.
