### ISSUE TITLE
`partOf` mandatory?

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#171]
# Steps

1. Pick electronic journal
2. Select Arbitrary Entry
3. Try to add new resource from "ocr data"

# Error

```js
400 - Bad Request {"message":"Validation errors","errors":[{"code":"INVALID_REQUEST_PARAMETER","errors":[{"code":"INVALID_TYPE","params":["string","null"],"message":"Expected type string but found type null","path":["partOf"]}],"in":"body","message":"Invalid parameter (bibliographicResource): Value failed JSON Schema validation","name":"bibliographicResource","path":["paths","/bibliographicResources","post","parameters","0"]}]}
```
partOf seems to be mandatory. Was this intentional @anlausch ? Of course I can put empty string but `null` instead seems reasonable.

**Comment by lgalke** [comment]
In the meantime, I removed `partOf` from being generated as `null` from ocrData and left out the property entirely.

**Comment by anlausch** [comment]
I just wanted to answer that it is not required but that it cannot be null. ;)
