### ISSUE TITLE
Search DOI in query 

### ISSUE THREAD

**Issue by SylviaZander** [locdb/locdb-frend#176]
When there is no title or author in the reference data it would be nice if we could search for the DOI. Otherwise there is no possibility to search for suggestions.

**Comment by lgalke** [comment]
We are currently investigating better (structured) search query possibilities. This might then especially include such structured data as the identifiers.

**Comment by zuphilip** [comment]
For clarification, there are two things here:
1. Use the DOI for the search query
2. Find Crossref metadata by DOI only

To 1: We can discuss how exactly to do this once we fixed the external sources, e.g. Fernleihindex.

To 2: Currently, if I copy the DOI, e.g. 10.1177/1468796807080237, into the query and search for it, then no suggestions are found, also the metadata are in Crossref: http://api.crossref.org/works/10.1177/1468796807080237. Is there a problem on how we search Crossref?

**Comment by zuphilip** [comment]
Continued in #192
