### ISSUE TITLE
References in list of entries

### ISSUE THREAD

**Issue by SylviaZander** [locdb/locdb-frend#177]
if the reference has few data the "header" is missing. Is there a possibility to fill the field with author, year and/or DOI?
![screenshot-2017-11-14 loc-db frontend](https://user-images.githubusercontent.com/32641017/32786033-302048f2-c953-11e7-899a-f785cf3f9f08.png)

**Comment by lgalke** [comment]
The format is now>:

`<authors>: <title> <identifiers> In: <journal + volume> <year>`

If everything fails, raw entry Text as before (which might also be empty).

Please let us know whether this format fits, else feel free to propose another one instead.

**Comment by lgalke** [comment]
5c2563e

**Comment by lgalke** [comment]
There was even another small problem, that caused `:` to appear even if some first author is present but empty. Now fixed 97237e8
