### ISSUE TITLE
Data ingestion, match desired workflow

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#178]
Below is an extracted comment from @kleinann in #134 that deserves top-level attention.

>We have different data sources for different publication types, and there are two different kinds of ppns (SWB-ppn and OLC-ppn). For now, the relevant cases shoud be:

    Type Monograph --> input ppn --> check SWB for metadata
    Type Collection --> input ppn --> check SWB for metadata of the collection itself
    --> input DOI --> check Crossref for metadata of a chapter
    Type Journal --> input ppn --> check OLC for metadata of the article
    --> input DOI --> check Crossref for metadata of the article

> In all these cases, the next steps should be:

    Check Crossref for references to the citing resource. (There is no reference data that can be retrieved by ppn.)
    If there are none, enable the upload of a file.

> I tried ppn 1992062145 / doi 10.1016/j.ssresearch.2016.08.020 and wasn't able to upload anything while using "Add Electronic Resource".

In particular the current behavior does not check crossref references for all resources but just electronic journals. Plus the input type collection does not check CrossRef for metadata of the chapter.

Triggering the `Check for crossRef references` in all cases could be implemented in the front-end (there is a back-end service already) similarly to triggering the OCR processing (after #164 is resolved).

The other thing: checking crossref for chapter metadata. Is it considered or even already implemented @anlausch ?

**Comment by anlausch** [comment]
The last point - checking for chapter meta data for collections - is already implemented. But I agree with you that this needs top-level attention. Related to other issues  #136, #134, I am already working on a redesign of the resource upload.

**Comment by lgalke** [comment]
Please check locdb/loc-db#14

**Comment by lgalke** [comment]
What's the state here, is the crossref reference check now triggered for all ingested resources / or in the upcoming prod version? I am not doing it in the front-end. When it would make more sense to do it in the front-end please let me know @anlausch .

**Comment by lgalke** [comment]
Auto-triggering the crossref check is now implemented also in the new version by @anlausch
