### ISSUE TITLE
First page wrongly propagates to next entries

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#179]
The last example for the electronic journals (dev) is the journal article `Safeguarding Democracy: Powersharing and Democratic Surviva` with doi `10.1017/s0003055417000326`. Clicking on the references from Crossref the first entry has a comment `First page: 159` which is correct (see http://api.crossref.org/works/10.1017/s0003055417000326 ), but the next entries have also that comment, which is wrong.

![first-page](https://user-images.githubusercontent.com/5199995/32879107-f1921b04-caa8-11e7-8ec5-3b5fc601138c.png)

**Comment by anlausch** [comment]
Probably a problem in the back end. I am checking on this.

**Comment by anlausch** [comment]
Is fixed with https://github.com/locdb/loc-db/commit/3c353d47f12010c80782f9361770987a2c8b52c0.
The fix will be deployed later that day. Feel free to open the issue again if the problem persists.

**Comment by zuphilip** [comment]
Yes, that looks better now. Thank you!
