### ISSUE TITLE
Link to GoogleScholar?

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#183]
As an alternative for the suggestions created from GoogleScholar, we could simply add a link to GoogleScholar search, which should open in a new tab. Then the users can click on that link and maybe find the resource in GoogleScholar and follow from there to a publisher's website, where a DOI is written. This found DOI can then used for the linking again. What do you think about adding a link to GoogleScholar search?

**Comment by lgalke** [comment]
Similar to the "Ask Others -> Google Scholar" button on DBLP. Sounds like a good idea.

**Comment by lgalke** [comment]
@zuphilip do you have recommendations on where to put this button? In the "Search Bar" on the right-hand side?

**Comment by lgalke** [comment]
It is now placed on the same level as the usual "Search" button.

**Comment by zuphilip** [comment]
Okay, sounds good. Is this already deployed?

**Comment by lgalke** [comment]
Yes it is deployed on devAm 20.11.2017 16:55 schrieb Philipp Zumstein <notifications@github.com>:Okay, sounds good. Is this already deployed?
