### ISSUE TITLE
Layout of Reference/Scan View

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#184]
For working in the reference/scan view it is important, to see the original (references from Crossref or scan) side-by-side with the suggestions or newly entered data. This is currently not always possible, especially for references at the end of the list, one needs to scroll up and down a lot and can not compare the two things easily. Can we improve the layout to achieve this goal?

**Comment by lgalke** [comment]
Yes,we are thinking about a good variant. Maybe have the right-hand-side auto-scroll as you go through the left-hand-side's references or allow individual scrolling... or collapsing unnecessary information on the left-hand-side while leaving the right-hand-side as is.

**Comment by lgalke** [comment]
- [ ] scrolling in entry-list

**Comment by lgalke** [comment]
We now have scrolling:
- [x] for the entry list
- [x] for the suggestions
- [x] for the todo list
