### ISSUE TITLE
Small references button inside of list item

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#187]
Instead of a big green button `<references>`, we want a smaller button *inside* of the short references display.

**Comment by chah3d** [comment]
Like this? 
![selection_053](https://user-images.githubusercontent.com/32481062/35566450-bedb461e-05c1-11e8-9297-9a3c974eaa93.png)

**Comment by lgalke** [comment]
Yes, to me it looks good!

**Comment by lgalke** [comment]
Incorporated also in current dev branch.
