### ISSUE TITLE
Breadcrumb for electronic journal (articles) is empty

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#188]
See for example in dev the newly added example in electronic journal.

**Comment by lgalke** [comment]
That's true, a statement is missing which passes back the "path" when selecting a journal. Thanks for reporting this.

**Comment by zuphilip** [comment]
Note, there are some changes coming from the OpenCitations' hierarchical data model, which might also influence this issue.

**Comment by lgalke** [comment]
Good to know.

**Comment by zuphilip** [comment]
This seems to be fixed now. Thank you!
