### ISSUE TITLE
Capability to manually add a missing reference.

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#189]
Add the capability to manually add a missing reference. E.g. by a button.

**Comment by lgalke** [comment]
To implement the functionality for adding missing references we need a `POST` operation on bib.-entry level in the back-end. @anlausch

**Comment by anlausch** [comment]
Ok, is this needed for the evaluation?

**Comment by LauraErhard** [comment]
I don't think so. We only work with journal articles at the moment and I didn't come across any missing references this week (I worked on 3 articles). Should be okay if you do it later.

**Comment by lgalke** [comment]
Capability in back-end is present https://locdb.bib.uni-mannheim.de/locdb-dev/docs/ , now we just need to connect the frontend.

**Comment by lgalke** [comment]
Discussion is continued in #238.
