### ISSUE TITLE
502 error for external suggestions in frontend

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#191]
Currently, I see a 502 proxy error for retrieving external suggestions for the query `The Sociology of Work and Occupations  Abbott Andrew`  in the `dev` system, but when I try to open the same url to the backend in a new tab it works.

![502](https://user-images.githubusercontent.com/5199995/33320902-0342aafe-d444-11e7-88cc-d1c0abda65d3.png)

**Comment by lgalke** [comment]
Is this referring to the Production or Development environment?

**Comment by zuphilip** [comment]
Development environment

**Comment by lgalke** [comment]
Will check.

**Comment by zuphilip** [comment]
Could you reproduce this behavior?

**Comment by lgalke** [comment]
No, I could unfortunately not reproduce it. 😞

**Comment by anlausch** [comment]
Me neither. But I will keep an eye on it.

**Comment by lgalke** [comment]
From time to time, we also experienced these issues but then in the next request (without even reloading or something), it worked again. Maybe there is just some HTTP errors happening somewhere, which can never be ruled out completely.

**Comment by anlausch** [comment]
That might be possible. I will also check in detail what's happening in the backend when we see this behavior. In my opinion that's of course annoying and the issue should be removed asap, but this should not prevent us from cataloguing. Maybe one can then just trigger the suggestions again. What do you think @zuphilip?

**Comment by zuphilip** [comment]
Yes, that sounds okay. We tested today more together and the others didn't report  such errors. I delete my browser cache now also completely. If we have the chance to debug one of these cases more into details, then we should do this. Otherwise we can hope that they are rare...

**Comment by lgalke** [comment]
Totally agree. Especially if happening only occasionally, it is even more important to report logs etc. so that we get a chance to fix it. For the case it is *just* a random http error. I could think of adding something like `retry 3 times` to the request.

**Comment by lgalke** [comment]
Reopen or open new issue, if occurs again.
