### ISSUE TITLE
Problems with searching by DOI (external suggestions)

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#192]
I tried to search for the DOI `10.1007/s00148-005-0056-5` in the getExternalSuggestionsByQueryString but no results are found, also Crossref should return https://search.crossref.org/?q=10.1007%2Fs00148-005-0056-5

**Comment by lgalke** [comment]
At the moment, we are not doing any structured search. We are aware that it might be helpful at some point, but we still need to find a good solution. Maybe some kind of very simple query language which does not make it necessary to have a fully-qualified facetted search form. E.g. detect `DOI=10.1007/s00148-005-0056-5` in the query field and issue a structured search depending on that.

**Comment by zuphilip** [comment]
Yes, I am aware of this. But I copied the DOI value manually in the query field and then press the search button again. Why does this not work?

**Comment by lgalke** [comment]
Because of the unstructured search, I presume that @anlausch is also just querying CrossRef's "unstructured search" endpoint. Still, I am not sure how what endpoints are exactly used and how they are queried. In any case, if we decide to assume some structure in the query string, this would resolve this as a side-effect.

**Comment by zuphilip** [comment]
The unstructured search for humans is what I linked above and which also works for DOI: https://search.crossref.org/?q=10.1007%2Fs00148-005-0056-5 . @anlausch Which query url do you use for Crossref?

**Comment by lgalke** [comment]
Ah I might have an idea: there is not much text similarity between the title of the document and the raw DOI. At the point where we manually compute the confidence value for external suggestions. Good to have this pointed out!

**Comment by lgalke** [comment]
Hm, also setting the threshold to zero does not help.

**Comment by zuphilip** [comment]
By setting the threshold to `0.1` I had some results with titles including `10` etc.

**Comment by anlausch** [comment]
I am currently using Crossref's node.js wrapper for querying the API [1]. The api is documented here [2]. The url query you are listing is not part of that API and therefore also not intended for purposes similar to ours.

When I search using the .works function with the doi. It returns results, but at least in the first 20 results, I couldn't find the right result at all. You can check this here:
https://api.crossref.org/works?query=10.1007/s00148-005-0056-5

An option is that I check whether the query string is a doi and then use the specific function .work for returning a result by doi. That corresponds to this request, which returns the right result:
https://api.crossref.org/works/10.1007/s00148-005-0056-5

If you want this feature, then you can request it and I can implement it. But, I think that currently, we have many urgent things to do (data model redesign etc.). 

[1] https://github.com/scienceai/crossref

**Comment by zuphilip** [comment]
> An option is that I check whether the query string is a doi and then use the specific function .work for returning a result by doi

Yes, we should do that and I guess that this is also what the online search of Crossref does. I can help you with the regexp for the DOI (I have there some experience from Zotero translators). The priority for this should IMO be pretty high, because this is otherwise a blocker for any efficient work with the editorial system. CC @kleinann

**Comment by kleinann** [comment]
It's still not possible to generate suggestions from DOIs. Could we implement this now, @anlausch ? It would certainly increase the performance a good deal.

**Comment by anlausch** [comment]
The feature is now available in the development version. https://github.com/locdb/loc-db/commit/0d9eea5ab1036ca902d670b89aaa2a17ca088329

The functionality relies on the regex given here: https://www.crossref.org/blog/dois-and-matching-regular-expressions/ . Therefore, it should work in most of the cases with high precision.

**Comment by zuphilip** [comment]
I am looking forward to test this in the frontend. But I guess that @lgalke has to do something for that?

**Comment by anlausch** [comment]
No, it should work out of the box for Crossref.

**Comment by LauraErhard** [comment]
For the automatic search with the DOI there is an issue #287.
But a small hint, I noticed that if there is a space at the beginning or end of the DOI the search doesn't work.

**Comment by anlausch** [comment]
The problem was the regular expression we use. Now a relaxed version of this is deployed.
