### ISSUE TITLE
URL SWB is empty, PPN not saved

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#193]
In the external suggestions, when a result in the SWB is found, the field `URL SWB` is empty. Actually, for the SWB I suggest to save the PPN from which then an URL can be easily derived. E.g. PPN `112886337` with URL http://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=112886337&INDEXSET=1 . The PPN in the SWB is in MARC field `001`.

**Comment by lgalke** [comment]
The URL pattern is very valuable and I could use it to make all PPNs clickable as long as this really applies to all considered PPN values. Was the PPN field filled in this case?

**Comment by zuphilip** [comment]
This only works for SWB PPNs but that is also what we have at the moment (other PPNs might become important in the future).

> Was the PPN field filled in this case?

Not sure, what you mean here... The data saved in the backend looks like this:

```json
  {
    "_id": "5a1d6cfc35c9107540ef9ce6",
    "title": "Gurus, Hired Guns, and Warm Bodies",
    "subtitle": "Itinerant Experts in a Knowledge Economy \/",
    "publicationYear": "2006",
    "status": "EXTERNAL",
    "__v": 4,
    "containerTitle": "",
    "edition": "1",
    "number": "",
    "type": "",
    "embodiedAs": [
      
    ],
    "parts": [
      
    ],
    "cites": [
      
    ],
    "contributors": [
      {
        "roleType": "AUTHOR",
        "_id": "5a1d6fcd9e32bd7a0db00d0c",
        "heldBy": {
          "givenName": "",
          "familyName": "",
          "nameString": "Kunda, Gideon",
          "identifiers": [
            
          ]
        },
        "identifiers": [
          
        ]
      },
      {
        "roleType": "PUBLISHER",
        "_id": "5a1d6fcd9e32bd7a0db00d0b",
        "heldBy": {
          "givenName": "",
          "familyName": "",
          "nameString": "Princeton University Press,",
          "identifiers": [
            
          ]
        },
        "identifiers": [
          
        ]
      },
      {
        "roleType": "AUTHOR",
        "_id": "5a1d6fcd9e32bd7a0db00d0a",
        "heldBy": {
          "givenName": "",
          "familyName": "",
          "nameString": "Barley, Stephen R.",
          "identifiers": [
            
          ]
        },
        "identifiers": [
          
        ]
      }
    ],
    "identifiers": [
      {
        "scheme": "ISBN",
        "literalValue": "9781400841271",
        "_id": "5a1d6fcd9e32bd7a0db00d09"
      },
      {
        "scheme": "URI",
        "literalValue": "http:\/\/www.degruyter.com\/search?f_0=isbnissn&q_0=9781400841271&searchTitles=true",
        "_id": "5a1d6fcd9e32bd7a0db00d08"
      },
      {
        "scheme": "URI",
        "literalValue": "http:\/\/www.degruyter.com\/doi\/book\/10.1515\/9781400841271",
        "_id": "5a1d6fcd9e32bd7a0db00d07"
      },
      {
        "scheme": "URI",
        "literalValue": "https:\/\/www.degruyter.com\/doi\/book\/10.1515\/9781400841271",
        "_id": "5a1d6fcd9e32bd7a0db00d06"
      },
      {
        "scheme": "URL_SWB",
        "literalValue": "",
        "_id": "5a1d6fcd9e32bd7a0db00d05"
      }
    ]
  }
```

**Comment by lgalke** [comment]
Okay if `scheme="PPN", literalValue="thePPN"` is not present in the `identifiers` list there is not much I can do in the front-end to reverse-engineer the PPN. That's why I was asking. Thanks for the detailed inspection. Still making PPNs clickable in principle would be nice to have.

**Comment by zuphilip** [comment]
Okay, I understand the frontend perspective. But then we should make sure that it saved in the backend, @anlausch , right?

**Comment by anlausch** [comment]
Thanks for pointing out. I am working on this.

**Comment by anlausch** [comment]
@zuphilip I would like to have a marc parser that is as generic as possible for our purposes. Marc control field 001 contains a control number, which is in case of swb ppn and also for example in the case of zdb. The field 003 should contain the control number type, but in case of these two sources it contains the identifier of the organization code. In case of BSZ it's DE-576 (that's unproblematic) but in the case of zdb it's DE-101 which relates to DNB. Is it okay to check for this in order to determine the ppn type?

**Comment by anlausch** [comment]
Is now implemented like this. https://github.com/locdb/loc-db/commit/9d9df3e4d1a1977220e0edde68bc9b1f3b8718ad
Feel free to reopen again if there are problems with the approach described above or anything else.

**Comment by zuphilip** [comment]
Thank you @anlausch ! I will test it later.
