### ISSUE TITLE
Plan for next deployment

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#194]
There are some improvements in the developing system, e.g. labels in the list of references, link to Google Scholar, breadcrump info. When should we plan to deploy this in the production system? Is there anything we should check before?

**Comment by lgalke** [comment]
The critical point is the differentiation between input resources. The input type 'COLLECTION' is in the dev version already (temporarily) mapped to 'BOOK_CHAPTER', which might need to be reverted in order to deploy it to production. I can double check and deploy the current dev front/end to production before the end of the week.

**Comment by zuphilip** [comment]
We should fix #191 first. Let me know when anything else should be tested before deployment.

**Comment by anlausch** [comment]
I can deploy the dev version to the prod environment at any time.

**Comment by lgalke** [comment]
#191 is only occurring in the dev setup right now, for prod everything works fine. Do you have an idea of what causes this issue?

**Comment by lgalke** [comment]
A version including #195 is now deployed on dev. Feel free to have a look at it before it gets deployed on prod.

**Comment by lgalke** [comment]
Final routing issues with the frontpage are now also resolved.

**Comment by zuphilip** [comment]
@lgalke @anlausch Any news about the issue #191? This seems IMO to be a blocker for deployment now.

**Comment by lgalke** [comment]
@anlausch have a call tomorrow afternoon to synchronize for deployment? Would be great if everything works out of the box, but afterwards I am basically be travelling and thus, unable to fix any upcoming problems.

**Comment by lgalke** [comment]
After asserting that the dev version also works with the currently deployed production back-end, I updated the production version just now. Let me know if there are any unexpected problems.

**Comment by zuphilip** [comment]
@LauraErhard Can you do the testing of the production instances, which is newly deployed?

**Comment by LauraErhard** [comment]
Yes I can do it.

**Comment by LauraErhard** [comment]
I tried to `commit link` and got the 418 error again.
![418](https://user-images.githubusercontent.com/32642653/33490032-0b417c02-d6b6-11e7-8290-c348c320bdf9.png)

**Comment by LauraErhard** [comment]
At the moment the suggestions take a long time to load. Is it my internet connection or is there something else responsable for the lagging?
Everything else looks and works like the dev version.

**Comment by lgalke** [comment]
No idea why that is the case, but @anlausch will probably update the prod version soon aswell. The front-end so far worked fine with both current dev (which will then be prod) and current prod backends.

Regarding the 418, whenever you see this please report exactly:

1. whether the `references` field of the entry was filled before
2. which of `internal`, `external` or `new resource` you selected.
3. if possible, copy paste console output

As in #208, the commit logic is quite complicated and tracing down such problems is very valuable.

What I already know is that sometimes the external suggestions have an identifier with no value which results in an error when trying to add it to locdb. I imposed a brute-force fix at some other point but it could be possible that somewhere inside the commit logic something similar happens.

Thanks for the extensive testing.

**Comment by LauraErhard** [comment]
Error 418:
1. the `references` field was not filled before
2. I selected a crossref external suggestion
3. 
`400 - Bad Request {"message":"Validation errors","errors":[{"code":"INVALID_REQUEST_PARAMETER","errors":[{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","35","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","34","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","33","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","32","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","31","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","30","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","29","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","28","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","27","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","26","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","25","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","24","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","23","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","22","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","21","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","19","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","18","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","17","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","16","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","15","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","14","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","13","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","11","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","9","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","8","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","7","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","6","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","5","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","4","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","3","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","2","identifiers","0"]},{"code":"OBJECT_MISSING_REQUIRED_PROPERTY","params":["literalValue"],"message":"Missing required property: literalValue","path":["parts","1","identifiers","0"]}],"in":"body","message":"Invalid parameter (bibliographicResource): Value failed JSON Schema validation","name":"bibliographicResource","path":["paths","/bibliographicResources","post","parameters","0"]}]}`

**Comment by anlausch** [comment]
I just deployed the current dev version to prod.
