### ISSUE TITLE
Edited information in suggestions are not saved

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#197]
![2017-11-29_20-54-59](https://user-images.githubusercontent.com/5199995/33396091-d00517bc-d547-11e7-9e8f-4ea42611457e.gif)

**Comment by lgalke** [comment]
9743b4d . Was caused by our more or less recent split into resource-view(s) and the resource-form itself. Now the correct reference is retained while the callback updates are applied. Will be deployed on dev now, on prod with respect to #194 .
