### ISSUE TITLE
Year in suggestion from Crossref is missing

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#201]
E.g. [10.2307/20034152](10.2307/20034152), title: Rules for the World: International Organizations in Global Politics

**Comment by anlausch** [comment]
I am going to add this asap.

**Comment by anlausch** [comment]
Should be solved with https://github.com/locdb/loc-db/commit/4d5f2083f8527e144d15478382de8c37b1a5a87c. Feel free to reopen again.

**Comment by zuphilip** [comment]
Thank you! 🙇
