### ISSUE TITLE
How to input names?

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#204]
Currently we see sometimes `familyName givenName` which seems unusal. The OC model suggest as one possibility `givenName familyName` or to split these parts up. When we begin to input these names manually we should also have a clear guideline.

**Comment by lgalke** [comment]
Currently, we only use the more generic nameString property, since the OCR component also does not detect which is the first and which is the lastname.

**Comment by lgalke** [comment]
In #58 we also figured out, that seperating between first and last names is difficult in principle.

**Comment by zuphilip** [comment]
Sorry, I should be more specific. I am aware of the problems with automatically splitting a name string into first and last name. That is not what I suggest here.

But sometimes we already have first and last names e.g. from Crossref. OpenCitations seem to save them then also into two different fields. Moreover, when we have to input them manually, then we want to do that consistent, e.g.
* `lastName, firstName`
* `firstName lastName`

However, the currently used `lastName firstName` is very uncommon, or do I miss the point here?

![author-names](https://user-images.githubusercontent.com/5199995/33445132-5ca1ada2-d5fc-11e7-931b-25435bd5ce28.png)

Picture shows our captured data vs. the original data from Crossref for http://api.crossref.org/works/10.2307/2757850

**Comment by lgalke** [comment]
Alright, I can check when the data is present and display it accordingly.
Would you prefer <firstname> <lastname> over <lastname>, <firstname> ?

In any case I would need to default to <namestring>, whenever there is no structure.

**Comment by zuphilip** [comment]
For inputing `lastName, firstName` is more accurate and allows to split the name string into parts. However, we should according to the OpenCitation model save this either as two parts or in the form `firstName lastName`.

**Comment by lgalke** [comment]
Just to remember later:

For editing:

1. When input string contains `,`:
- Assume string before `,` as lastname, string after `,` as firstname
- Store both structured (`firstname` and `lastname`) and unstructured variant (`namestring`) for safety
2. When displaying prefer structured `<lastname>, <firstname>` format, if possible else fallback to `nameString`

**Comment by lgalke** [comment]
#252

**Comment by lgalke** [comment]
What if some organization name contains a `,` Guess we wont get around putting separate fields into the form.

**Comment by lgalke** [comment]
190d0fc
