### ISSUE TITLE
Marking better which entry is active

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#205]
I could envision a thick bar at the beginning, something like

![bar-beginning](https://user-images.githubusercontent.com/5199995/33434129-93865cdc-d5de-11e7-9027-7d84e6dd618d.png)

**Comment by lgalke** [comment]
Good idea, we will take that into account for the mock-ups as well as the more polished, next version in general.

**Comment by chah3d** [comment]
Looks this like what you had in mind or is it still too subtle?
![selection_050](https://user-images.githubusercontent.com/32481062/35442600-21793190-02a8-11e8-8dc4-d3e0de836879.png)

**Comment by zuphilip** [comment]
Yeah, this looks like what I have envisioned. Is this already implemented?

**Comment by lgalke** [comment]
Yes. In the meantime it is also merged into dev branch / deployment.
