### ISSUE TITLE
Url encoding fails for some queries

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#206]
Just noticed that the query fails for

1. Enter `Das kosmopolitische lEuropa; Suhrkamp Verlag, UIrich Grande lBeck` into search field

2. **Expected** any results

3. **Result** cross origin fail : 

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://locdb.bib.uni-mannheim.de/locdb-dev/getInternalSuggestionsByQueryString?query=Das%2520kosmopolitische%2520lEuropa;%2520Suhrkamp%2520Verlag,%2520UIrich%2520Grande%2520lBeck&threshold=1. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://locdb.bib.uni-mannheim.de/locdb-dev/getExternalSuggestionsByQueryString?query=Das%2520kosmopolitische%2520lEuropa;%2520Suhrkamp%2520Verlag,%2520UIrich%2520Grande%2520lBeck&threshold=0.5. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by anlausch** [comment]
Sorry, but I cannot reproduce what you are referring to. For both services I copied exactly the url given in your error message and I just see that it works and that the CORS headers are set as you requested.
How can we support you with this?
![image](https://user-images.githubusercontent.com/20592651/33441068-0dff0fdc-d5f2-11e7-9721-d5ab77bf5bdd.png)
![image](https://user-images.githubusercontent.com/20592651/33441352-c191d73c-d5f2-11e7-8c68-c3e14dcfd70c.png)

**Comment by zuphilip** [comment]
This works for me as well in the new `Browse` tab:

![search-title](https://user-images.githubusercontent.com/5199995/33447039-41e0dac8-d602-11e7-96ac-15cef4deae27.png)

**Comment by lgalke** [comment]
Strange, then it might be just related to my local development setting..
