### ISSUE TITLE
Delete wrong bibliographic entries

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#207]
Sometimes the data from Crossref or scan process produces also wrong bibliographic entries. We have here a case where one reference was wrongly splitted up into two bibliographic entries and reported by Crossref. Thus, we need to have a delete bibliographic entry button, similar to #189.

**Comment by lgalke** [comment]
Fabian will address this issue.

**Comment by chah3d** [comment]
There will be a button under the edit form in the todo detail view, which deletes the current entry: 
![selection_056](https://user-images.githubusercontent.com/32481062/35568861-ac404898-05ca-11e8-954f-ef4af3cc8df7.png)

**Comment by lgalke** [comment]
Great, just make sure to ask for confirmation (by dialog) before performing the actual delete. Code is present already at bibliographic resources level delete or here https://www.w3schools.com/jsref/met_win_confirm.asp

**Comment by chah3d** [comment]
Yes, is works the same way as deleting a resource
