### ISSUE TITLE
Unknown entries in ingest attached to empty container

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#214]
As we started working in the production system, we entered a few journal articles from `Acta Sociologica`. However, now there are a lot other entries in the ingest pane which are attached to an empty container:

![empty-container](https://user-images.githubusercontent.com/5199995/33954248-fed6b910-e037-11e7-87f5-8ee63eaf32ff.png)

The first entry is from a journal by SAGE and the second one is from a journal by CUP, thus **they never should be attached to the same resource**. No idea why the container resource is completely **empty**. If you try to set the type in the empty container resource, then this information is not surviving a refresh. The first entry "Collective Feelings" has no type, which should not be possible. We have found one example "The school careers of ethnic minority youth in France" in this list, which we used also for a target resource in the resolving step.

The main question is: **from which process are these entries created and can we stop that?**

**Comment by anlausch** [comment]
As a quick guess: I think this is due to the fact, that the front end is submitting (saving) bibliographic resources as targets for links with the status EXTERNAL. I pointed this out in a comment in https://github.com/locdb/locdb-frend/issues/208.

**Comment by lgalke** [comment]
If that was indeed the problem, bf4e494 should fix it

**Comment by lgalke** [comment]
Deployed to dev.

**Comment by zuphilip** [comment]
I cannot test on dev, because there are some 500 errors in the db calls...

**Comment by zuphilip** [comment]
Maybe a newer db version is deployed on test?

**Comment by lgalke** [comment]
I'm just thinking about this issue again:
- Every Resource marked with `EXTERNAL` is a ToDo item.
- When commit a link to an external resource we set its status to `VALID`, since `EXTERNAL` is not appropriate here.

What needs to be asserted is: when we edit an **external** resource (read: a ToDo item), the status should **not** change.

**Comment by lgalke** [comment]
Will be addressed in #243

**Comment by lgalke** [comment]
The only case, where we touch the status of the `br` is when a new BR is migrated from an external suggestion. Which should be marked as `VALID`, **NOT** `EXTERNAL`.
