### ISSUE TITLE
Internal search results and ranking

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#215]
The internal search results and ranking seems to be strange. Here is an example for searching (brows pane) in the production system:

1. Search for `careers` and you find two internal items (actually a duplicate), with the title "The school careers of ethnic minority youth in France". ✔️ 
2. Search for `school careers` and you find several items, but the two items from above are only at rank 5 and 6. Actually, the better ranked titles don't have the word `careers` anywhere. ❓ 
3. Search for `The school careers` show several results, but not the ones we are looking for. ✖️

**Comment by anlausch** [comment]
https://locdb.bib.uni-mannheim.de/locdb/getInternalSuggestionsByQueryString?query=school%20careers returns in my case the correct results in rank 1 and 2 and all the other results have school in the title or subtitle. Maybe there is a problem on how the query is submitted?

For 3 I agree and will investigate on this.

**Comment by zuphilip** [comment]
For 2: Okay, the output is the same also with the currently used `threshold=1`. But it seems that the fronted orders them differently, then the backend outputs them. Or are there any confidence values for ordering?

**Comment by lgalke** [comment]
Just had a look, we do not reorder the suggestions in the front-end.

**Comment by anlausch** [comment]
I think 2) might be related to the URL encoding again, because I saw that from the front end this URL is called: https://locdb.bib.uni-mannheim.de/locdb/getInternalSuggestionsByQueryString?query=school%2520careers&threshold=1
But `%2520` is I think a twice-encoded string, which encodes in a first step the space ` ` to `%20` and then the `%20` to `%2520`. Am I right? Of course, I am URL decoding in the backend, but that it is encoded multiple times is a bit unusual. Would you like to adapt @lgalke? Otherwise, I can, of course, have a closer look and decode specifically for what I get, but for me it seems a bit weird. What do you think?

**Comment by lgalke** [comment]
hm when I deactivate the manual `encodeURI` step, I get
`https://locdb.bib.uni-mannheim.de/locdb-dev/getInternalSuggestionsByQueryString?query=school careers&threshold=1`
which leads to 502 proxy error


``` html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/locdb-dev/getInternalSuggestionsByQueryString">GET&nbsp;/locdb-dev/getInternalSuggestionsByQueryString</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
<hr>
<address>Apache/2.4.25 (Debian) Server at locdb.bib.uni-mannheim.de Port 443</address>
</body></html>
```

**Comment by lgalke** [comment]
Reverted and encoded the Query string again, but atm there are still some 502, 503 errors. Are you updating something atm? My browser also showed me just a single encoded request right now.

`https://locdb.bib.uni-mannheim.de/locdb-dev/getInternalSuggestionsByQueryString?query=school%20careers&threshold=1`

**Comment by zuphilip** [comment]
On dev I have seen similar errors, see https://github.com/locdb/locdb-frend/issues/214#issuecomment-351697972

**Comment by zuphilip** [comment]
@lgalke Do you still see these 5XX errors in the external suggestions?

**Comment by lgalke** [comment]
@zuphilip yes :arrow_right: #217

**Comment by lgalke** [comment]
In the context of adapting to the new datamodel, we now use Swagger-generated code. We hope that for that reason, such communication issues can be avoided (since the backend also uses Swagger). Let's see how it turns out.

**Comment by lgalke** [comment]
The conversion works now great with swagger-generated interface code. When the search behavior is still not precise, please raise another issue.
