### ISSUE TITLE
500 error "Mapping failed" in dev server

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#217]
When I open the frontend in the dev server and click on resolve, I see the following error:

![dev-500](https://user-images.githubusercontent.com/5199995/34196338-02655288-e562-11e7-9526-94a1fc4f447e.png)

Moreover, the journals tab remains empty, also I just entered a DOI, which can be found with the webservice (no. 82).

**Comment by lgalke** [comment]
```
Request URL: https://locdb.bib.uni-mannheim.de/locdb-dev/getToDo?status=EXTERNAL
Status code: 500 Internal Server Error
```
```json
{"message":"Mapping failed."}
````

It is the same behaviour for me, @anlausch did you change the enum name for ToDos that are electronic journals?

**Comment by lgalke** [comment]
Will close for now, as the referred dev model is obsolete. On `dev` we are currently adapting the front-end to the new data model.
