### ISSUE TITLE
'Browse'-section doesn't work

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#223]
The Browse section doesn't work at the moment (nothing urgent, but I thought you should know).

**Comment by lgalke** [comment]
For now the browse section is just filled with a placeholder reusing the Suggestion Interface. We could even think about omitting it for the Demo deployment.

**Comment by lgalke** [comment]
https://locdb.bib.uni-mannheim.de/demo-frontend/
Here it should be working right now. The demo database is just still empty at the moment.

**Comment by lgalke** [comment]
Close for now, main functionality is working (not yet on production, but will be in the dev soon). When deployed we can open new issues, regarding the Browse component.
