### ISSUE TITLE
Dont show fully-validated todo items

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#234]
The todo list should only contain resources that are not yet completely processed.
Of course all resources should be visible in the Browse section. There is already a status attribute somewhere indicating this.

**Comment by lgalke** [comment]
For linking, we call the `GET updateTargetBibliographicResource` service. The documentation says that it also puts the entry in "valid" state. So that should be fine.
What happens when all entries of some Resource are `valid` later on. Do you still consider it as a ToDo item and send it over the network? @anlausch

**Comment by anlausch** [comment]
Yes. In order to fully validate a bibliographic resource, the overall status needs to be set to `valid` for resources without scans and additionally -- in case scans are present -- all scans need to be `valid`.

**Comment by kleinann** [comment]
Is this question still open?

**Comment by lgalke** [comment]
Yes

**Comment by kleinann** [comment]
Is it a question for Anne? I don't see any possibility to set a "valid"-property manually in the frontend. I thought that it would be set when the citations are all linked to a proper bibliographic resource.

**Comment by lgalke** [comment]
Yes this is a question to @anlausch because right now we do set entries to valid but we do not check every single time whether all entries of a todo item are linked. This would probably be cleaner when performed on the back-end side, after an entry is validated.

**Comment by lgalke** [comment]
Anne has added the '/setValid' endpoint which specifically sets the state of a resource to `VALID`, with the side-effect of setting all unlinked entries to `OBSOLETE`. Any preferences on where we could put the validation button?

**Comment by kleinann** [comment]
Maybe at the bottom, next to the "Commit Link" button?

**Comment by LauraErhard** [comment]
I think the bottom is fine, but I would prefer under the reference list. But I'm okay with both.

**Comment by lgalke** [comment]
Guess it would make more sense close to the reference list than beneath commit as it is related to the resource itself and not one specific citation target (also with #354, the 'global' commit button would disappear). Other options include within the agenda or even within the edit form because it will be used rather rarely. Would it make sense to also implement the inverse operation (set it to 'ToDo' again and "reactivate" all the "OBSOLETE" entries)? If yes, we'd need back-end support also for this.

**Comment by LauraErhard** [comment]
> Guess it would make more sense close to the reference list than beneath commit as it is related to the resource itself and not one specific citation target (also with #354, the 'global' commit button would disappear). Other options include within the agenda or even within the edit form because it will be used rather rarely.

I thought I have to click the valid button everytime I want to close a resource?! 
I just linked every reference in a reference list (on dev) and now I still see the resource in the agenda but every box and reference in the reference list is gone. Is this supposed to work this way? And would I now have to press the valid button to completely finish this resource?!

The advantage of having the button directly under the reference list would be that you can directly check if you missed a reference or not.

> Would it make sense to also implement the inverse operation (set it to 'ToDo' again and "reactivate" all the "OBSOLETE" entries)? If yes, we'd need back-end support also for this.

I think we would only have to reactivate a resource if we wrongly closed it too early. I hope this doesn't happen at all/very rarely. Still I think this would be a nice to have feature, but not a priority at the moment.

**Comment by lgalke** [comment]
>I thought I have to click the valid button everytime I want to close a resource?!
The button should be pressed if the resource is done. It will not appear on the agenda again, and its remaining unlinked entries are marked obsolete.

>I just linked every reference in a reference list (on dev) and now I still see the resource in the agenda >but every box and reference in the reference list is gone. Is this supposed to work this way?
> And would I now have to press the valid button to completely finish this resource?!
Yes, that will be the exact purpose of the new button.

**Comment by lgalke** [comment]
Button is now included, will be deployed first on dev. #378
