### ISSUE TITLE
Create new Bibliographic Entry from scratch

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#238]
It happens that the recognized or imported reference lists don't contain all bibliographic entries that exist in the original text. Then, the librarian must have the possibility to create a new bibliographic entry from scratch.

**Comment by lgalke** [comment]
Same as #189

**Comment by lgalke** [comment]
Will be addressed in the datamodel rework #243

**Comment by lgalke** [comment]
Should be addressed.
