### ISSUE TITLE
Source Detection

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#244]
At the moment, we are harvesting the resources `identifiers` for known identifiers to infer where some suggestion came from. Here: We need to add ID_k10PLUS and ID_GVI to the list.

Just for remembering, this is a mere reconstruction by heuristics of what is known already: **As soon as multiple external sources yield resources with same identifier schemes, this will be invalid**. In this case we need a `source` or similar property that tells us from which external source this specific suggestion came.

**Comment by lgalke** [comment]
@anlausch will explicitly send this bit of information soon.

**Comment by anlausch** [comment]
Should be there now with https://github.com/locdb/loc-db/commit/78989836092db0b7035ee5656057309cba040ace .
