### ISSUE TITLE
Ingest Malfunction

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#250]
Ingest component currently does not work, yet it would help further testing. The application compiles right now. Please make sure to delete `node_modules` and `package-lock.json` before running `npm install`.

**Comment by chah3d** [comment]
should the embodiment type also be mandatory?
![selection_062](https://user-images.githubusercontent.com/32481062/37522729-211979b4-2925-11e8-83d0-040e33193b43.png)

electronic resources also have fields for page-numbers, which are optional. Are there any cases in which they are useful?
![selection_063](https://user-images.githubusercontent.com/32481062/37522844-81c6b51a-2925-11e8-8a03-6988b20601f5.png)

**Comment by lgalke** [comment]
I am not quite sure, to what this embodiment type refers. If it only distinguished between `DIGITAL` and `PRINT`, we can silently set it to `PRINT` for file uploads and `DIGITAL` for electronic ingests via DOI.

Just merged the changes, I was also working on it a little. Most notably, `batchInformation` now holds not only the resource type but also the identifier scheme for the whole batch. If something else is desired, we can add it there.
