### ISSUE TITLE
Where are the scans

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#255]
The expected location does (at least in this case) not hold the scan anymore: https://locdb.bib.uni-mannheim.de/locdb-dev/scans/5aaf87081ec11656af02a888 . Before, we could find it at the URL with the scanID appended (as above). Is this still the preferred way of accessing the scans? @anlausch

**Comment by lgalke** [comment]
Also tried `/locdb-dev/scans/${scan.scanName}`. This could be just one spurious example, however @anlausch, please clarifiy where to find the scans with the new datamodel.

**Comment by anlausch** [comment]
@lgalke When I click on the link, the scan appears. Maybe I don't understand the issue, but to me everything seems fine.

**Comment by lgalke** [comment]
Good point. The problem is then that it is a `pdf` rather than a `png`. Didn't we have only (potentially cropped by DFKI) `png` files, before?

**Comment by anlausch** [comment]
Good catch! I forgot to set the new name. The issue is fixed and will be deployed next. Feel free to reopen again.
