### ISSUE TITLE
Error 413 - Payload Too Large

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#262]
I commited an internal suggestion and tried to add the issue information and the page information but after clicking `submit` the 413 error occured. What does that mean? 
![2018-04-16 413 error](https://user-images.githubusercontent.com/32642653/38800414-81fedd0a-4167-11e8-89bc-2545d2a277d0.png)

I checked different references in the list and there is no problem committing or changing information there. Therefore it has to be a problem with just this reference.

**Comment by anlausch** [comment]
From the screenshot it looks like just what it says: apparently, the front end tried to send too much data to the back end. So, there is some kind of limit that should be configurable. 
This will help:
https://stackoverflow.com/questions/19917401/error-request-entity-too-large

**Comment by anlausch** [comment]
Payload size is double now. https://github.com/locdb/loc-db/commit/459289b6955bec123463bd34e18713046f789602
