### ISSUE TITLE
resource embodiment data is confusingly split over several embodiedAs entries

### ISSUE THREAD

**Issue by chah3d** [locdb/locdb-frend#265]
![selection_082](https://user-images.githubusercontent.com/32481062/38863605-774f8c2a-4238-11e8-9c55-a5d33e5c938d.png)

There are some resources where a scan has an embodiedAs entry and the relevant page-numbers are stored in another entry with their own id and no reference to the corresponding scans. Is this a Bug or what is the intention behind this?

**Comment by anlausch** [comment]
This could be correct or could be wrong. To determine whether it is a bug we need to know what happened. How was the resource generated? Did you just create it?

**Comment by anlausch** [comment]
Should be fixed. Please report if the problem persists or appears on other resource types. https://github.com/locdb/loc-db/commit/c0f0f508ced1d54804642c371bf4928d27051f55
