### ISSUE TITLE
publicationDate

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#266]
When `POST`ing a new bibliographic resource we get the following error:

```json
{"message":"Validation errors","errors":[{"code":"INVALID_REQUEST_PARAMETER","errors":
[{"code":"INVALID_FORMAT","params":["date","2013"],"message":"Object didn't pass validation for format
 date: 2013","path":["report_publicationDate"]}],"in":"body","message":"Invalid parameter 
(bibliographicResource): Value failed JSON Schema validation","name":"bibliographicResource","path":
["paths","/bibliographicResources","post","parameters","0"]}]}
```

However, on Swagger the definitions are still presented as string propertiers (and thus in the connection API it is aswell):

```json
// [...]
  "journalArticle_publicationDate": "string",
  "journalIssue_publicationDate": "string",
  "journalVolume_publicationDate": "string",
  "journal_publicationDate": "string",
  "monograph_publicationDate": "string",
  "report_publicationDate": "string",
  "reportSeries_publicationDate": "string",
  "bookChapter_publicationDate": "string",
  "bookSeries_publicationDate": "string",
  "bookSet_publicationDate": "string",
  "editedBook_publicationDate": "string",
  "dissertation_publicationDate": "string",
  "proceedingsArticle_publicationDate": "string",
  "dataset_publicationDate": "string",
  "proceedings_publicationDate": "string",
  "book_publicationDate": "string",
  "referenceBook_publicationDate": "string",
  "referenceEntry_publicationDate": "string",
  "standard_publicationDate": "string",
  "standardSeries_publicationDate": "string",
  "bookPart_publicationDate": "string",
  "bookSection_publicationDate": "string",
  "bookTrack_publicationDate": "string",
  "component_publicationDate": "string",
// [...]
```

We need to know how to pass the validation checks if we are forced to send a string @anlausch .

**Comment by anlausch** [comment]
The swagger specification defines publicationDate as string but with the format date.
![image](https://user-images.githubusercontent.com/20592651/38985765-97f8935c-43ca-11e8-9405-12b3b51cdf0d.png)
This format again follows the full-date notation defined in https://tools.ietf.org/html/rfc3339#section-5.6.
So, there would be some preprocessing needed in the frontend, e.g., mapping "2013" to "2013-01-01". If this is not feasible we can also change this back, but then it is of course more difficult to search the data in terms of time etc.

**Comment by lgalke** [comment]
I see. Will try to get the conversion to work. Which value passes the validation check when there is no date present? empty string?
