### ISSUE TITLE
dev: where are the electronic journal articles?

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#269]
I just ingested a DOI and I can't find the article in the resolve part. Where should I expect it? I guessed "external" but I couldn't find it anywhere.

**Comment by lgalke** [comment]
Interesting the response payload is `[]` as if there was no electronic journal stored. Could you provide the DOI which you tried?

**Comment by LauraErhard** [comment]
I tried these two:
10.1177/0001699310392604
10.1177/0001699310392600

**Comment by lgalke** [comment]
When I try to ingest it again it says `{"message":"The resource already exists."}`, it should be somewhere. Maybe @anlausch can help: is querying for `status=EXTERNAL` still the correct way to retrieve electronic journals? or was it replaced at some point?

**Comment by anlausch** [comment]
This is still correct. The problem is that the status for externals is not properly set upon creation. I will fix this.

**Comment by anlausch** [comment]
Should work now. Please report if not. https://github.com/locdb/loc-db/commit/b53ea27f379201d450b7cedd3fdcd9a0fa622410
In order to see the effect you might need to delete the resources and then create them again or use different examples.

**Comment by anlausch** [comment]
I have no problem creating this article directly via the swagger api. @lgalke any idea?

**Comment by LauraErhard** [comment]
I tried 3 different articles just now and everything worked fine. I will check more examples tomorrow afternoon and will report back if there are any more problems or if this was just a special case. Thanks for checking.

**Comment by lgalke** [comment]
Let's hope for the best.
