### ISSUE TITLE
dev: OCR processing

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#270]
I uploaded 2 monographs and 3 chapters of one book and just the first monograph was automatically put in the OCR processed category (I played around with the "embodiment type" while uploading this file, so there is a digital and print file for this monograph.). The other 4 files bounced from "ocr processing" to "not ocr processed" in a few minutes. I tried to start a new OCR processing for the second monograph with pushing the little "play" button, but even then the file bounced back. 
![resolve_notocr](https://user-images.githubusercontent.com/32642653/39244110-f90184c8-488f-11e8-9839-927279b44db5.png)
On top of that I only see the message "Received application-type " while trying to see the pdf in the scan view.
![resolve_nopdf](https://user-images.githubusercontent.com/32642653/39244380-d13c3248-4890-11e8-9752-abadf8fdc5c8.png)

**Comment by LauraErhard** [comment]
It worked for three chapters from a different book (ppn: 489864848) directly and I can see the scanned pdfs in the scan view. The pdf file was just one page for each chapter. Maybe there is a problem with files with more than one page?

**Comment by LauraErhard** [comment]
Okay, once I clicked every "not ocr processed" file and waited for it to get processed and then clicking the next one, every file was successfully OCR processed (but the one with 9 pages, doesn't show a single box although it took 5 minutes for the file to be OCR processed). 
So there is only the issue with the "received application-type". Is this just the message if the file is not yet OCR processed?

**Comment by lgalke** [comment]
Hey @LauraErhard, we hope that those issues with long OCR processing times and/or the need for manual re-triggering will be alleviated with the upcoming version of the OCR component. For now, however, I am quite happy that at least all files got somewhat successfully processed. The `received application-type` was shown when the file was at that moment in-processing, correct?

**Comment by LauraErhard** [comment]
Yes, but the one file, where I uploaded a file with "print" and "digital" embodiment type the `received application-type` is still there although it is in the OCR processed part. But maybe that was my mistake because I see the file still in the "OCR processing" part as well.

**Comment by LauraErhard** [comment]
There are a some files (which I uploaded earlier) stuck in the OCR processing part. The pages 128-130 and 59-59 from the book Citizenship Education : Konzepte, Anregungen und Ideen zur Demokratiebildung. Is there a possibility to get them to switch to the OCR unprocessed part so we can manually trigger them again?

**Comment by lgalke** [comment]
I assume that happens automatically, when the OCR processing failed (@anlausch ?) . There is currently no possibility to cancel a single request. When the way the OCR works is still the same, it is possible that the "input pipeline" may become quite large, when many requests with many pages are sent.

**Comment by LauraErhard** [comment]
The scan for the OCR processed item doesn't show up:
![scannotfound2](https://user-images.githubusercontent.com/32642653/39307247-977a0daa-4962-11e8-90ce-2d98388e70b0.png)
![scannotfound](https://user-images.githubusercontent.com/32642653/39307250-99de7dce-4962-11e8-83bf-aed5fa36e64c.png)

**Comment by lgalke** [comment]
That is strange, also you receive Proxy Errors in response to request for suggestions. I also experienced these proxy issues some time ago and just wanted to check whether they are still present, but for now it worked for me. Maybe the two things are related... I just tried with presumably the same scan and it worked. 
![snip1](https://user-images.githubusercontent.com/3439126/39309753-113b8c58-4969-11e8-9817-e583633ea8c3.PNG)

**Comment by lgalke** [comment]
Something seems to be wrong with the connection, please make sure to enforce a cleared cache once, e.g. in firefox via <Control><Shift>r

**Comment by LauraErhard** [comment]
I cleared my cache and tried it again and now I am at the empty page with the "scan image not found" message again.

**Comment by LauraErhard** [comment]
Just fyi I'm sitting at a different computer right now and get the boxes but not the text again. The proxy errors still occur.

**Comment by lgalke** [comment]
Is it possible, that it depends on whether you are in some university network? We had this kind of restriction in the very beginning. Is it possible that this is still an issue? Otherwise I have now idea where these proxy errors come from (the error could also be forwarded by some 3rd party). @anlausch do you mind checking the backend-logs for these proxy errors?

**Comment by LauraErhard** [comment]
I'm at work therefore I should be in the university network. I just checked the proxy error message in detail and noticed that there is a third error.
![proxyerror](https://user-images.githubusercontent.com/32642653/39362519-066d6bde-4a27-11e8-9035-3cb915234d75.png)

**Comment by LauraErhard** [comment]
Strangely enough with the edited book " Globale Sicherheit und die Zukunft politischer Ordnungen" pages 27-28 I have no problems (I see the boxes and the whole scanned pdf and there is no proxy error).
![2018-04-30_scanview](https://user-images.githubusercontent.com/32642653/39427973-0d54b2fc-4c86-11e8-9284-d8316838507a.png)
This is the first OCR processed entry in the agenda, maybe between this one and the second something happened?! I hope this helps with narrowing the situation down.

**Comment by LauraErhard** [comment]
I see every OCR processed scan now, so this issue is solved.

But I got uploads stuck in the OCR processing part. I don't know if this gets better with the new OCR model, but I just wanted to keep it in our minds, that there is an issue:
![2018-05-07 ocr_processing](https://user-images.githubusercontent.com/32642653/39712812-b33f0174-5224-11e8-8adf-d2405abe44b6.png)

**Comment by LauraErhard** [comment]
We still have a file stuck in the `OCR processing` part. It looks like some references were extracted, but the scan is not visible. Why are references extracted but it didn't switch to the `OCR processed` part?!
![2018-06-15 ocr processing](https://user-images.githubusercontent.com/32642653/41466417-75090f7a-70a2-11e8-83bc-1cd779f17bcf.png)
![2018-06-15 ocr processing2](https://user-images.githubusercontent.com/32642653/41466419-7652d884-70a2-11e8-82cd-9c624bbcf07b.png)

For these occurrences would it be possible to implement a button similar to the "play-button" (#318) to either trigger the scan again or cancel the processing and switch the file to `OCR not processed` to then manually trigger it again?!

**Comment by lgalke** [comment]
The references are present, because they do come from CrossRef. We cannot cancel the OCR processing as soon as the trigger is pulled. If OCR processing fails, it will return to `NOT_OCR_PROCESSED` with a 'play'-button at some point. If OCR processing did succeed, it will probably not generate a different output when invoked another time. We hope that these OCR issues will be alleviated when the new OCR engine can be used.

**Comment by LauraErhard** [comment]
Oh, I thought the new OCR engine is already implemented. When can we expect it to work?

**Comment by lgalke** [comment]
Guess this issue is obsolete right now.
