### ISSUE TITLE
dev: external suggestions

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#271]
First a general question: where do the external suggestions come from now?

I have a few comments about the categories of the suggestions:
a. The publication year has alway days and month, but with monographs and book chapters we don't need this, because we always only have a publication year available.  Should we then always fill out 01.01. of every year? This seems a bit strange.
b. The second identifier of the example below is an ID number of the Bibliotheksverbund Bayern, but we don't have a possibility to choose this identifier type because it doesn't exist. Why was this ID chosen? There would be a SWB PPN available.
c. The author field is now filled in like `family name;first name`  this is not the way we wanted it. We wanted `family name, first name`. Is there a possibility to change the semicolon to a comma with a space after it?

![suggestions](https://user-images.githubusercontent.com/32642653/39249614-52c2ea24-489f-11e8-9b79-16602d8ba246.png)

**Comment by anlausch** [comment]
As discussed with @kleinann the suggestions come from different sources including GVI, which is the source of this specific suggestion. 
a. the publicationDate is of type full-date now. As a result of discussions with @lgalke there are/will ways such that the user just has to input the year. Anyways we can change it back to a simple string.
b. The identifier is the GVI id.  The record belonging to this is below. Please indicate if there are more identifiers that need to be extracted (see fullrecord-field).
```
{
        "catalog":"DE-604",
        "consortium":["DE-604"],
        "language":["eng"],
        "collection":"B3KAT",
        "material_content_type":["Book"],
        "fullrecord":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><collection xmlns=\"http://www.loc.gov/MARC21/slim\"><record><leader>00000nam a2200000zc 4500</leader><controlfield tag=\"001\">BV018429525</controlfield><controlfield tag=\"003\">DE-604</controlfield><controlfield tag=\"005\">20161208</controlfield><controlfield tag=\"007\">t</controlfield><controlfield tag=\"008\">040417s1973             |||| 00||| eng d</controlfield><datafield tag=\"035\" ind1=\" \" ind2=\" \"><subfield code=\"a\">(OCoLC)164680124</subfield></datafield><datafield tag=\"035\" ind1=\" \" ind2=\" \"><subfield code=\"a\">(DE-599)BVBBV018429525</subfield></datafield><datafield tag=\"040\" ind1=\" \" ind2=\" \"><subfield code=\"a\">DE-604</subfield><subfield code=\"b\">ger</subfield></datafield><datafield tag=\"049\" ind1=\" \" ind2=\" \"><subfield code=\"a\">DE-12</subfield></datafield><datafield tag=\"100\" ind1=\"1\" ind2=\" \"><subfield code=\"a\">Acheson, Dean</subfield><subfield code=\"d\">1893-1971</subfield><subfield code=\"e\">Verfasser</subfield><subfield code=\"0\">(DE-588)118643665</subfield><subfield code=\"4\">aut</subfield></datafield><datafield tag=\"245\" ind1=\"1\" ind2=\"0\"><subfield code=\"a\">This vast external realm</subfield></datafield><datafield tag=\"260\" ind1=\" \" ind2=\" \"><subfield code=\"c\">1973</subfield></datafield><datafield tag=\"505\" ind1=\"0\" ind2=\" \"><subfield code=\"a\">(1.ed.)&lt;br&gt;New York: Norton (1973). 298 S., 1 Portr. [Dean Gooderham Acheson]</subfield></datafield><datafield tag=\"924\" ind1=\" \" ind2=\" \"><subfield code=\"a\">BV018429525</subfield><subfield code=\"b\">DE-12</subfield><subfield code=\"c\">BVB</subfield></datafield></record></collection>\n",
        "ill_flag":["Undefined"],
        "material_pubform":["Monograph/Item"],
        "id":"(DE-604)BV018429525",
        "_version_":1587231005453844480,
        "recordtype":"gvimarc",
        "index_date":"2017-12-19T15:02:25.824Z"}
```
c. As it can be seen in the plain json, the back end extracts the name splitted into first an last name:
```
    {
      "book_identifiers": [
        {
          "literalValue": "164680124",
          "scheme": "OCLC_ID"
        },
        {
          "literalValue": "(DE-604)BV018429525",
          "scheme": "ID_GVI"
        }
      ],
      "type": "BOOK",
      "book_title": "This vast external realm",
      "book_contributors": [
        {
          "roleType": "AUTHOR",
          "heldBy": {
            "givenName": "Dean",
            "familyName": "Acheson"
          }
        }
      ],
      "book_publicationDate": "1973-01-01T00:00:00.000Z",
      "status": "EXTERNAL",
      "source": "GVI"
    }
```

What I am apparently missing here is the publisher. But marc data field 505 is unknown to me so far and is "Formatted contents note". That might be anything, right?

**Comment by lgalke** [comment]
I changed the seperator between lastname and firstname to `, ` strict. We were thinking that `;` might be more robust, but let's see.

**Comment by LauraErhard** [comment]
Thanks for all this information, very much appreciated.
a. The full date option is useful for journal articles. So I don't want to loose the full date there, I was just wondering what we should do, if we only have a year available.
b. I am not the expert on these IDs, maybe @zuphilip or @kleinann can help with that.
But the identifier type GVI_ID doesn't exist in the drop down list. I tried just leaving it empty and that worked fine. You probably have the type in the backend and don't need us to define it for you!?
c. Okay, we have to see. We just always used the `, ` to seperate the lastname and firstname and thought that was just the practical thing to do. But if it causes any problems we can talk about it again.

**Comment by LauraErhard** [comment]
I just noticed, the record you put first has the `"material_pubform":["Monograph/Item"],` and the json from the back end has `"type": "BOOK",`. Is there a reason this changes? Or are these two different things?

**Comment by lgalke** [comment]
So only (c) is left: @anlausch how do we deal with these identifiers? Do we add these other identifiers to our enums or should we discard them?

**Comment by kleinann** [comment]
The structure of the GVI-identifier seems to be (source-database-identifier)record-identifier.
So in (DE-604)BV018429525, DE-604 tells us that the records comes from the Bavarian Union catalogue
See http://sigel.staatsbibliothek-berlin.de/nc/suche/
and BV018429525 ist the equivalent of our ppn in this catalogue, see
http://gateway-bayern.de/BV018429525
As the GVI is the "Gemeinsamer Verbundindex", I suppose that all GVI-identifiers are in fact Verbund-Identifiers.

If we want to treat them as this, Verbund-Identifier, we'd have to analyse the GVI-identifiers and split them into the two different parts, as we do for the SWB-ppn.  Then the right qualification for the identifier would be "BVB" (Bibliotheksverbund Bayern). 
The other option is to ignore that it is in fact a Verbund-Identifier and treat it as a GVI-Identifier in its own right. We should qualify that accordingly then as "GVI". It will probably not be possible to search with the GVI-Identifier in the original databases (search for "(DE-604)BV018429525" in Bibliotheksverbund Bayern has 0 results).
Therefore, I think that the real Verbund-Identifier might be more useful, but I don't know how difficult it is to analyse the GVI-identifiers. Maybe we could also just store the GVI-identifier now and enrich the database later with the Verbund-Identifiers deduced from the GVI-identifiers.

Anyway, the cataloguer should be able to see, which kind of identifier it is.

**Comment by lgalke** [comment]
@LauraErhard when each author's firstname and lastname is seperated by `, ` what is the desired separator between multiple authors? Should we use `; ` then there?

**Comment by lgalke** [comment]
Is this resolved by now?

**Comment by LauraErhard** [comment]
Not quite.
Regarding the date, it would be nice, if for books & monographs, we only have to fill in the year, because this is all the information we have (you can add the `-01-01 ` in the backend, but in the frontend it is quite distracting) . For journal articles we do have a full date and would like to input days and month additionally.
Is there a possibility to have different date input for the various publication types?

Regarding the GVI identifier, I think the main issue is resolved. I just noticed, that the GVI identifier has no label to choose in the dropdown menu. I checked the screenshot at the beginning of the issue and it looks like the identifier is saved under ID_GVI, would you check if this is correct and add the right label to the dropdown menu?
![id_gvi](https://user-images.githubusercontent.com/32642653/44463356-c1c26000-a617-11e8-85de-6d59dd61bf7a.png)

**Comment by lgalke** [comment]
The GVI id should be now available (also deployed to dev). I couldnt find an example for testing though, so please let me know whether it is also properly recognized, when an GVI identifier is already present.

Regarding the other part about different date inputs: it should be no problem. We will implement it when we address #326 , since we also need to dynamically change the form according to which resource type is selected (to make all possibly flattened container attributes visible).

**Comment by lgalke** [comment]
I noted the specific requirement on the date field in the other issue, such that we can close this one, if there isnt anything else (?)

**Comment by LauraErhard** [comment]
I checked the GVI ID and it is available in both cases (GVI identifier already present & in the dropdown). Thank you!
