### ISSUE TITLE
[Web Meeting] Create new sub-resource

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#279]

**Comment by kleinann** [comment]
My idea was that when a parent resource already exists, it should be possible to edit it, change the publication type and add the necessary fields for the child resource.
For example: A book already exists in the database. When a chapter from this book is cited which is not yet in the database, the book is suggested. We edit the book, and change the publication type to book-chapter. Then, the specific data fields for the chapter appear and we can add them manually and commit the new resource.

**Comment by lgalke** [comment]
It is now possible by creating a new resource from reference meta-data (since there is nothing else given) and add the designated parent resource in the `partOf` field via autocompletion. Is this sufficient?

**Comment by lgalke** [comment]
Guess the other way is more intuitive, please double-check with the new interface.
The idea would be in such a case to create the meta-data of the child (new Resource from reference metadata) and connect it to the existing container. If the container was external (only within suggestions) in the first place, you can manually migrate it such that it will become available.

Let me know in case the issue is not sufficiently addressed.
