### ISSUE TITLE
Mongoose/ Elastic inconsistencies

### ISSUE THREAD

**Issue by anlausch** [locdb/locdb-frend#286]
Hi all,
the last weeks we encountered server problems (remember the proxy error 502 and others). The problem is due to inconsistencies between our data base and the search. The framework we are using for coupling these (mongoosastic), runs into a null pointer when trying to retrieve matches found in the index from the data base if they are already deleted, i.e. actually not present in the db. This null pointer cannot be catched from outside the framework and causes the server to crash.

`TypeError: Cannot read property '_id' of undefined
    at hits.forEach.doc (/home/anlausch/locdb-dev/source/node_modules/mongoosastic/lib/mongoosastic.js:149:35)
    at Array.forEach (native)
    at query.exec (/home/anlausch/locdb-dev/source/node_modules/mongoosastic/lib/mongoosastic.js:148:12)
    at /home/anlausch/locdb-dev/source/node_modules/mongoose/lib/query.js:3118:18
    at newTickHandler (/home/anlausch/locdb-dev/source/node_modules/mpromise/lib/promise.js:234:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)`

In order to avoid that behavior, we have to take care that the synchronization works properly. One solution is apparently: We should only perform changes/ deletions/ inserts using a particular document instance (no changes on the collection).
See https://github.com/mongoosastic/mongoosastic#indexing .
I tried to check every piece of code regarding that but I doubt the problem is solved 100%. 

I have now manually synced the systems and everything works again. Please report here if you see the server crash again when triggering the search and try to remember what you did before (as I am currently not able to reproduce the problem).

**Comment by LauraErhard** [comment]
I still have the 502 proxy error message.
If I understand you correctly the problem is between our data base and the search. But this time I got the internal suggestions, but as I see it, the external suggestions triggered the proxy error?! 
What I did: I opened LOCDB, clicked on the scan from book chapter "Globale Sicherheit und die Zukunft politischer Ordnungen" pages 27-28. Then I clicked on the box on the left, waited til the first search was finished (no results, but no proxy errors) and then corrected the search term and searched again. Then:
![2018-05-07 proxy error](https://user-images.githubusercontent.com/32642653/39702453-2e489666-5205-11e8-8c60-b0dc3092b118.png)

**Comment by LauraErhard** [comment]
Unfortunately I seem to have clicked on the only box the proxy error still exists. I checked like 20 different references and I don't see the proxy error anywhere else.

**Comment by anlausch** [comment]
Hi Laura,
thanks for checking on this. This particular problem is another easier one caused by missing data in one of our external sources. I will nail down the exact problem and fix this. Cheers

**Comment by LauraErhard** [comment]
I just stumbled over another error. This seems to have to do with missing information as well:
![2018-05-07 error_missing_contributors](https://user-images.githubusercontent.com/32642653/39703652-0d83c910-5209-11e8-8caa-e8cef400bc53.png)

**Comment by anlausch** [comment]
The first problem should be fixed. https://github.com/locdb/loc-db/commit/c23cd6a2d5b8225768342c37fb1e86c37348c83d

The second thing is something related to the front end where I cannot be sure whether there is actually a problem in the backend (at least the server is not crashing). I don't think so, but I will check on this.
Thanks for your effort so far and please keep on reporting the proxy errors!

**Comment by LauraErhard** [comment]
I just double checked the first problem and it's fixed. Thank you!

**Comment by chah3d** [comment]
Resources without contributors should not cause any problems in the metadata shortform anymore, however the new version is soonest deployed next week.

**Comment by lgalke** [comment]
Will deploy now.

**Comment by anlausch** [comment]
I will close the issue as it seems to be resolved.
