### ISSUE TITLE
Support DOI search in frontend

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#287]
DOIs can now be searched when they are manually copied to the search box in the frontend. It would be much more efficient if the DOI would be searched automatically. That means: If there is a DOI, this is copied to the search box automatically, and the search is started automatically.

**Comment by lgalke** [comment]
That's great. Would you prefer to search only by DOI if available, or rather title + DOI?

**Comment by lgalke** [comment]
We fill the initial query string now via DOI when there is a DOI available. Does DOI search also work for internal suggestions @anlausch ? Otherwise, we might end up with a lot of duplicates.

**Comment by anlausch** [comment]
No, but I can work on this using a similar trick as with the external suggestions.

**Comment by anlausch** [comment]
A new version is deployed in which searching internally by `doi` should work.

**Comment by lgalke** [comment]
Great. So DOI search should now be fully-working. :+1:
