### ISSUE TITLE
Idea: Button "online" for resolve view

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#292]
I suggest to have a new button "online" in the resolve view instead of showing the DOI, Crossref URL etc. Clicking on the button should then simply open the URL in a new browser tab.

![locdb-online-button](https://user-images.githubusercontent.com/5199995/40115860-14422db8-5912-11e8-8464-89508a49e631.jpg)

Compared to the current

![locdb-current](https://user-images.githubusercontent.com/5199995/40115979-84ca0088-5912-11e8-89c1-a6357259a8ea.jpg)

**Comment by LauraErhard** [comment]
I saw this is implemented now. Thank you!
I have just one (hopefully little) request. Would it be possible to automatically open the link in a new tab instead of in the same tab?

**Comment by lgalke** [comment]
Yes, of course.

**Comment by lgalke** [comment]
73e8805147a7d055f3c13e8b0300ca1c69c5b919 opens in new tab.
