### ISSUE TITLE
Use year to narrow down suggestions (filter or search)

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#293]
A lot of reference strings have the information about the publication year. This is an important information especially to choose between several suggested items, e.g. searching for the title `Minority Education and Caste: The American System in Cross-Cultural Perspective`:

![locdb-year2](https://user-images.githubusercontent.com/5199995/40116496-1c902d38-5914-11e8-807c-d7ca3ff92766.jpg)

There are several editions of this books in several catalogs. It should be possible to narrow down these suggestion by fixing the exact publication year.

I could imagine to either filter the suggestions afterwards by restricting the year, or to use the year in the search as well. Actually, it works if I additional add the year to the search in the frontend. Should we automatically add the year besides the title for all resources as a search string? (The doi case and unstructured case would stay untouched.)

**Comment by lgalke** [comment]
Adding the year to the generated query string would be no problem. Filtering would be a rather big extension, which we also have in mind to filter by source #114.

**Comment by zuphilip** [comment]
Okay, thank you for adding the year to the query again. @LauraErhard @SylviaZander Can you test this a little more and tell us if it is better or worse than before?

**Comment by anlausch** [comment]
Let me know if this causes trouble with the back end part of the search.

**Comment by LauraErhard** [comment]
Searching with or without the year doesn't make a huge difference right now.

Searching without year (0 right results):
![2018-05-30 external searchyear](https://user-images.githubusercontent.com/32642653/40720109-f3fd6ea0-6415-11e8-94ce-42c23d507d79.png)

Searching with year (0 right results):
![2018-05-30 external searchyear2](https://user-images.githubusercontent.com/32642653/40720123-fb1c86bc-6415-11e8-876b-ce4943e4d838.png)

Searching with year at the beginning of the search string (1 right results):
![2018-05-30 external searchyearfront](https://user-images.githubusercontent.com/32642653/40720136-06e11c42-6416-11e8-995a-5b6196233efd.png)

Is it possible that with making the search more fuzzy #289 you made the year more fuzzy too?! I can't quite explain why the year at the beginning of the search string provides different results as at the end. Any ideas?!

**Comment by lgalke** [comment]
@anlausch do you have an idea?

**Comment by anlausch** [comment]
The sensitivity with which the year is treated highly depends on the external source. This is I think one of the reasons why we wanted to have ad-hoc post-filtering in the frontend. Then, the search is triggered once, the user sees all the results and can next filter by year if needed. Similarly, Annette suggested that you can filter by resource type. So the idea was, that the backend tries to be as good as possible for a given search query but that then afterwards the user has the possibility to interactively explore the results. We were thinking about implementing the filter already in the backend, but then we thought that  we would probably lower the recall a lot.

**Comment by lgalke** [comment]
We have already implemented some filtering mechanisms. However, the pre-calculated suggestions usually consist of only 10 items. Assuming we would not want to re-run the query, it might become an overhead to have 5 different filters to explore the 10 items. Would it make sense to increase the number of pre-calculated suggestions at some point? Then, the 'ad-hoc post-filtering' would indeed become more useful.

**Comment by anlausch** [comment]
+1 I'll update you regarding this.

**Comment by anlausch** [comment]
I have increased the default number of possible suggestions to 30. But there could be less, depending on what the external sources return.

**Comment by lgalke** [comment]
It remains unclear why having the year at the beginning or at the end of the search string.
For now, we implemented filtering on the year after the suggestions have arrived.
