### ISSUE TITLE
Disable References button when there are no references

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#299]
When no references are available `!parts.length`, the `References` button should be disabled.

**Comment by chah3d** [comment]
One small concern, now it is impossible to manually add references, if non where added in the first place.

**Comment by lgalke** [comment]
Good point... @kleinann @LauraErhard, what's your take on this?

**Comment by LauraErhard** [comment]
When there are no references from crossref but a scan available we want this button to be disabled:
![2018-05-25 reference](https://user-images.githubusercontent.com/32642653/40534688-31b2a69c-6007-11e8-9d94-f16b84bcd2ac.png)

Without this button it should be possible to add new references after clicking on the scan view and then switching to the reference list.
![2018-05-25 reference2](https://user-images.githubusercontent.com/32642653/40534727-4bf66dfe-6007-11e8-963d-cdbcba955169.png)

Or are these two views connected?

**Comment by lgalke** [comment]
The `References` Button actually leads to all references of the resource (which may or may not come from CrossRef). You are right, when there is a scan there is a way to add refs but this is only possible when there is a scan. We could still have an electronic journal article which has no CrossRef references found...

**Comment by LauraErhard** [comment]
The electronic journal articles without CrossRef data have the bibliography available as pdfs. Therefore we can upload the pdfs and have a "scan" available then too.

**Comment by lgalke** [comment]
Okay, then we disable the button.
