### ISSUE TITLE
Scan View: Seperate Zoom and Scroll functionality

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#300]
The zoom and scrolling functionality is mixed up and a little confusing. It requires very careful mouse movements to use properly, which is not desirable.

We should think about putting a dedicated button for zooming. Or (in case it helps already) remove the external scrolling functionality and rely on browser scrolling.

**Comment by chah3d** [comment]
- [ ] integrate buttons (maybe top right in the header?)

![selection_096](https://user-images.githubusercontent.com/32481062/40543213-ab22fdda-6023-11e8-8d69-819d82935151.png)

**Comment by LauraErhard** [comment]
I thought maybe at the bottom?! Or both at first to check what feels better?
![2018-05-25 zoombutton](https://user-images.githubusercontent.com/32642653/40543445-b2a482e4-6024-11e8-90c9-743ef22731fe.png)
What's your opinion @zuphilip @kleinann @SylviaZander?

**Comment by LauraErhard** [comment]
I just saw the changes and the zoom works perfectly. 
We need the information on the scan to correct the search string and to compare with the suggestions, thus we need the scans on the same hight as the search/suggestions. Even if I zoom into the scan and then try to move the scan upwards I can't see all the references. Would it be possible to activate the scrolling again without enabling the "scroll zoom"? Or would it be possible to just move the scan further up with the cursor?! Or should the right side move down if we scroll down? Or is something else planned?!
