### ISSUE TITLE
Commit more then one link for en entry?

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#313]
For books, we often find more then one correct external suggestion from GVI now; they come from the different union catalogues and contain the identifiers of the respective database. 
At the moment, we can only commit one link for a bibliographic entry. If we want to link the produced bibliographic resources to our own library catalogue some day, we'd need the identifier of the SWB to do that. At first glance, it's not possible to see from which union catalogue an external suggestions originates.

If we imagine that libraries from all over Germany use LOC-DB, it would be desirable to have all union catalogue IDs in the database. I see two possibilities to get there:
1. Commit a link to any of the suggestions arbitrarily, and create an enrichment procedure that adds the relevant IDs afterwards (maybe via Culturegraph)
2. Commit links all the relevant suggestions that are shown. The link to all additional resources after the first would then imply a Same-as-relation between the linked records.

What do you think?

**Comment by lgalke** [comment]
We should keep in mind that our data model only allows a **single** link target:`references`.
The link target can of course have multiple identifiers, but it is still only a single resource, which reflects the (desired?) level of abstraction. We should probably look for ways to deal with this issue that preserves the single-resource idea.

From the technical perspective: Assuming, we would silently aggregate all identifiers of selected resources into one resource, we need to be aware that there can be conflicts in the other data attributes but also in the identifiers itself (different title, someone did select two resources that looked similar but are not, thus have different DOI values) and so on. 

As of now, one would select one target with the best set of meta-data available, and then enrich it with other known identifiers (which may come from other suggestions or elsewhere) and commit it. 

Afterwards it should pop up as an internal suggestion. If there is still some meta-data or identifer missing, it can be added. Of course this is an overhead which we could potentially alleviate, but for now it is, in theory, possible to construct a very-well linked citation target in our own database.

**Comment by lgalke** [comment]
Just to note, we could think of some light-weight merge strategy such as 'Migrate all identifiers from resource xy to the current resource". Once we have some sort of auto-completion (which is also useful to adjust the parent resource), we could re-use it and offer some sort of "Migrate all identifiers from: <text-input>", where it should be enough to enter the first few letters of the title of the other resource. We would need to further discuss that since it also relies on the internal search functionality and might require also some adaptions there.

**Comment by lgalke** [comment]
We implemented the 'migrate ids from another resource' via auto-completion.
