### ISSUE TITLE
Replace mystic float thresholds with top-K thresholds

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#315]
Replace mystic float thresholds inputs for internal and external suggestions with top-K threshold inputs.

**Comment by anlausch** [comment]
Just to make clear: Currently, this applies only to the external suggestions. Of course, this can be added to the internal suggestions too. I'll let you know when it changes.

**Comment by lgalke** [comment]
Thanks for the clarification, it would make sense if it behaved in the same way for internal suggestions.

**Comment by lgalke** [comment]
Its implemented and deployed.
