### ISSUE TITLE
Adaptions for precalculated external suggestions

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#316]
There will be a new service to retrieve the precalculated suggestions by entry id. When an entry is selected, this service should get called to give the first results. The other service, as we use it now, is then only used when the search string is changed.

**Comment by lgalke** [comment]
As soon as an entry gets selected, we first query for the **precalculated** external suggetions (fast). When you adapt the search string and press 'Refresh', a traditional query is executed (slow).

This behaviour is now implemented on the dev system, please feel free to test it @LauraErhard @SylviaZander @kleinann . For now, I only asserted that its technically working.

**Comment by LauraErhard** [comment]
I just checked a few examples and this doesn't work. If I click on an entry I only see the internal suggestions. After clicking the search button the external suggestions are loaded as always (not very fast).

**Comment by lgalke** [comment]
It was the same for me, I assumed that for the old-data the precalculation was never triggered. I was hoping that for newly ingested data, the precalculations would be triggered and it would yield them.

**Comment by lgalke** [comment]
An idea: if the precalculated suggestions returned an empty list `[]`, then query the usual suggestion engine (same as if you would press 'Refresh' afterwards).

**Comment by LauraErhard** [comment]
Okay, I will ingest more new data to check this.

And I don't quite understand what you mean with the 
> ...then query the usual suggestion engine (same as if you would press 'Refresh' afterwards).
Do you mean that I just have to click the search button again?!

**Comment by lgalke** [comment]
I meant we can automate this, when the precalculated suggestions give no results, we can trigger the normal external suggestions as fall-back.

**Comment by lgalke** [comment]
For now, we implemented this fall-back mechanism and deployed it also to demo.
