### ISSUE TITLE
Not_OCR_processed files can't be manually triggered?

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#318]
I saw that you emptied the database and uploaded a new file. This one bounced to the `not_ocr_processed` part. Without the scan button, there was a possibility (I think it was a little "play-button" besides the file link) to manually trigger the OCR process again. Is the functionality not there anymore? Or am I just not seeing it? We definitely need this functionality.

**Comment by lgalke** [comment]
We will check where this got lost.

**Comment by lgalke** [comment]
48f97a8 fixes that, is deployed by now.
