### ISSUE TITLE
Can't see a processed scan

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#319]
One upload was OCR processed, but I can't see the scan. The reference extraction seems to have worked, because I see a search string and if I click on references (in the agenda), I see a list of entries.
![2018-06-13 proxy error](https://user-images.githubusercontent.com/32642653/41349212-716d8628-6f0f-11e8-87c9-7271042ca3a7.png)

**Comment by anlausch** [comment]
Sorry, I assume that was me. Please feel free to report if this issue persists.
