### ISSUE TITLE
No Scans in demo/dev version?

### ISSUE THREAD

**Issue by aklein71** [locdb/locdb-frend#322]
Maybe its a known bug, but we can't open scans in the new versions.  Like this, we'd have to use the production version to show how reference extraction works.
Is there any way to get to the processed scans right now? Maybe in a way that I could just show them alongside the frontend in a different browser window?

**Comment by LauraErhard** [comment]
I can see the scans in both.
The dev version:
![2016-06-15 scan dev](https://user-images.githubusercontent.com/32642653/41480675-78240e8a-70cf-11e8-81f9-c7f5bc5c0fc5.png)

The demo version:
![2016-06-15 scan demo](https://user-images.githubusercontent.com/32642653/41480681-7d7211fc-70cf-11e8-8289-55e42f2f0e5c.png)

Do you just see the scan view without the scan?

**Comment by kleinann** [comment]
Okay, it seems to have been a problem with my very old netbook. Here at my usual office PC, I can see the scans in both places. Sorry for bothering you...
