### ISSUE TITLE
Pages in dev/demo frontend

### ISSUE THREAD

**Issue by aklein71** [locdb/locdb-frend#323]
For print resources, pages aren't shown as part of the normal metadata. They're only visible when I click on the Scan button.

**Comment by lgalke** [comment]
I re-added the page numbers and deployed it on dev. Please have a look at it and let me know whether we should also put a version with page numbers on demo. @anlausch for long-term, we might want to separate the embodiment page numbers from scan page numbers.

**Comment by kleinann** [comment]
The dev-version looks good, thanks!  Would be nice to have that on demo, too.

**Comment by lgalke** [comment]
It is deployed now also on demo.
