### ISSUE TITLE
Missing publication year and pages in external suggestions from Crossref

### ISSUE THREAD

**Issue by aklein71** [locdb/locdb-frend#324]
for doi 10.1016/0030-5073(69)90004-x which is a reference in
Dieckhoff, Martina: The effect of unemployment on subsequent job quality in Europe: A comparative study of four countries in: JOURNAL_ISSUE Acta Sociologica, volume 54, issue 3, SAGE Publications
uploaded in the Demo frontend, publication year and pages are missing in the external suggestion that is found when querying the doi in locdb. The data is there in Crossref, see
https://search.crossref.org/?q=10.1016%2F0030-5073%2869%2990004-x

I tried the other dois in the reference list of the above mentioned article. They're always lacking the pages.

**Comment by lgalke** [comment]
Considering pages, see #323, I will check for the year.

**Comment by lgalke** [comment]
The years are also properly displayed.
for DOI 10.1016/0030-5073(69)90004-x the external suggestion shows the year 1969.
