### ISSUE TITLE
Precalculated suggestions

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#329]
I just noticed two things.
First of all the precalculated suggestions don't have the source information (e.g. GVI, crossref,...) in the short view. Is this on purpose?

Then I noticed, that the precalculated suggestions deliver a slightly different list of suggestions compared with manually triggering the default search sting. Is the backend searching with a different string than the one I see in the frontend search?
Precalculated suggestions:
![2018-06-29 precalculated2 1](https://user-images.githubusercontent.com/32642653/42091449-b3b2afc0-7ba5-11e8-8f6b-b99858cdc28c.png)
Searching with the default search:
![2018-06-29 precalculated2 2](https://user-images.githubusercontent.com/32642653/42091454-b564a88c-7ba5-11e8-8609-947a079d9e71.png)

**Comment by LauraErhard** [comment]
I read #291 again and saw that the backend search stategy is a little different than the frontend. So the second part is clarified.

**Comment by lgalke** [comment]
Regarding the first part, we re-use the same display strategy for both. Is the `source` attribute also present for pre-calculated suggestions @anlausch ?

**Comment by anlausch** [comment]
The fix I provided some time ago was not deployed properly. Now, it should work.
