### ISSUE TITLE
Error: Something went wrong during commit

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#330]
I tried in the dev system:
1. Resolve
2. Activate "External"
3. Go to bottom and choose "Unemployment in early career in the UK A trap or a stepping stone?"
4. Click on "References"
5. Try to commit a link for any reference fails with `Something went wrong during commit: [object Object]` and in the browser console I see the error `The target bibliographic resource cannot be found.`.

**Comment by zuphilip** [comment]
The same error occurs in the demo system...

**Comment by lgalke** [comment]
Im trying to fix it right now. It seems to be a problem with the precalculated suggestions.

**Comment by lgalke** [comment]
```
Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"https://locdb.bib.uni-mannheim.de/locdb-dev/addTargetBibliographicResource?bibliographicEntryId=5b363802bb263415c64bf750&bibliographicResourceId=5b363804bb263415c64bf9cb","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://locdb.bib.uni-mannheim.de/locdb-dev/addTargetBibliographicResource?bibliographicEntryId=5b363802bb263415c64bf750&bibliographicResourceId=5b363804bb263415c64bf9cb: 400 Bad Request","error":"The target bibliographic resource cannot be found."}
```
The back-end says the target resource cannot be found. Even though, we do insert the resource before we try to commit the link. It is the same for external suggestions and precalculated suggestions, I cannot fully trace down why it works in the one case and it does not work in the other.

@anlausch do you have an idea?

**Comment by lgalke** [comment]
Do the precalculated suggestions already have an `_id`, but are not in the index? That could cause trouble, since when there was an `_id` already, we assumed that its also a valid linking target.

**Comment by lgalke** [comment]
If Im able to fix it tomorrow, I will dare to make another deployment on demo... I think its a major issue which would be worth the risk if it was resolved.

**Comment by anlausch** [comment]
Exactly as before you have to save the target before committing the link. The precalculated suggestions are treated the same way as the external ones.

**Comment by anlausch** [comment]
They are in a completely different collection to make the system work as before.

**Comment by lgalke** [comment]
But do they have an `_id` value despite being not usable as citation target?

**Comment by anlausch** [comment]
Yes, because mongodb automatically assigns _ids to everything you save. It needs them as unique identifiers. But, they belong to another collection, which the back end does not consider as stable (remember that the collection is restricted to a certain size), therefore, we do not want to use these ids. In the most extreme case it could happen that the user sees the suggestion but it gets at the same time deleted by the system.

**Comment by lgalke** [comment]
I see, we used the `_id` property to determine whether we need to insert the target resource first. If its present we didnt insert (internal suggestion), if its not present (external suggestion) we did insert the resource. Now we have another case where it is present but we still need to insert it. I tried to fix it already (always try to push the resource to the backend) but, so far, it did not resolve the problem.

**Comment by lgalke** [comment]
Ah guess I traced it down. The date that comes with the precalculated suggestions does not pass the validation test when committing it. 

```errors\":[{\"code\":\"INVALID_FORMAT\",\"params\":[\"date\",\"2002-01-01T00:00:00.000Z\"],\"message\":\"Object didn't pass validation 
```

I will fix it for now, but it would be long-time preferred if the data in the suggestions also satisfies the constraints ;)

**Comment by anlausch** [comment]
Maybe you can use the status property?

**Comment by lgalke** [comment]
That's how we did it long time ago, but there were also some corner-cases in which it didnt work reliably, that's why we went to testing the `_id`. :/

**Comment by lgalke** [comment]
When I remember correctly, the problem was with ToDo items that are flagged 'EXTERNAL' because they hold web data. Is it still the same, or can I safely check for `status === 'EXTERNAL'` to determine whether it is a suggestion that is not yet usable as title?

**Comment by anlausch** [comment]
This is surprising as the back end uses the format everywhere. Thanks for looking into the follow-up issue.

**Comment by anlausch** [comment]
Your right not to use this property. I can check tomorrow if necessary, as I have no option to code right now. I would suggest you implementat the workaround as discussed and I provide a proper solution, maybe just introducing another enumeration value 'SUGGESTION'. Would that be feasible?

**Comment by lgalke** [comment]
Yes, something like that would be great.

**Comment by lgalke** [comment]
I'll also now stop and have another look tomorrow. The workaround unfortunately doesnt completely solve the problem. Still, I get `target unknown` errors even if I successfully use the `save` endpoint to store the suggestion before (and wait for successful response).

**Comment by zuphilip** [comment]
FYI this is not breaking the demo on Monday. I will just not click on "Commit" and then none sees that there is a potential error. It is important to fix that issue, but you can also continue on Monday on that.

**Comment by lgalke** [comment]
@anlausch another feasible solution: do not send the `_id` property within the precalculated suggestions, then I could rely on it again.

**Comment by lgalke** [comment]
I fixed it right now by setting `._id` to `undefined` when we retrieve the precalculated suggestions.

**Comment by lgalke** [comment]
It is deployed on dev right now. If there are no unexpected other bugs, I could also deploy on demo tonight. @zuphilip please let me know whether you would agree having this version also on demo.

**Comment by lgalke** [comment]
Deployed on demo, can roll-back if necessary.

**Comment by zuphilip** [comment]
Thank you! Looks good so far.
