### ISSUE TITLE
[Agenda] Don't repeat information about container resource in all children

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#331]
Currently, in the agenda view the full information of the container resource is repeated for each child. Besides that the container resource itself is also present with all its information, e.g.

![agenda-repetition](https://user-images.githubusercontent.com/5199995/42100609-f4786d36-7bc0-11e8-992e-49db1529aca0.png)

This repetition is not useful and will fill up the agenda view more. I suggest to simply not repeat anything from the container resource. In the example that would lead to 

![agenda-no-repetition](https://user-images.githubusercontent.com/5199995/42100840-9ed5b914-7bc1-11e8-8d32-4e9c59c83714.png)

Respectively after entering the title and author information:

![agenda-no-repetition2](https://user-images.githubusercontent.com/5199995/42101227-cd14a2c6-7bc2-11e8-9e81-2db1da096051.png)

**Comment by lgalke** [comment]
We also had this in mind. In the design session, we, however, decided to start with showing the information in both places but we can reconsider this. What are your thoughts on this @kleinann @SylviaZander @LauraErhard  ?

**Comment by SylviaZander** [comment]
I like the view with the separate information. Maybe you could colorize the container title slightly darker, that would make the hierachy even clearer

**Comment by kleinann** [comment]
As you said, Lukas, we didn't consider this as a primary issue. But maybe it makes the whole view a little bit more compact. I would rely on the opinion of our practicioners here.

**Comment by LauraErhard** [comment]
We don't need the information from the parent in the child resource. As said before it just fills up space.

**Comment by lgalke** [comment]
Alright, we will change that soon.

**Comment by lgalke** [comment]
We changed this already some time ago.
