### ISSUE TITLE
[Agenda] Don't show disabled buttons

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#332]
Currently, all three buttons are always shown in the agenda view for each entry, but some are disabled because they this functionality is not applicable. There is no IMO no need to show disabled buttons with no functionality.

I would suggest to either a) delete the disabled buttons (resp. not show them), or a) set the visibility to hidden.

Option a:

![agenda-delete-disabled-buttons](https://user-images.githubusercontent.com/5199995/42102563-8c46254a-7bc6-11e8-8106-9b1bfcc46490.png)

Option b:

![agenda-hide-disabled-buttons](https://user-images.githubusercontent.com/5199995/42102577-940440dc-7bc6-11e8-8e43-fd34d98805b8.png)

**Comment by lgalke** [comment]
Thanks @chah3d, its deployed right now.
