### ISSUE TITLE
Author Identifiers

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#336]
- [x] Allow to view and edit author identifiers
- [x] Preferably without overloading the UI, e.g. in a modal
- [x] Properly store the updated identifiers
- [x] Add two small buttons to shift an author, or a contributor, up and down the list
- [x] Minor adjustments

**Comment by lgalke** [comment]
We can start with [ORCID](https://orcid.org/) and maybe `GND` id? @LauraErhard @SylviaZander @kleinann

**Comment by LauraErhard** [comment]
I just tested this.
It looks like there is no check if the input is valid.
Can you implement a validation check?
Information about the ORCID format:

> The ORCID iD is an https URI with a 16-digit number that is compatible with the ISO Standard (ISO 27729), also known as the International Standard Name Identifier (ISNI), e.g. https://orcid.org/0000-0001-2345-6789
Initially ORCID iDs will be randomly assigned by the ORCID Registry from a block of numbers that will not conflict with ISNI-formatted numbers assigned in other ways. ORCID iDs always require all 16 digits of the identifier; they can not be shortened to remove leading zeros if they exist.

See: https://support.orcid.org/knowledgebase/articles/116780

I'm not so sure about the GND-ID. I just checked a few examples and it seems like the GND-ID always has 9 or 10 digits, without special characters. But maybe @zuphilip @SylviaZander @kleinann know more about this?!

On top of that the filling out is not very smooth at the moment. I don't really like the pop up window, but right now I can't think of a better way to implement this. 
It would be nice, if I didn't have to click on `add identifier` to open a new field. Could you show an empty row from the beginning?
Right now:
![author_identifier1](https://user-images.githubusercontent.com/32642653/44467462-33ec7200-a623-11e8-9a44-4e3e8a7d4f3a.png)

Would be better:
![author_identifier2](https://user-images.githubusercontent.com/32642653/44467471-3b138000-a623-11e8-8e53-71a56b6efa7c.png)

It would also be nice if the cursor is already in the empty field so we can directly paste the number into the field.

**Comment by lgalke** [comment]
Having an initial empty field is a good idea. @chah3d can take care of it. We need to keep in mind to not add any identifier that is empty or has an empty scheme then.

Regarding the validation checks, of course we can add validation checks when the restrictions are well-defined. For ORC-IDs it should be always 16 digits, but I've seen at least one ORC-ID that has a literal `X` as the final character, which is of course, not a digit. That's why we are quite cautious about that. Still, I agree that it would be a good extension to have such validation checks (also for the identifiers on resource-level).

@zuphilip do you, by occasion, have already a set of regex for some of the identifier schemes (both for contributors and for resources), else we need to figure them out depending on the rules. But then again, we could make use of some pointers to well-defined formats for the identifier schemes.
For reference, I pasted a list of all the identifier schemes we consider at the moment:

```
export enum identifier {
  isbn = 'ISBN',
    issn = 'ISSN',
    swb_ppn = 'SWB_PPN',
    urlSbw = 'URL_SWB',
    olc_ppn = 'OLC_PPN',
    zdb_ppn = 'ZDB_PPN',
    zdb_id = 'ZDB_ID',
    ppn = 'PPN',
    doi = 'DOI',
    lccn = 'LCCN',
    gndId = 'GND_ID',
    swbGndId = 'SWB_GND_ID',
    oclcId = 'OCLC_ID',
    uri = 'URI',
    urlCrossref = 'URL_CROSSREF',
    gviId = 'ID_GVI',
}
```

**Comment by lgalke** [comment]
It is currently being deployed on all systems. Shifting works now, buttons are beautiful, and the identifiers are, of course, shifted along with the authors.
