### ISSUE TITLE
Mapping between scans and entries

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#341]
We discovered another related problem:
At the moment, the front-end has access to

- `scans` *holds the list of scans (may be more than one for a single document)*,and
- `entries` *holds the info on extracted references and bounding boxes*

**But** there is no mapping between scans and entries. We do not know, from which scan a specific entry is derived. 

Two solutions that would be feasible:
- [ ] Store in each `entry.ocrData` from which scan it is derived.
- [ ] Create an `entries` property to the `scans` level, such that we can access them individually via `scans[i].entries`. This way, we would not clutter the global entries list (which holds for instance also the data retrieved from crossref plus already those entries that are already manually indexed)

We can discuss, which one is more suited. For the front-end both options would be fine. Maybe the second one is slightly preferred.

Guess we need to make a full-path through all components (1. reference extraction, 2. backend, 3. frontend)

@rtahseen is it possible to derive that kind of information from the results you supply to our back-end already now?

**Comment by rtahseen** [comment]
@lgalke The results returned to the back-end already contains the information regarding the relevant scan image from which the results were extracted.
![image](https://user-images.githubusercontent.com/14193937/44019083-13ba61c8-9ede-11e8-8577-62c58baa63f7.png)
You can find an attribute "fname" which contains the name of the relevant scan.

**Comment by lgalke** [comment]
Thanks, we will check whether this gets passed through to the front-end.

**Comment by lgalke** [comment]
@rtahseen just to make sure: the coordinates are then relative to the respective slice of the image?

**Comment by rtahseen** [comment]
By slices, you mean that specific page?
If a pdf file has multiple pages then the system will break down a single pdf file into its respective pages and then coordinates are computed for each specific page separately as they are then considered as separate files. For example   sample.pdf --> Page1.jpg, Page2.jpg ...

**Comment by lgalke** [comment]
Ah very good :+1: that is what I meant. Then it can indeed be an explanation for the overlapping boxes we encountered lately #340

**Comment by lgalke** [comment]
@anlausch, we would expect that the `getToDoBibliographicEntries(scan_id)` service returns only the BibliographicEntries that are on the scan with `scan_id`. Could you please verify that this is the case? It seems like it is returning the entries of all scans instead of only the correct one (the correct slice of the uploaded image).

**Comment by anlausch** [comment]
@lgalke I might have misunderstood the issue, but I checked and I think that everything is working as expected. For example:

https://locdb.bib.uni-mannheim.de/locdb-dev/bibliographicResources/5b694667af1eb41e753a0dfc

returns the whole br with all bes and all scans. Each be is then associated with a scanid, e.g.

```
    {
      "bibliographicEntryText": "Osterkamp, Rigmar (Hg.): Auf dem Pritstand: Ein bedins ung sloses Grundeinkommen fiir Deutschland?, Baden-Baden 2015 (ZEP-Son- derband 7)",
      "ocrData": {
        "coordinates": "99 1525 1091 1637",
        "title": "(Hg.): Auf dem Pritstand: Ein bedins ung sloses Grundeinkommen fiir Deutschland?,",
        "date": "2015",
        "marker": "4.",
        "journal": "",
        "volume": "",
        "_id": "5b6d7a94e70b9b0a2d8f913e",
        "authors": [
          "Rigmar Osterkamp"
        ]
      },
      "scanId": "5b694716af1eb41e753a131d",
      "scanName": "5b694667af1eb41e753a0e06-2.jpg",
      "status": "OCR_PROCESSED",
      "_id": "5b6d7a94e70b9b0a2d8f913d",
      "identifiers": [
        
      ]
    },
```
But, when I call https://locdb.bib.uni-mannheim.de/locdb-dev/getToDoBibliographicEntries?scanId=5b694716af1eb41e753a131b

I get only the bes for a single scan. Can you recheck and let me know in case there is another problem, please?

**Comment by lgalke** [comment]
Yes, I will double-check :) Thanks for clarifying!

**Comment by lgalke** [comment]
It seems to be fine right now, thanks for double-checking. It was presumably an issue with our own code: after a clean re-implementation of the scan inspector, everything seems to be working as expected.
