### ISSUE TITLE
Back-end down?

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#346]
```js
Object { headers: {…}, status: 503, statusText: "Service Unavailable", url: "https://locdb.bib.uni-mannheim.de/locdb/getToDo?status=OCR_PROCESSED", ok: false, name: "HttpErrorResponse", message: "Http failure response for https://locdb.bib.uni-mannheim.de/locdb/getToDo?status=OCR_PROCESSED: 503 Service Unavailable", error: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n<hr>\n<address>Apache/2.4.25 (Debian) Server at locdb.bib.uni-mannheim.de Port 443</address>\n</body></html>\n" }
```

Also https://locdb.bib.uni-mannheim.de/locdb/docs/ is not accessible manually.

**Comment by zuphilip** [comment]
I guess that they are not running. There was a restart of the server 2 days ago... I try to look how we have to restart these services now.

**Comment by lgalke** [comment]
Ah that'd be great. Anne has a [description](https://github.com/locdb/loc-db) of how to start the services.

**Comment by zuphilip** [comment]
Okay, we managed to start the services again, well I hope we did everything correct. Can you please test a few things to be sure that it is the same as before?

**Comment by anlausch** [comment]
Thanks to @zuphilip I see the back end running again. We are currently discussing about the best way to start everything on reboot. Therefore, I will close the issue.
