### ISSUE TITLE
online-button for entries without metadata

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#349]
If we ingest pdfs via DOI, there is no metadata available:
![articleswithoutmetadata](https://user-images.githubusercontent.com/32642653/44467687-ca209800-a623-11e8-81df-918c0c1631ef.png)
It would be really helpful, if you could create a DOI-URL on the basis of the file name (file name is e.g. 10.1111j.1468-4446.2010.01345.x.pdf and you would have to create the URL https://doi.org/10.1111/j.1468-4446.2010.01345.x in the backend) and then show the online button. This would make it easier for us to check the source and help with the editing of the entry metadata. Would this be possible?

**Comment by lgalke** [comment]
The Identifier is present, so we can see what we can do in the frontend. Thanks for the hint.

**Comment by lgalke** [comment]
Are the first 6 digits (including the dot in-between) always separated by `/` from the remainder of the DOI?

**Comment by lgalke** [comment]
I implemented the conversion according to your example, but this **will** go wrong if we have to deal with differntly formed DOIs (that already contain the forward slach at position 7, or are already prefixed).
Let me know when you encounter such cases, or when you can provide a reference to the specifications.

**Comment by LauraErhard** [comment]
The articles we upload via DOI never have the `/` because windows doesn't allow slashs in file names. And we never prefixed them with `https://doi.org/`. This shouldn't make any problems.
But I just checked our data and noticed, that sometimes we substituted the `/` with a `.` but this was only done for a few files and we can easily change this before uploading.

In addition, I just uploaded a new article and I don't see the online button. Is it deployed on dev?

**Comment by LauraErhard** [comment]
Oh correction, I see it now. But not with every article. I will check later, if I notice a pattern.

**Comment by lgalke** [comment]
Should be, maybe reload. The button is now labeled `DOI` before we had a rather strange heuristic of searching for any identifier that is linkable and chosing the first one. Now we have always 'DOI' and 'URL_CROSSREF', let me know if you need more.

**Comment by lgalke** [comment]
I inspected https://www.crossref.org/blog/dois-and-matching-regular-expressions/ again for that issue and it seems like the number of digits after the first dot is flexible (between 4 and 9) so I need to adapt. Also it says that after that, a "slash" should follow. Of course its an issue when Windows doesnt allow such filenames but the DOI property in our database comply to the correct format, dont you agree?

**Comment by lgalke** [comment]
For now, I changed it back, which means we assume that the DOI in our data complies to standards. We only prefix it with either `https://` or `https://doi.org/` if necessary

**Comment by LauraErhard** [comment]
I just checked and while ingesting the data, we can adjust the automatically filled in DOI. Therefore we could manually check for each journal where the slash has to be (the wikipedia entry says: "The prefix identifies the registrant of the identifier", therefore the slash placement should be the same for each article from a specific journal). This would concern 58 journals, but for a lot of them it is quite easy (for a human) to see where the slash should be, because after the digit follows a letter or something else. You would then only need to generate the prefix `https://doi.org/`. I think this would be good enough for now, because it is a limited amount of journals we have to treat this way.
