### ISSUE TITLE
OCR boxes 

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#350]
I just checked the scan inspector and I noticed two things.
If I click on a scan in the agenda and look at the scan, the current reference is not marked as selected (=red box instead of blue). The box only changes colour if I click on it.
![boxes1](https://user-images.githubusercontent.com/32642653/44469806-95630f80-a628-11e8-810e-79cb5c49b0b9.png)
And the second thing I noticed is that if I switch to the second page, the same reference is selected as in the first page. I would expect that by switching to the next page a reference from this page is automatically selected.
![boxes2](https://user-images.githubusercontent.com/32642653/44469895-bc214600-a628-11e8-9495-3924a9dba648.png)

**Comment by lgalke** [comment]
Thanks, will take care tomorrow :)

**Comment by lgalke** [comment]
It is fixed by now (deployed on dev)

Btw, when you switch between the Scan View and the List View, the same entry stays selected, such that it is easier to compare when in doubt. Hope that helps.
