### ISSUE TITLE
PDFs in waiting can't be triggered manually

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#351]
As I mentioned in #339

> And a negative side effect of not showing the initial pdf is that if the scan doesn't get processed, I can't manually start the OCR process again, because the "scans"-button is not available. Can you suppress the initial pdf only when the scan is successfully processed? Or can you position the little "play"-button, which triggers the new OCR processing, somewhere different?!

![waiting](https://user-images.githubusercontent.com/32642653/44470483-25558900-a62a-11e8-9cbb-5f553e06ee8a.png)

Is there any news on this?
Maybe we should also think about automatically triggering another OCR process?! Or is this not possible/practical?

**Comment by lgalke** [comment]
Thanks. We will fix it soon :+1: 

>Maybe we should also think about automatically triggering another OCR process?! Or is this not possible/practical?
Yes we can think about it. However, it is not a good idea to implement such repeating jobs in the front-end. Also in the back-end, it can become a little tricky:
- They failed for a reason, why should it be different in a second run?
- If we triggered all at once, every 2 hours or so, it is likely that the OCR component gets too much workload and therefore fails again.

So some careful scheduling of one item per hour would be probably feasible, but I'm concerned that it could be much effort for rather little gain. What's your take on this @anlausch ?
