### ISSUE TITLE
New Detector Service

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#355]
dfki reference extraction interface:
- large files (e.g. 4 MB) always get a proxy error after 5 minutes
`Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /fileupload/.
Reason: Error reading from remote serve`
- detection with Grobid looks promising

locdb frontend:
- switching between Grobid and ParsCit references needs to be integrated into the frontend
- large files (e.g. 4 MB) don't get processed and bounce to the `waiting` part
- sometimes processing takes a lot of time (can't yet pinpoint when)

**Comment by lgalke** [comment]
> switching between Grobid and ParsCit references needs to be integrated into the frontend

We could tackle this in two ways:

a. Via some user preferences
b. Run both, filter at runtime.

**Comment by rtahseen** [comment]
I am working on making all processing requests asynchronous. It will eliminate this proxy issue.

**Comment by anlausch** [comment]
> > switching between Grobid and ParsCit references needs to be integrated into the frontend
> 
> We could tackle this in two ways:
> 
> a. Via some user preferences
> b. Run both, filter at runtime.

I decided for b) as I think that it offers a better experience to the user, when he/she can dynamically switch between the different detection methods. But, we have to keep in mind, that in this case, we can not set the BR to 'valid' as probably never all BEs in the list (remember that now we'll have duplicates) will be linked. Should this be done manually? Or is the better way to go, to decide this over some preferences? @lgalke let me know what you think

**Comment by lgalke** [comment]
Guess it would be the best to let the librarians decide when the a reference list is completely linked, i.e. offer a button. 'valid' BRs will not be displayed again in the ToDo agenda. Would this be fine? @LauraErhard

**Comment by lgalke** [comment]
We have decided for `b)`. The filtering is implemented in the front-end. We also have a button to fully validate the resources.
