### ISSUE TITLE
pages increase after upload

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#357]
Something curious just happened.
I uploaded a chapter pages 94-95, but after checking `scans `suddenly there where three pages. I checked the original pdf and it really is just two pages long.
![3pages](https://user-images.githubusercontent.com/32642653/45218701-d6098c80-b2a8-11e8-8a9d-dd6c82d9f1c2.png)
The first page is listed twice. And on the first page one box is available but the search field only appears if I click on the box again. On the second first page is the same box and the search field is available as expected.
First page:
![first page](https://user-images.githubusercontent.com/32642653/45218888-5fb95a00-b2a9-11e8-8fb7-7bab96eb87ef.png)
Second first page:
![first page second](https://user-images.githubusercontent.com/32642653/45218895-65af3b00-b2a9-11e8-88ec-f6d7f62d6c62.png)

 What happened there?

**Comment by anlausch** [comment]
After upload, the scan is send to the reference detection and there it is processed (splitted, .. . Therefore, we then have another or even multiple other scans. The references are computed on the "new" scan, which is why the detected references only relate to this one. The back end changes the status of the original scan to "OBSOLETE". The front end should probably not show this scan. I guess that the issue relates to this, but I will check in order to make sure.

**Comment by lgalke** [comment]
We actually do filter for obsolete :+1: will check in more detail after my vacation.

**Comment by LauraErhard** [comment]
I looked at this again and wanted to mention, that the first scan is not the original scan with 2 pages. It is just one page. Don't know if this helps with tracking down the problem.

**Comment by lgalke** [comment]
Could you check whether this disappears after a fresh reload, please? It could be possible that there are some left-overs otherwise. Apart from that, I don't have a clue at the moment where this additional scan could come from.

**Comment by SylviaZander** [comment]
I just uploaded the example with the two pages (94-95) again and this time the pages are shown correctly. We must probably continue to watch if it occurs again somewhere else ...

**Comment by lgalke** [comment]
While fixing #364 , I observed only correct amount of pages. Feel free to re-open if the bug occurs again.
