### ISSUE TITLE
Installation depends on deprecated packages and other warnings from npm

### ISSUE THREAD

**Issue by stweil** [locdb/locdb-frend#361]
Installation protocol:

    npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
    npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
    npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
    npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
    npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
    npm WARN deprecated buildmail@4.0.1: This project is unmaintained
    npm WARN deprecated uws@9.14.0: stop using this version
    npm WARN prefer global node-gyp@3.8.0 should be installed with -g
    [...]
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/chokidar/node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/@angular/compiler-cli/node_modules/chokidar/node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm WARN angular2-hotkeys@2.1.2 requires a peer of rxjs@^5.5.0 but none was installed.
    npm WARN ngx-accordion@0.0.17 requires a peer of @angular/core@^2.0.0 but none was installed.
    npm WARN ngx-popover@0.0.16 requires a peer of @angular/core@^2.0.0 but none was installed.
    npm WARN @ngtools/webpack@6.0.8 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but none was installed.

**Comment by lgalke** [comment]
Thanks @stweil . As long as it's *only* warnings, we can safely ignore. I am trying to keep our dependencies as well as the output of `npm audit` as clean as possible (vulnerabilities), but not all of the vulnerabilities can be trivially fixed and new ones are discovered quite frequently.

**Comment by lgalke** [comment]
In PR #367, we got rid of all vulnerabilities. The warnings can typically be ignored, some of them like hoek should also be resolved by upgrading karma to 3.0. In principle, those mentioned deprecation warnings are all not caused by direct dependencies. So there's not much we can do about it except for keeping our direct-dependencies up-to-date.
