### ISSUE TITLE
Suggestions: filter & list of results

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#365]
I just checked out the different possibilities to filter the suggestions and their impact on the list of results and noticed a few things we should discuss more.
 
![filter](https://user-images.githubusercontent.com/32642653/45760213-d8b19d80-bc29-11e8-9c15-055fc71d946a.png)

1. First of all I think the number of internal suggestions should be preselected to 5 instead of 1. By experience (while we produced real data in the production system) the right internal suggestion was not always the first on the list of internal suggestions. Maybe with all the changes these last few months this got better, but to be safe, I would suggest preselecting it to at least 5. I think this should not be a huge change if we want to change it back to 1 in the future?!
2. Second of all I noticed that if I want to change the number of suggestions after a search I always have to start a new search. Does the backend only save the selected number of suggestions for each search so that we really need to give the search new parameters or does the backend have more suggestions available and we only see 10? If we have more suggestions in the backend it would be faster for us if we could activate the filter independently from a new search. But I don’t know if this is feasible/ possible?!
3. The source filter sometimes shows every possible source even if the list of external suggestions only has suggestions from e.g. crossref:
  
![filter_nach_source](https://user-images.githubusercontent.com/32642653/45760226-e1a26f00-bc29-11e8-8831-8a7b42105882.png)

After seeing all the sources available I had the idea to select the top 10 of each source when picking the source in the filter (not only filter the 10 suggestions we already see). This would be very helpful in cases in which we are pretty sure for example the SWB has the right suggestion, but we don’t see any suggestion from the SWB in the list. This would maybe save us the time to change the number of external suggestion, because we would have 10 suggestions for each source which equals 40 suggestions. We would of cause keep the `all` as standard and would keep the ranking there because in a lot of cases we already see the right suggestion there. I have no idea if this would demand excessive work from your side or if it is even useful, but I just wanted to start a discussion about this. 

4. As already questioned in #114 I am not so sure what the contained filter should do:

> I just now checked this new feature out. And I have a question. What does the "contained" filter? It seems that the contained filter only shows external suggestions and standalone only shows internal suggestions. Am I right with this assumption? And if so, why is it called "contained" and "standalone"?
>  
> Or is it something completely different?

**Comment by lgalke** [comment]
> After seeing all the sources available I had the idea to select the top 10 of each source when picking the source in the filter (not only filter the 10 suggestions we already see). This would be very helpful in cases in which we are pretty sure for example the SWB has the right suggestion, but we don’t see any suggestion from the SWB in the list. This would maybe save us the time to change the number of external suggestion, because we would have 10 suggestions for each source which equals 40 suggestions. We would of cause keep the all as standard and would keep the ranking there because in a lot of cases we already see the right suggestion there. I have no idea if this would demand excessive work from your side or if it is even useful, but I just wanted to start a discussion about this.

This one is something for @anlausch, since at the moment, we can only query the external suggestion regardless of the source. What do you think?

**Comment by lgalke** [comment]
@LauraErhard , we have fixed the "container vs stand-alone" filter. The desired use was to separate resources that do not have a "parent" (stand-alone) from resources which are actually a pair of resources (resource A **in** resource B). @kleinann requested this kind of filtering. I am just deploying the updates to dev.

**Comment by lgalke** [comment]
Anne raised the number of precalculated suggestions to 30 (#293) and they should also be visible in the front-end (assuming show-more is pressed). Regarding point 3, we incrementally fill the valid choices based on the available suggestions. While testing, I found it to work correctly. Maybe there was some hard coded values in there back-then. Let me know if there are still some special cases, which we would need to trace down.

Feel free to re-open if you feel something is not yet addressed.
