### ISSUE TITLE
Create new journal issue

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#371]
How do I create a new journal issue that is needed for linking?
Example:
![grafik](https://user-images.githubusercontent.com/33151732/46540424-963ec080-c8b9-11e8-8834-20f499f1b6a1.png)

The journal article cant't be found in the external suggestions. The issue does not exist. When I choose "New resource from reference metadata" the form does not show the appropriate data fields for a journal issue (no specification of the numbers - whether it's volume number or issue number).

**Comment by kleinann** [comment]
Actually, it's volume 35 (and issue 3, but this is not in our data). The first mentioned number is usually the volume. But yes, in principle, that's what we need.
As for contributors and identifiers, I'm not sure what the difference would be. I'd hope that when creating a new issue for a journal for which we already have other issues in the database, we'd be able to use one of the existing issues and just change the number. But maybe I didn't get your point.

**Comment by lgalke** [comment]
We have pulled the whole `partOf` logic out of the actual resource form #376 .
Now, one can:

1. Toggle between viewing the resource's own metadata and its container's metadata
2. Disconnect the resource from the container and assign **or create** a new one.

The changes are just now being deployed to both dev and prod. There is one issue remaining #377, which makes it impossible to persistently clear the partOf field, but I presume Anne will take care of that, soon. 

Please feel free to try it out.
