### ISSUE TITLE
uploads don't switch to ready (dev)

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#374]
I just uploaded 3 different chapters (dev) but they don't seem to switch to the `ready` part. Agendash shows that everything was completed. Is there a bug right now that prevents the resources to switch categories?
![agendash](https://user-images.githubusercontent.com/32642653/46616097-15caca80-cb1a-11e8-8121-2df28a24edc8.png)

![dev](https://user-images.githubusercontent.com/32642653/46616099-16fbf780-cb1a-11e8-9a6c-1f7fb8869a06.png)

**Comment by anlausch** [comment]
Can you try again?

**Comment by anlausch** [comment]
https://github.com/locdb/loc-db/commit/91d51905c3c0a7e7f06bd4522f93a45c31d93eec feel free to open again

**Comment by LauraErhard** [comment]
Still doesn't work. We uploaded a scan maybe an hour ago and it is still `in queue`.
