### ISSUE TITLE
Number of pages of monographs

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#375]
I just noticed that with monographs we don't have page numbers available, which leads to this (in the agenda view):
![pagenumber](https://user-images.githubusercontent.com/32642653/46738737-42f4b580-cc9f-11e8-9931-12c8f36823ed.png)
This is again quite confusing. Can you maybe check if page numbers are available and if not just count from 1 upwards. Then we can easily differentiate between the different scans again. Or do you have another idea?

**Comment by lgalke** [comment]
Thanks for reporting. We cared for other special cases but missed that one. Will fix asap

**Comment by lgalke** [comment]
![image](https://user-images.githubusercontent.com/3439126/46740388-ff03af80-cca2-11e8-993b-c2f76f79a5ff.png)
Is that better?
