### ISSUE TITLE
filter for suggestions

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#379]
I just linked a few references and I noticed, that the year filter works nicely but it would be even nicer if the years would be sorted in chronological order. Right now it looks a bit messy and we lose time searching for the right year.
![year_filter](https://user-images.githubusercontent.com/32642653/46802740-82360b80-cd5e-11e8-8c2a-cde8d5907c52.png)

And I noticed that when I set a filter it stays put even if I switch to the next reference. We hardly ever have the use of the same filter twice in a row. Could you reset all filters to "all" after clicking a new reference?

**Comment by lgalke** [comment]
Thanks for reporting. I noticed that the old values from previous searches were also not properly cleaned up. This is now fixed, and also selected filters are not stored for the next entry. We also introduced a consistent ordering for all the possible filters.
