### ISSUE TITLE
container metadata doesn't get stored

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#380]
I just linked a few references. I noticed that there is a problem with journal articles (and likely every resource with a container).
I just committed a journal article and then noticed, that the journal is not in the short view (although I'm sure I migrated the container before the article) :
![first](https://user-images.githubusercontent.com/32642653/46815231-c9ca9080-cd7a-11e8-970f-b442bc58d97d.png)
Then I doubted myself and tried to connect the issue again. I found the right journal issue with the `link to container` resource and submitted that again. I saw the issue in the short view:
![second](https://user-images.githubusercontent.com/32642653/46815387-20d06580-cd7b-11e8-8b64-21c11461ae79.png)
Then I switched to `switch to own metadata` and submitted that for good measure again. Then I noticed that the message which tells me to connect the container first is still there. After clicking `fix it` the following error occurs:
![third](https://user-images.githubusercontent.com/32642653/46815587-7442b380-cd7b-11e8-902e-82ecb0f191d7.png)
After clicking `okay` and clicking on a different reference and back again to my example every change is gone.

What's the problem? Do I do something wrong or is there a bug?

**Comment by lgalke** [comment]
Thanks for the extensive testing, I will try to reproduce the issue tomorrow and figure out what is going wrong. Conceptually the functionality of linking resources to their containers should be completely handled by the section above the type field. Changes are applied (and sent to the backend) when the "Fix it" button is pressed. Please note that we fully moved this functionality out of the actual form as it can get quite complex and deserves dedicated controls (we not only change partOf anymore, but it is now also possible, to view and edit the container's meta-data before linking them together).

In the case you described, this operation of storing the link (read: between resource and container) to the back-end did not succeed. So far I experienced this only when I wanted to intentionally remove a container without replacement. In this case the validation checks failed (See #377 ). I will investigate tomorrow if we have a similar case here, despite you actually did select a valid container.

**Comment by lgalke** [comment]
It was a problem of the date conversion (once again).. we now do change **only** the partOf property in the 'Fix it' procedure. This way, there won't be any trouble (as long as both resources have are internal / have been migrated).
