### ISSUE TITLE
pressing refresh on prod leads to dev

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#381]
After some confusion I finally realised that if I click on `refresh` (F5 on windows) in the production system I always get forwarded to the development system. Why does this happen? Is there a purpose for this?

**Comment by lgalke** [comment]
Thanks for reporting, good catch. We need, of course, a different .htaccess file for development and production. I just deployed a fix. Will leave the issue open until we have integrated it into our deployment scripts such that it will not happen again.
