### ISSUE TITLE
search for container (autocompletion) tedious

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#382]
When I want to`link to a container` and search for a journal the view is pretty unhelpful. Would it be possible to see the journal title and the volume number as well? Right now I only see the issue number and the publisher which is really not that helpful.
![autocompletion](https://user-images.githubusercontent.com/32642653/46870635-6d757880-ce2f-11e8-8386-e1b414bd418c.png)

**Comment by lgalke** [comment]
Is this any better? 
![image](https://user-images.githubusercontent.com/3439126/46872649-08248600-ce35-11e8-85f8-c8cc2cecf45b.png)
