### ISSUE TITLE
problems with container resources

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#392]
I noticed a few things about the container resources.

1. If I search for a journal (either in `ready` or `browse`) I always see this:
![suggestions_container_one](https://user-images.githubusercontent.com/32642653/47022793-8f883700-d15e-11e8-96ff-66b7acc4e708.png)

I think this is something similiar to #382. It would be nice to see journal title, vol., issue.

2. When I click on one of the issues as seen above, I get this:
![suggestions_container_empty](https://user-images.githubusercontent.com/32642653/47022784-88f9bf80-d15e-11e8-9586-d9d840afa6e0.png)

As you can see, you see nothing. There is not even the issue number visible. Only in one case I see journal title, vol, issue (I recently linked an article from this journal issue, maybe because of that it got updated?).
If I search for the same journal in the `link to container`, I see all the data:
![autocompletion_container](https://user-images.githubusercontent.com/32642653/47023034-14735080-d15f-11e8-86dd-7d79cb219c77.png)
(I assumed these are the same issues as I found with the different search)
What is going on?

3. I searched for an article and a suggestion from crossref was the right suggestion. I clicked `edit` and noticed that the article was already connected to a container. I looked at the container metadata and saw empty fields.
![suggestion_con](https://user-images.githubusercontent.com/32642653/47023577-39b48e80-d160-11e8-80af-67a39cbc04ce.png)
Then I remembered, that I linked a different reference to this journal earlier and decided to check if I could find the right issue. So then I had to `disconnect from container` and then `link to container` to start the autocompletion where I promptly found the right issue. Long story short I wanted to ask if the container metadata is always created from the source metadata without checking if the container already exists in the database? It seems that way and this is problematic because we could unintentionally create the container a few times.

4. The searching with the autocompletion function is very nice right now. But as I was searching the issue from above I noticed that I can search for issue number and volume number. However instead of eliminating the issues which don't have the number present it only shows me the numbers in bold. 
![autocompletion_search](https://user-images.githubusercontent.com/32642653/47024744-9a44cb00-d162-11e8-878c-8fe5909e1c94.png)
If I assume correctly we see only 10 results each search and if we have more than 10 issues from the same journal I wouldn't see all of them. Could we limit the results to only show me the issues with the right numbers? Or rank the results on how many numbers are correct? Or maybe you have a different idea?

**Comment by LauraErhard** [comment]
I just saw that 1 & 2 are already documented in #370

**Comment by lgalke** [comment]
> If I search for a journal (either in ready or browse) I always see this:

Yes, we apparently need to update the Browse component here.


> Long story short I wanted to ask if the container metadata is always created from the source metadata without checking if the container already exists in the database?

Yes. 

> If I assume correctly we see only 10 results each search and if we have more than 10 issues from the same journal I wouldn't see all of them. Could we limit the results to only show me the issues with the right numbers? Or rank the results on how many numbers are correct? Or maybe you have a different idea?

The completions are drawn from the internal suggestions and yes it is limited to 10. We can raise this number or the backend @anlausch provides a dedicated service for auto-completions.

**Comment by lgalke** [comment]
We identified the issue for #370 and I'll have a closer look tomorrow.

**Comment by lgalke** [comment]
Everything should now work seamlessly. See #396
I'll deploy it as soon as the PR is merged.

**Comment by lgalke** [comment]
#396 should've addressed it. It is now deployed on both dev and prod.
