### ISSUE TITLE
filter boxes via detector & namer

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#393]
I think filtering the different boxes doesn't work yet. At least I still see only `all` for both of them.
![scan_filter](https://user-images.githubusercontent.com/32642653/47025655-2d323500-d164-11e8-984d-3418ca5ece76.png)
I did interpret #355 right and this should work now, right?

**Comment by LauraErhard** [comment]
https://locdb.bib.uni-mannheim.de/extrapolate-dev/linking/ScanInspector/5bc5daeb1b67a1379318d467/5bc5ed7d1b67a137931a2955

But I just saw that only one box was detected, but that should have given me at least one different option to choose from.

**Comment by LauraErhard** [comment]
The dev system is now empty and the uploads don't switch again, so maybe we have to wait for that to work again to really test this.

**Comment by SylviaZander** [comment]
I have now uploaded a new title but the filters still do not work

https://locdb.bib.uni-mannheim.de/extrapolate-dev/linking/ScanInspector/5bc70bfc19bfec072e0b08cb/5bc71c74563e8b6c1800e50e

**Comment by anlausch** [comment]
Issue was solved with the newest deployment (there is now one example in the system)
