### ISSUE TITLE
identifiers missing right label

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#394]
Sometimes we don't see the label of an identifier. Maybe there is a category missing in the drop-down menu? Could you please check the backend?
![identifiers_category](https://user-images.githubusercontent.com/32642653/47026269-5acbae00-d165-11e8-8a1e-f4356d9df52d.png)

**Comment by lgalke** [comment]
Looks like we're missing an identifier scheme in the front-end.

**Comment by lgalke** [comment]
032d2e2 deploying to prod
