### ISSUE TITLE
Resource type not implemented

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#395]
## Expected Behavior

Resources of type 'PROCEEDINGS_ARTICLE' are properly ingested.

## Current Behavior

The back-end yields
```
{message: "Resource type not implemented."}
```

## Possible Solution

Implement the resource type, or conceal the "not implemented" ones in the front-end.

## Steps to Reproduce (for bugs)

1. Open Ingest View
2. Select resource type "PROCEEDINGS_ARTICLE"
3. Enter scheme DOI and a valid identifier
4. Insert the references as plain text 

## Context

I wanted to add [this article](https://dl.acm.org/citation.cfm?id=3209236) to our system using the plain-text references as extracted by ACM DL.

**Comment by anlausch** [comment]
https://github.com/locdb/loc-db/commit/b5573ebb4facdda2bd8f3eeb5fd24ece22d3c5a8
