### ISSUE TITLE
Proxy Errors and Service Unavailable Errors

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#397]
When I enter some custom query string (it was the same one as in #387 ), the `getInternalSuggestionsByQueryString` service returns Proxy Error and subsequent requests are responded with Service Unavailable **even when I change to an entry that worked completely fine before**.

After some time the other entries work just fine again. However the problem was reproducible.

See picture below, the selected log entry is the first one that errored and caused subsequent errors.

![image](https://user-images.githubusercontent.com/3439126/47115754-d578f400-d25f-11e8-8bac-ec51cfe7a86c.png)

My assumption is that there is a critical error in getInternalSuggestionsByQueryString, which causes also the subsequent errors (feels like it'd be rebooting, or being just not responsive for some time).

Can you have a look into that @anlausch ?

Context: dev-backend was used.

**Comment by lgalke** [comment]
I've now similar problems with just retrieving the ToDo items or uploading resources.

**Comment by anlausch** [comment]
The above issue should be resolved

**Comment by anlausch** [comment]
The above issue should be resolved

**Comment by anlausch** [comment]
The above issue should be resolved
