### ISSUE TITLE
Author IDs don't save as expected

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#412]
When I click on the i-button besides an author and enter an ID and click on `confirm`, then the value is not saved. However, it seems to work when I click afterwards on the plus-button to start with a new one. But this should not be needed for saving.

![2018-10-26_17-35-36](https://user-images.githubusercontent.com/5199995/47576867-cf60d280-d945-11e8-9b76-400d85251e0d.gif)

**Comment by lgalke** [comment]
Thanks Philipp. Yes it seems like we ended up in a strange situation after addressing

> It would be nice, if I didn't have to click on add identifier to open a new field. Could you show an empty row from the beginning?

from #336.

We will take care of it. Anything that is visible should be also saved, when 'Confirm' is pressed.

**Comment by zuphilip** [comment]
> Anything that is visible should be also saved, when 'Confirm' is pressed.

If visible and not empty, yes. Thank you!

**Comment by lgalke** [comment]
Please let me know whether the interface feels more convenient now.
