### ISSUE TITLE
Zombies back in production

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#415]
Many records without references are stuck in the Agenda for Electronic Resources:

![grafik](https://user-images.githubusercontent.com/33151732/47727324-81f1a780-dc5c-11e8-97f7-2ac4f16ca3f4.png)

**Comment by lgalke** [comment]
This is strange, I do set the status to valid upon migration. Is there anything else that could interfere @anlausch ?
I updated the front-end on production yesterday, so I don't see any problems in the front-end. Just to make sure, I'll update again now.

**Comment by kleinann** [comment]
They're still there. Really strange.

**Comment by kleinann** [comment]
I removed them manually, so the issue can be closed.
