### ISSUE TITLE
Stats page doesn't load for production

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#416]
https://locdb.bib.uni-mannheim.de/locdb/stats

produces the following error:

Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /locdb/stats.

Reason: Error reading from remote server

Apache/2.4.25 (Debian) Server at locdb.bib.uni-mannheim.de Port 443

**Comment by lgalke** [comment]
We are experiencing also performance problems at other points #414 . I'd guess this is related.

**Comment by kleinann** [comment]
The stats page for production still doesn't load (never did, in fact). The one for the dev-version does, on the contrary.
We were planning to use the stats for production it in the workshop (hands-on-session data quality), so if you could do anything... would be really great.

**Comment by lgalke** [comment]
@anlausch

**Comment by anlausch** [comment]
It actually works, but I assume your browser is cutting the connection at some point.
![image](https://user-images.githubusercontent.com/20592651/47798273-5c31d480-dd28-11e8-8ae4-bd5d80975ba0.png)

I will see whether I have enough time to compute it asynchronously.

**Comment by anlausch** [comment]
Quickfix: Stats computation can now be triggered via /triggerStats. After a while the actual stats then can be accessed via /stats.

**Comment by kleinann** [comment]
Yes, it works! Thanks a lot!

**Comment by anlausch** [comment]
I also added the br identifiers as discussed (but these are not computed on the contributor and embodiment statistics due to my time constraints atm).
