### ISSUE TITLE
Journal issue data not editable in production system

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#417]
In some records, journal issue data like volume, issue, and pages is shown in the short results list, but does not show up in the form when clicking the "edit" button. Example:
![grafik](https://user-images.githubusercontent.com/33151732/47776645-2a524b00-dcf3-11e8-9bca-086b54d3172d.png)

Quite frequently, page numbers are duplicated, and the second instance (probably connected to the journal issue) isn't editable and thus cannot be removed. Example:
![grafik](https://user-images.githubusercontent.com/33151732/47776852-9df45800-dcf3-11e8-8862-4521184f9d0b.png)

**Comment by lgalke** [comment]
Thanks for reporting. I will fix this tomorrow. My initial guess is that the Journal Volume Number field is filled with "15, pp.27-47" literally. On the other side the respective form field is of type number and can therefore not be properly filled with "15, pp.27-47. I'll change the Journal Volume Number field also to plain-text input.

**Comment by lgalke** [comment]
The volume number field is now of type string so it should display the information properly and make it editable.
