### ISSUE TITLE
Create childs for Journal Issue and Edited book

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#418]
Journal Issues and Edited books need a functionality to create a new child instead of a new container.
At the moment, only creating containers is possible:
![grafik](https://user-images.githubusercontent.com/33151732/47910982-b354b800-de94-11e8-82b2-b950550f2984.png)

![grafik](https://user-images.githubusercontent.com/33151732/47911017-c7001e80-de94-11e8-961e-a2c8b95f4210.png)

**Comment by lgalke** [comment]
Would you prefer to have the new button only visibles for certain types or always? In the former case, should it be enabled for all resources that can be a container?

**Comment by kleinann** [comment]
Exactly, it should be enabled for all resources that can be a container.
