### ISSUE TITLE
Fix trailing spaces in fields

### ISSUE THREAD

**Issue by zuphilip** [locdb/locdb-frend#425]
There are more than 400 spaces at the beginning of fields. I just search for `: " ` in the json dump. E.g.
```
    "journalArticle_title": " YouTube catches candidates in compromising positions",
        "literalValue": " http://www.usatoday.com/tech/news/techpolicy/ethics/2006- 08-22-youtube-embarrassing_x.htm?POE = click-refer",
        "literalValue": "  2002007737",
    "monograph_subtitle": " crime and punishment in American",
```
I guess we can delete all of them. Agree?

**Comment by zuphilip** [comment]
Also at the end of some values there a spaces...

**Comment by lgalke** [comment]
We can manually trim all strings in forms when editing. However, for the initial extraction of structured data, Anne needs to conduct the trimming. There is not always editing involved.

**Comment by zuphilip** [comment]
I would suggest to trim just before saving the data. Spaces which then can appear on initial import or are edited can be handled together.

**Comment by anlausch** [comment]
https://github.com/locdb/loc-db/commit/beb0f44b92ba90c5af5f4295918e3be5e0f496dd
