### ISSUE TITLE
Status changes back to "ToDo" in production

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#427]
Several resources that were completely processed and had the status valid have changed back to "todo". I found them in "Browse", but they're not in the Agenda. 
Example:
![grafik](https://user-images.githubusercontent.com/33151732/48001858-17cc7d00-e10a-11e8-83b2-d27d64fb1e62.png)

**Comment by kleinann** [comment]
Correction: They *are* in the Agenda. But I'm 100% sure that Jaffrelot was valid before.

**Comment by kleinann** [comment]
I think I know what it is now. If I don't use the new, yellow "migrate and link"-button, but create a new resource or migrate with the old "migrate" und "link" button inside the edit-form, the status stays "todo" and the resources appear in the Agenda.

**Comment by lgalke** [comment]
Thanks for finding this. The manually created resources also receive now the status valid. Before, there was no status manually assigned.

**Comment by anlausch** [comment]
cannot reproduce anymore
