### ISSUE TITLE
Zooming not working in Chrome

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#43]
The zooming works fine for Firefox but not for Chrome/Chromium.

**Comment by lgalke** [comment]
https://github.com/d3/d3/wiki states that

> D3 is tested against Firefox, Chrome, Safari, Opera, IE9+, Android and iOS.  

Is there some kind of other bug @chah3d ?

**Comment by chah3d** [comment]
https://stackoverflow.com/questions/37722487/chrome-issue-svg-transform 
seems to be an SVG version issue, fixed it for now. Movement of the image is still a bit erratic in chrome.

**Comment by lgalke** [comment]
Zooming towards the cursor position works by double-clicking or using the scroll-wheel.
