### ISSUE TITLE
Conversion of books in a book set from SWB

### ISSUE THREAD

**Issue by kleinann** [locdb/locdb-frend#430]
Book that are part of book sets are not correctly converted when they come from SWB.

Example:

PPN: | 006370462
Gesamttitel: | Gesammelte Werke / Robert Musil. Hrsg. von Adolf Frisé
Teil: | 8. Essays und Reden
Erschienen: | Reinbek bei Hamburg : Rowohlt, 1978
Umfang: | S. 977 - 1437
ISBN: | 3-499-30008-7

Our conversion:
![grafik](https://user-images.githubusercontent.com/33151732/48363448-3ef4f280-e6a6-11e8-94c5-40df5b5c1e5a.png)
![grafik](https://user-images.githubusercontent.com/33151732/48363474-4c11e180-e6a6-11e8-92c9-c4a63c96e8d6.png)

"Gesammelte Werke" should be the title of the container, not of the resource.
The title of the resource should be Essays und Reden, and it's number 8.
Robert Musil is author of both the book set and the book itself.

**Comment by anlausch** [comment]
https://github.com/locdb/loc-db/commit/892d5fb02c592c8c07bfffd8866f4f4be33aace2
