### ISSUE TITLE
OCR seems to have issues with cursiv

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#446]
I noticed that the OCR is very bad with cursiv letters e.g.:

![2019-04-03_ocr_scan](https://user-images.githubusercontent.com/32642653/55486921-73555500-562d-11e9-938c-42de46a70864.png)

![2019-04-03_ocr_refList](https://user-images.githubusercontent.com/32642653/55486848-4c971e80-562d-11e9-88aa-74bc29979c69.png)

**Comment by abdelqader-mohammad** [comment]
The Frontend does not influence the OCR process and only gets the results from the backend. @rtahseen can we do anything on this? can the increase in the quality of the scan (if possible) solve the problem?

**Comment by rtahseen** [comment]
This was an issue of OCR engine, which is resolved in new version. I have updated OCR engine to the latest version. I have tested offline and it works fine. It should resolve the issue now.

**Comment by rtahseen** [comment]
@LauraErhard any update on this issue?

**Comment by LauraErhard** [comment]
Yes, now the same scan delivers this result: 
![2019-04-10_ocr_nice](https://user-images.githubusercontent.com/32642653/55883690-0c90e800-5ba7-11e9-9436-790f89f90aaf.png)
Thanks for your quick work!
