### ISSUE TITLE
SWB suggestion can't be linked

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#450]
I tried to migrate this suggestion but I always get the following error:
![2019-04-24 502Error](https://user-images.githubusercontent.com/32642653/56657938-9659ae80-6699-11e9-88ff-0caffa23cb02.png)
Is there a larger problem or is this an isolated issue?

**Comment by abdelqader-mohammad** [comment]
I tested several SWB suggestions, and all of them succeeded to migrate.

**Comment by LauraErhard** [comment]
It seemed to be just this one reference, since then I didn't have anymore problems.
