### ISSUE TITLE
problems with database

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#452]
We noticed that we can't find our newly migrated entries via browse/in the internal suggestions while linking references. I wanted to check the backend: https://locdb.bib.uni-mannheim.de/locdb/bibliographicResources to see if our data is even correctly imported, but I always get an error message:
![LOCDBerror](https://user-images.githubusercontent.com/32642653/57435078-c037d700-723c-11e9-8bf1-710fc59b9e48.JPG)
I checked the Tübinger backend https://locdb.bib.uni-mannheim.de/locdb-tue/bibliographicResources and this doesn't work either.
The dev seems to work.

Is our newly migrated data properly saved? What is the issue with checking all resources in the backend?

**Comment by abdelqader-mohammad** [comment]
Tübingen worked for a while then went down again.
The production is still not working. @stweil is there a capacity problem?

![error](https://user-images.githubusercontent.com/46019130/57444367-490c3e00-7250-11e9-8cba-b527b3ef54b9.png)

**Comment by LauraErhard** [comment]
I checked with my colleagues there is no capacity problem, but both prod & tue show this error:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node /home/anlausch/locdb-prod/source/app.js]
 2: 0x55d1e56dc70e [node /home/anlausch/locdb-prod/source/app.js]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node /home/anlausch/locdb-prod/source/app.js]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node /home/anlausch/locdb-prod/source/app.js]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node /home/anlausch/locdb-prod/source/app.js]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node /home/anlausch/locdb-prod/source/app.js]
 7: 0x3faf9630eb86
```

**Comment by abdelqader-mohammad** [comment]
@LauraErhard I think there is no problem in the database. Maybe due to the large amount of data you want to retrieve from the database caused this error. I am not sure, but perhaps this is the reason for that error.

**Comment by zuphilip** [comment]
FYI it is possible to access an individual resource, e.g. https://locdb.bib.uni-mannheim.de/locdb/bibliographicResources/5cc2f8676fe387398c588dda

**Comment by zuphilip** [comment]
@LauraErhard The last error says "JavaScript heap out of memory" and this could be possible as the heap memory in node is limited, see e.g. https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory .

**Comment by LauraErhard** [comment]
> FYI it is possible to access an individual resource, e.g. https://locdb.bib.uni-mannheim.de/locdb/bibliographicResources/5cc2f8676fe387398c588dda
@zuphilip Can I only access an individual resource if I have the key, or can I search somewhere with title/author?

**Comment by zuphilip** [comment]
FYI we started all instances with more JS memory now.

**Comment by LauraErhard** [comment]
The backend is loading fine now, but the issue that we can't find our newly migrated entries via browse/in the internal suggestions while linking references still exists.

**Comment by stweil** [comment]
CC'ing @JKamlah.

**Comment by zuphilip** [comment]
Let us open a new issue #454 for that.
