### ISSUE TITLE
RSS Feed reader

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#48]
Back-end provides functionality [to store user-specific RSS feeds](https://locdb.bib.uni-mannheim.de/locdb-dev/docs/). We could show the feed reader besides the Todo Management in the initial Dashboard. As soon as a resource gets selected, it may disappear.

**Comment by lgalke** [comment]
Is this necessary until workshop?

**Comment by lgalke** [comment]
starting point 77b05f6fa7a9bebb7977d25ac4e0c365eddb5107

**Comment by lgalke** [comment]
ec8897e6f14f7845441a7bbd9064cc4d2d1d3392 continued. Mostly done, just the fetchFeeds method is raising `CORS` errors. Can you double check for our testing environment @anlausch ?

**Comment by anlausch** [comment]
![image](https://user-images.githubusercontent.com/20592651/33067305-02dfb93a-ceae-11e7-95f3-3b20435776aa.png)

I still think that everything works as discussed.

**Comment by lgalke** [comment]
We will update, for now we took the feeds passed with user data at login.

**Comment by lgalke** [comment]
outdated..
