### ISSUE TITLE
Option to stop OCR Processing

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#52]
OCR component already offers an interface for stopping OCR processing. We need to include analogous options in the back-end as well as the front-end.

**Comment by anlausch** [comment]
Probably we want to mirror restart

**Comment by lgalke** [comment]
Is this necessary for the workshop?

**Comment by lgalke** [comment]
If OCR has a lot of files queued, it does not listen to its restart service. Instead, we now have an option to delete `ToDoScans`, so that they can be uploaded again if necessary.
