### ISSUE TITLE
Type mismatch when committing resource edit form

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#57]
At some point there is still a mismatch between `number` and `string` types when submitting an edit resource form.

**Comment by lgalke** [comment]
Type mismatch is resolved. Still there is an issue when we submit `br.number = 0`, the property does *not* get updated as expected. @anlausch

**Comment by anlausch** [comment]
Which service causes the problem? Thanks. @lgalke

**Comment by lgalke** [comment]
PUT /bibliographicResource/${id}Am 11.10.2017 17:14 schrieb anlausch <notifications@github.com>:Which service causes the problem? Thanks. @lgalke

**Comment by anlausch** [comment]
Problem was due to inconsistencies in the database, resolved by setting up the dev system from scratch.
