### ISSUE TITLE
Contributers in Bibliographic Resource

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#58]
1. In the data for the individual entries (“Bibliographic Resource”) the "contributors" are not bold, like the other categories.
2. For the data re-use, the contributor name should be standardized. Should the name be split into family name and given name? Should there be a hint how to write the name in (family name, given name)? Should there be a link to the integrated authority file (GND = Gemeinsame Normdatei)?
3. Sometimes the PDFs contain the family name completely capitalized hence the OCR copies this spelling and has to be corrected manually. Is it possible to transform the names into the regular spelling (first letter capital, rest small)?

**Comment by lgalke** [comment]
Thanks for reporting the issue. The bold emphasis of the field should not be a problem. Splitting into family name and given name is indeed a good idea. The linking to authority files would be also a great feature. For now we only store raw text values without any links. Implementing the linking is probably out-of-scope for the workshop milestone, since it would also require searching all authors that are already stored in the LOCDB system in the same way we do it now with resources.

**Comment by lgalke** [comment]
Considering proper capitalization, it would probably be cleaner if it happens before the extracted data is passed to the front-end: either directly in the OCR component or the back-end. What do you think @anlausch

**Comment by zuphilip** [comment]
Just a note that this is probably more complicated: For example the author `DENYS DE LA PATELLIÈRE` or Spanish authors can have several first names and several last names and on the other hand `LIGO Scientific Collaboration` appears as authors of several papers.

Thus, I suggest to try to have a good automatic heuristic about lower/uppercase. The remaining errors can be corrected manually. But I wouldn't do anything about splitting into first and last name. Hopefully we can link to the correct publications (via CrossRef, OLC-Contents, our own DB, OpenCitations, WikiCite) where the metadata is hopefully entered correctly.

**Comment by lgalke** [comment]
Thats a good point @zuphilip . Plus, searching in the internal/external data sources is typically not case-sensitive. Thus when there is any matching resource, it should not be a problem. When we create a new resource from OCR data, it is probably okay to let the librarian adjust the proper spelling. If heuristics are still desired, the OCR component is probably the right spot.

**Comment by lgalke** [comment]
Author disambiguation is another big topic which might be out of project scope.
