### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#6]
# Deployment

## Option 1: Dockerfile

Use the dockerfile to fully deploy on remote machine.

- we need to install nodejs@latest (and npm@latest) even before `npm install`
- presumably requires root access to remote machine

## Option 2: `ng build && rsync`

Generate a self-contained `ng build` and deploy it on the remote machine via `rsync` (or `scp`)

- requires less access rights and less dependencies on remote machine
- initial attempt did not work...

## Option 3: Meta-repository with backend with Dockerfile

We could setup locdb/locdb-full as a meta repository including locdb/loc-db and locdb/locdb-frend as submodules and then create a complete Dockerfile for both the front-end and the backend.

**Comment by zuphilip** [comment]
We should speak about the options in some more details. Generally, I am fine with everything which works smoothly and is fine for you.

**Comment by lgalke** [comment]
True. At the moment the main concern is to find something that works at all (considering the locdb machine). Option 2 unfortunately did not work out of the box. And dynamic depenency installation (via `npm install`) did also fail, due to some connectivity (DNS related) issues.
I assume that there is another problem in general with passing of javascript through the global apache setup.

**Comment by lgalke** [comment]
After adjustment of  `base-href` the `ng build` variant did successfully deploy the prototype.
There's just one remaining problem regarding the cross-origin access of the back-end via http.
