### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#72]
## Steps to reproduce:

1. trigger OCR processing by clicking on the respective scan, tested with the scan attached to `The aptitude test workbook (`pdf` image).
2. wait 

## Error log
```
GET https://locdb.bib.uni-mannheim.de/locdb-dev/triggerOcrProcessing?id=59e754e1fbadab5565f23d87 502 (Proxy Error)

Failed to load https://locdb.bib.uni-mannheim.de/locdb-dev/triggerOcrProcessing?id=59e754e1fbadab5565f23d87: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 502.

 0 -  {"isTrusted":true}
```

This happens not only in the local testing environment but also when deployed on the LOCDB server.

Might be solved after new ocr component service gets deployed. The error message is only slightly different  ( `SyntaxError: Unexpected token < in JSON at position 0` instead of `{"isTrusted":true}`.

**Comment by rtahseen** [comment]
Can you please try again with some other file? I just checked and found out that the file which was uploaded last time had low dpi than required and system could not process it.

**Comment by lgalke** [comment]
I will try in the afternoon with some files I find in the owncloud. Thanks.

**Comment by lgalke** [comment]
It also failed for some other document from the current test collection in owncloud (directory 'Neuzugang 2017'). However this one was also split across several pages, can the system handle such scenarios already?

**Comment by lgalke** [comment]
```
GET https://locdb.bib.uni-mannheim.de/locdb-dev/triggerOcrProcessing?id=59e754e1fbadab5565f23d87 502 (Bad Gateway)
```

**Comment by rtahseen** [comment]
Please try it with dev version web service of OCR component.

**Comment by lgalke** [comment]
That's great. We can close this as soon as the back-end conversion and front-end access is also up and running.

**Comment by anlausch** [comment]
We are now on the new version of the ocr component.

**Comment by lgalke** [comment]
Proxy Error is resolved.
