### ISSUE TITLE
PPN Format

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#75]
What is the exact format of the PPN used? 8 digits + either X or a ninth digit? (Inferred from a sample of 'Neuzugang 2017')

```vim
\d\{8}[X0-9]
```

If confirmed, adapt `ScanComponent` accordingly.

**Comment by lgalke** [comment]
@zuphilip @LauraErhard can anyone assert that this format is correct?

**Comment by zuphilip** [comment]
The last digit position could also be a check digit, cf. http://swbtools.bsz-bw.de/cgi-bin/help.pl?cmd=kat&val=0100&regelwerk=RDA&verbund=SWB .

**Comment by lgalke** [comment]
Great, thanks. Fixed for now via 4aa9714 . I assume that the final (ninth) position is now either a number or a literal 'X'. Hope this is correct.
