### ISSUE TITLE
Dont jump to top when triggering ocr processing

### ISSUE THREAD

**Issue by lgalke** [locdb/locdb-frend#86]
When one clicks on a scan item in the todo component, the page jumps to the very top due to the `a href='#'` tag. That is disturbing. We should find another solution (buttons?).

**Comment by LauraErhard** [comment]
The same happens when you click on enter information after the file upload.

**Comment by lgalke** [comment]
Good point. Since just now d677de1 the scan items are buttons instead of pseudo-links, thus there will be no more jumps. The scan upload view still needs the update. @chah3d

**Comment by LauraErhard** [comment]
The buttons are more convenient but the design is very aggressiv. Is it possible to change the colour back to the original light blue? What does the combination of numbers and letters (e.g. 59e5bc5) mean?

**Comment by lgalke** [comment]
The new version should retain the colors and look-and-feel of before the change, while the functionality is fixed to not push the user to the very top of the page. I just uploaded a new version (make sure to reset the cache, if the changes do not appear immediately).
