### ISSUE TITLE
Bug uploading monographs

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#92]
After choosing a monograph PDF file (filename just the ppn) in the file upload component, I can't upload the file, because there is a pop up window that says the file is not ready. If I fill in the page numbers (which are not needed for monographs) the file changes to ready, but after clicking upload I just see a lot of mysterious hieroglyphics: 

> [ { "ppn": "493223657", "firstpage": 127, "lastpage": 128, "file": {}, "filecontent": "%PDF-1.5\n%§ãññ\n2 0 obj\n<<\n/Type /Catalog\n/Version /1#2E5\n/Pages 4 0 R\n/PieceInfo 5 0 R\n>>\nendobj\n14 0 obj\n<<\n/Filter /FlateDecode\n/Length 34\n>>\nstream\r\nx+ä210W0\u0000B3SS0Ë¥ïk àÏ\u0015È\u0005\u0000b¶\u0006^\r\nendstream\nendobj\n16 0 obj\n<<\n/Filter /FlateDecode\n/Length 34\n>>\nstream\r\nx+ä214S0\u0000B3\u0013S0Ë¥ïk àÏ\u0015È\u0005\u0000b£\u0006]\r\nendstream\nendobj\n18 0 obj\n<<\n/Filter /FlateDecode\n/Length 34\n>>\nstream\r\nx+ä21°P0\u0000B3\u0013S0Ë¥ïk àÏ\u0015È\u0005\u0000b½\u0006^\r\nendstream\nendobj\n20 0 obj\n<<\n/Filter 

And so on

**Comment by lgalke** [comment]
Agreed. The constraint of page-numbers should be removed for monographs. The mysterious hieroglyphs are the raw file contents, which is displayed as debug information.

**Comment by lgalke** [comment]
- [x] page numbers not mandatory anymore if type is `"MONOGRAPH"`
- [x] page number inputs are also not displayed in this case
- [x] guessing of resource type: pages could be extracted from filename leads to `"COLLECTION"` else `"MONOGRAPH"`
- [x] validity checks adapted so that no open/close is necessary if information could be fully extracted.

f6757f2

**Comment by LauraErhard** [comment]
It runs smoothly now. Thank you.
