### ISSUE TITLE
Bug uploading collections

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#93]
In the file upload component when trying to upload a colletion there seems to be a transcription error in the majority of cases. Sometimes the ppn is missing or the page information is not right.
![screenshot-2017-10-26 loc-db frontend 1](https://user-images.githubusercontent.com/32642653/32055131-2ddc4100-ba61-11e7-96d3-129bd65cb544.png)

If you change the page numbers manually, the information is stored in the field and when I upload a new file after that the numbers are still in the field. I can see under the file upload component that the right page information is in the system:
![screenshot-2017-10-26 loc-db frontend](https://user-images.githubusercontent.com/32642653/32055368-e4f29a38-ba61-11e7-91ba-5548ac1851ee.png)

**Comment by lgalke** [comment]
That is an interesting issue, especially since the numbers are actually extracted correctly (as shown in the screenshots) but **not** displayed correctly.

**Comment by lgalke** [comment]
As in #92, there were some changes, also improving the extraction of ppn and page numbers. Could you recheck this one more time? Thanks for reporting those issues!

**Comment by lgalke** [comment]
Some more bugs were fixed, everything should be working now.

**Comment by LauraErhard** [comment]
It runs smoothly when uploading a file with two page numbers (citations are on more than one page per chapter) but if the file only contains one page number (one page of citations per chapter) the system guesses that this is a monograph. Because of this I can't even put the page numbers in manually.

**Comment by lgalke** [comment]
I see, so when the file name has one file number, the guess would still be 'collection' and but we only need a single file number, correct? this is clearly not supported yet, extraction only finds something in the file name when there is a starting and an ending page. On the other hand, you should be able to manually select `COLLECTION` and then the page number input elements should appear.

**Comment by LauraErhard** [comment]
Yes the guess would still be 'collection' if only one page number is available. 
You are right I can change the setting to 'collection' and the input element appears. But if I just put in the one page number the pop up window appears that the file is not ready. If I put in the same number in start and end page nothing happens and the console error is as follows:
`Send Scans failed:  Object { _body: ""Not authenticated."", status: 401, ok: false, statusText: "Unauthorized", headers: Object, type: 2, url: "https://locdb.bib.uni-mannheim.de/l…" }`

**Comment by LauraErhard** [comment]
Sorry I didn't want to close this just now, I got the wrong button.

**Comment by lgalke** [comment]
No problem. "No authenticated" is typically a problem of the login status. Due to our current implementation of user management via HTTP sessions there is a possibility that the session gets closed after some time without action. In this case the GUI is not updated. In a final version, we would catch the `401` error and e.g. display a login prompt. Regarding the issue itself: a possible workaround for now would be to insert starting page: 5 ending page: 5. In the future we could also improve in this case.

**Comment by LauraErhard** [comment]
Thank you for this information. Now I will make sure to login again when I see a "not authenticated" error. 

The workaround with the same starting and ending page works fine.
