### ISSUE TITLE
Todo component empty & can't upload a new file

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#95]
After loggin in and reloading the todo component it stays empty. If I want to upload a file it seems to work (there is no debug information at the bottom) and the file disappears from the file upload component. But I can't see anything in the todo component even after several reloads and like 10 minutes of waiting in between.

Edit: Now after clicking upload the file stays in the file upload and doesn't disappear like before. Maybe I was too eager and the system thinks it is a DOS attack again?

**Comment by lgalke** [comment]
```
GET https://locdb.bib.uni-mannheim.de/locdb-dev/getToDo?status=OCR_PROCESSED 502 (Proxy Error)
```
The back-end throws an error when trying to access the Todo list. Apart from that, whenever the file stays in the file upload list it is most likely that the PPN  does not exist in SWB (we should provide an appropriate error message in that case)

**Comment by LauraErhard** [comment]
I double checked the PPN and it definitely exists in the SWB:
![screenshot-2017-10-27 loc-db frontend 1](https://user-images.githubusercontent.com/32642653/32093422-7b23fe62-bafc-11e7-94ce-72c1539a86f7.png)
![screenshot-2017-10-27 swb online-katalog - results availability](https://user-images.githubusercontent.com/32642653/32093423-7cf111f8-bafc-11e7-8acd-3d8d36206c93.png)

**Comment by lgalke** [comment]
Could you try once more please? Now the todo's are getting retrieved again and everything should be up and running.

**Comment by LauraErhard** [comment]
It works with the above example. But I tried a different one (PPN 486376729) and got this error message:
`Send Scans failed:  Object { _body: ""Not authenticated."", status: 401, ok: false, statusText: "Unauthorized", headers: Object, type: 2, url: "https://locdb.bib.uni-mannheim.de/l…" }`

**Comment by anlausch** [comment]
"Unauthorized" means usually that you are just not logged in. This may be for example due to a new version of the backend being deployed. I would suggest that you retry the same actions and check if the problem persists.

**Comment by LauraErhard** [comment]
I made sure that I am logged in, now I get a different error:
`Send Scans failed:  Object { _body: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD…", status: 503, ok: false, statusText: "Service Unavailable", headers: Object, type: 2, url: "https://locdb.bib.uni-mannheim.de/l…" }`

**Comment by anlausch** [comment]
Could you maybe post the full url of the endpoint? The value in your error message in the property "url". Thanks!

**Comment by LauraErhard** [comment]
It is "https://locdb.bib.uni-mannheim.de/locdb-dev/saveScan" 

If I click on this URL it gives me this:
`Error: Path [/saveScan] defined in Swagger, but GET operation is not.
    at middleware (/home/anlausch/locdb-dev/source/node_modules/swagger-node-runner/lib/connect_middleware.js:31:21)
    at Layer.handle [as handle_request] (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:317:13)
    at /home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:335:12)
    at next (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:275:10)
    at cors (/home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:188:7)
    at /home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:224:17
    at originCallback (/home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:214:15)
    at /home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/home/anlausch/locdb-dev/source/node_modules/cors/lib/index.js:204:7)
    at Layer.handle [as handle_request] (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:317:13)
    at /home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/anlausch/locdb-dev/source/node_modules/express/lib/router/index.js:335:12)`

**Comment by anlausch** [comment]
Thank you! .. that you get the error when clicking on the url is by design. No problem here. I will investigate regarding the other issue.

**Comment by anlausch** [comment]
The issue with this particular PPN (486376729) is that in Marc21 field 773$g, which was mapped by Annette to the open citations property "number", we have  "(2013), S. 217-234" (See xml below). In our data model, however, this field can only contain numbers and not string values. I've set this property type to string now.. but, is this right? Someone with library meta data knowledge needs to look at this maybe.  

<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="http://swbtest.bsz-bw.de/sru/?xsl=searchRetrieveResponse" ?>
<srw:searchRetrieveResponse xmlns:srw="http://www.loc.gov/zing/srw/"
			    xmlns:dc="http://purl.org/dc/elements/1.1/"
			    xmlns:diag="http://www.loc.gov/zing/srw/diagnostic/"
			    xmlns:xcql="http://www.loc.gov/zing/cql/xcql/">
    <srw:version>1.1</srw:version>
    <srw:numberOfRecords>1</srw:numberOfRecords>
    <srw:resultSetId>SID2e0f81ae-226S1007</srw:resultSetId>
    <srw:records>
    


<srw:record>
<srw:recordSchema>marc21</srw:recordSchema>
<srw:recordPacking>xml</srw:recordPacking>
<srw:recordData>
<record>
<leader>     naa a22     2  4500</leader>
<controlfield tag="001">486376729</controlfield>
<controlfield tag="003">DE-576</controlfield>
<controlfield tag="005">20171004125806.0</controlfield>
<controlfield tag="007">tu</controlfield>
<controlfield tag="008">171004s2013    xx             00 0 eng c</controlfield>
<datafield tag="035" ind1=" " ind2=" "><subfield code="a">(DE-599)BSZ486376729</subfield></datafield>
<datafield tag="040" ind1=" " ind2=" "><subfield code="a">DE-576</subfield>
<subfield code="b">ger</subfield>
<subfield code="c">DE-576</subfield>
<subfield code="e">rakwb</subfield></datafield>
<datafield tag="041" ind1=" " ind2=" "><subfield code="a">eng</subfield></datafield>
<datafield tag="084" ind1=" " ind2=" "><subfield code="a">IN: PE 1075 COM 2013</subfield></datafield>
<datafield tag="100" ind1="1" ind2=" "><subfield code="a">Bolze, Christine</subfield></datafield>
<datafield tag="245" ind1="1" ind2="0"><subfield code="a">ƠTheƠ verb to be in the West Saxon Gospels and the Lindisfarne Gospels /</subfield>
<subfield code="c">Christine Bolze</subfield></datafield>
<datafield tag="260" ind1=" " ind2=" "><subfield code="a">Amsterdam,</subfield>
<subfield code="c">2013</subfield></datafield>
<datafield tag="773" ind1="0" ind2="8"><subfield code="i">In</subfield>
<subfield code="a">Comparative studies in early Germanic languages : with a focus on verbal gories</subfield>
<subfield code="d">2013</subfield>
<subfield code="g">(2013), S. 217-234</subfield></datafield>
<datafield tag="935" ind1=" " ind2=" "><subfield code="b">druck</subfield></datafield>
<datafield tag="936" ind1="u" ind2="w"><subfield code="j">2013</subfield>
<subfield code="h">217-234</subfield></datafield></record></srw:recordData><srw:recordPosition>1</srw:recordPosition></srw:record>
</srw:records>
    <srw:echoedSearchRetrieveRequest>
	<srw:version>1.1</srw:version>
	<srw:query>pica.ppn+%3D+%22486376729%22</srw:query>
	<srw:xQuery><xcql:searchClause><xcql:index>pica.ppn</xcql:index><xcql:relation><xcql:value>=</xcql:value></xcql:relation><xcql:term>"486376729"</xcql:term></xcql:searchClause></srw:xQuery>
	<startRecord>1</startRecord>
	<maximumRecords>1</maximumRecords>
	<srw:recordPacking>xml</srw:recordPacking>
	<srw:recordSchema>marc21</srw:recordSchema>
	<sortKeys>none</sortKeys>
	<srw:stylesheet>http://swbtest.bsz-bw.de/sru/?xsl=searchRetrieveResponse</srw:stylesheet>
    </srw:echoedSearchRetrieveRequest>
    <diag:diagnostics>
        <diag:uri>info:srw/diagnostic/1/0</diag:uri>
	
	
    </diag:diagnostics>
    <srw:extraResponseData>
	<rob:authenticationToken xmlns:rob="info:srw/extension/2/auth-1.0">U998,Pbszgast,I17,B0728+,SY,NRecherche-DB,D2.1,E2e0f81ae-226,A,H,R193.197.31.28,FY</rob:authenticationToken>
        <mg:resultGrouping xmlns:mg="info:srw/extension/5/metadata-grouping-v1.0">
	    
	    <mg:grouping key="9008" description="Sysflag"></mg:grouping>
	    
	    <mg:grouping key="9001" description="Materialart"></mg:grouping>
	    
	    <mg:grouping key="9000" description="Erscheinungsjahr"></mg:grouping>
	    
	    <mg:grouping key="9030" description="LibID-ADI"></mg:grouping>
	    
	    <mg:grouping key="9005" description="jetzt AUI"></mg:grouping>
	    
	    <mg:grouping key="9002" description="Region"></mg:grouping>
	    
	    <mg:grouping key="9004" description="Sprache"></mg:grouping>
	    
	    <mg:grouping key="9015" description="Erschliessungsmaterial"></mg:grouping>
	    
	    
	</mg:resultGrouping>
    </srw:extraResponseData>
</srw:searchRetrieveResponse>

**Comment by zuphilip** [comment]
The data for this PPN is wrong and it seems that you use the wrong database. @anlausch Are you currently using the SWB test database? You should use the production database from the SWB which is reachable under `z3950n.bsz-bw.de` see also https://wiki.bsz-bw.de/doku.php?id=v-team:daten:z39.50neu .

**Comment by anlausch** [comment]
Changed with https://github.com/locdb/loc-db/commit/3807c9f4dc1226f51c4d68fc79046f41eac8f0d8

**Comment by lgalke** [comment]
Okay I assume that I need to adapt the `number` property aswell. is this correct? @anlausch

**Comment by anlausch** [comment]
yes

**Comment by lgalke** [comment]
For now everything seems to work without adapting the `number` property. I will do it then after our meeting. :ok_hand:

**Comment by LauraErhard** [comment]
Is it possible to delete the file with the PPN 486376729 (Title: ƠTheƠ verb to be in the West Saxon Gospels and the Lindisfarne Gospels). I want to test if it works now and I can't do this while the file with the wrong data is already in the todo component.

**Comment by lgalke** [comment]
I am curious what would happen if you pressed `Edit` and then `Delete` on the `ToDo` resource. So far the delete operation was only tested on the right-hand side.

**Comment by LauraErhard** [comment]
I just tried to delete the file with the PPN 486376729 and now every OCR processed file is gone!?

**Comment by LauraErhard** [comment]
Now the todo component seems normal again. The delete function has only deleted the metadata but the pdf file seems to be still online:
![screenshot-2017-10-30 deleted_file](https://user-images.githubusercontent.com/32642653/32163393-72950bb2-bd5c-11e7-935a-f1d45d2919ae.png)

**Comment by anlausch** [comment]
@lgalke In my tests this seems to work fine in the back end .. but I noticed, that you are only deleting parent resources for nested resources. These all have separate identifiers.

**Comment by lgalke** [comment]
Deleting a resource is not the best way to get rid of its attached scans, since also e.g. other resources pointing to it would become invalid. A `DELETE /scan` rest functionality is desired.

**Comment by lgalke** [comment]
The discussion diverged from the original topic, #124 should address the remaining problem.
