### ISSUE TITLE
Logout bug

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#96]
I noticed that after loggin out the current session is maybe not closed? I can still try to upload files and reload the todo component (that was yesterday, now I can't see anything (issue #95), but I think this issue stayed).

**Comment by anlausch** [comment]
I just tested again the back end regarding this using the swagger ui as well as using the unit tests. When logging out I cannot access any data anymore. That's why I guess that this is only front-end related.

**Comment by lgalke** [comment]
I have no idea how the front-end could possibly fetch the data from the back-end without being authenticated (via HTTP Session), even if it is not possible in the tests. We know that sessions cause some strange behavior. On pressing `/logout` the appropriate request is send to the back-end. I will recheck it.

**Comment by lgalke** [comment]
Closed for now. If the bug is still present and not caused by strange HTTP session behaviour, please reopen.
