### ISSUE TITLE
bug clear function in file upload component

### ISSUE THREAD

**Issue by LauraErhard** [locdb/locdb-frend#97]
The clear function in the file upload component seems to be buggy. After clicking clear all the information disappears and I see the "durchsuchen..." option. But after choosing a different file there seems to be a problem. 
The resource typ always stays the same:
![screenshot-2017-10-27_resourcetype](https://user-images.githubusercontent.com/32642653/32090606-8b927ff0-baf0-11e7-9c11-99d23236e09d.png)

Sometimes the PPN is not changed:
![screenshot-2017-10-27_ppn](https://user-images.githubusercontent.com/32642653/32090615-9bed7c42-baf0-11e7-8d2b-d4b8d0d3aea5.png)

The page information is not changed:
![screenshot-2017-10-27 loc-db frontend](https://user-images.githubusercontent.com/32642653/32090956-41451f1e-baf2-11e7-8a65-f6b5fdca20ae.png)

**Comment by lgalke** [comment]
I will make sure that all information, esp the metadata is deleted, when clicking `clear`.

**Comment by lgalke** [comment]
should be fixed by 14a9ef3

**Comment by LauraErhard** [comment]
I tested it several times. It works smoothly now. Thank you
